LICENSE.md
README.md
pom.xml

Updated readme and added Public Domain license

DPC-100: Opensource project

---

.gitignore
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/BlueButtonClient.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/BlueButtonClientException.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/BlueButtonClientModule.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/BlueButtonClientSetupException.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/DefaultBlueButtonClient.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/MockBlueButtonClient.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java
dpc-aggregation/src/test/java/gov.cms.dpc.aggregation/bbclient/BlueButtonClientTest.java

BBclient needs to be able to fetch explanation of benefit data from the bluebutton server.

DPC-142: Add EOB-fetching functionality in BBclient

---

.codeclimate.yml

This commit adds a codeclimate.yml file to the repo, which means we can now version our changes within the repo itself, rather than requiring the GUI.

DPC-167: Add CodeClimate config

---

dpc-common/pom.xml

The hibernate coordinates are incorrect.
This should fix it.

Fix Hibernate path

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/BlueButtonClient.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/DefaultBlueButtonClient.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/bbclient/MockBlueButtonClient.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/bbclient/BlueButtonClientTest.java
dpc-aggregation/src/test/resources/bb-test-data/coverage/20140000008325.xml
dpc-aggregation/src/test/resources/bb-test-data/coverage/20140000009893.xml
dpc-api/src/test/java/gov/cms/dpc/api/EndToEndRequestTest.java
dpc-api/src/test/java/gov/cms/dpc/api/FHIRSubmissionTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/JobResourceTest.java
dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobModel.java

**Why**
Add the Coverage resource type in addition to the Patient and Explanation Of Benefit resource types.
No major changes. BlueButtonClient has a new method requestCoverageResource to fetch the Coverage resource type. 
Followed existing patterns, waiting for DPC-241 to refactor. 
**What's Next**
DPC-241 - Refactor Aggregation Engine
**Fixes**
DPC-238

Rick/dpc-238 Add coverage resource

---

dpc-web/app/assets/stylesheets/components/_site-blocks.scss

**Why**
Improve the visual design and typographic hierarchy. 
Font size for headings of section blocks
https://jiraent.cms.gov/browse/DPC-417

update font size of section block headings

---

README.md
pom.xml

**Why**
Easier setup for manual testing
Added documentation on a header which should be set.

Update headers needed for manual testing in README

---

dpc-api/src/test/java/gov/cms/dpc/api/EndToEndRequestTest.java

**Why**
The `EndToEndRequestTest` would register the provider into the system after running it once, making it fail if it was run twice in a row.
Added a `try/catch` block to account for the case where the provider was registered (via a previous run of this test).
Added a `try/catch` as opposed to resetting the project completely in the test or leaving it untouched (since this wasn't hurting the CI).
No Ticket
N/A

Made EndToEnd test more comprehensive

---

dpc-web/app/assets/stylesheets/components/_accordions.scss
dpc-web/app/views/pages/faq.html.erb
dpc-web/app/views/pages/support.html.erb

**Why**
We need to have a page to address some questions that have come up during research interviews but would not be appropriate to place on the landing page.
In addition to the content, some other changes include:
- css updates
- hooking up links
https://jiraent.cms.gov/browse/DPC-440

write faq content

---

dpc-web/app/views/shared/_head.html.erb

Robots tag to hide from search engine:

add robots meta tag to hide from search engines

---

dpc-web/app/views/shared/_head.html.erb

should be `nofollow` instead of `follow`

fix typo in meta tag

---

dpc-web/app/views/public/home.html.erb

- Adds FAQ to the landing page
- Updates a line of text.

add faq link and update some text

---

dpc-web/app/views/pages/faq.html.erb

fix rebase error on faq

---

dpc-web/app/views/shared/_navbar.html.erb

update login button layout

---

dpc-web/app/views/devise/registrations/edit.html.erb
dpc-web/app/views/pages/faq.html.erb
dpc-web/app/views/public/home.html.erb

**Why**
CMS wanted to change the voice from 1st person to 3rd. 
All instances of _we_ are to be changed to _CMS_.

Change instances of we to CMS

---

dpc-web/app/views/devise/registrations/new.html.erb

- just an update to the empty option in a select box

select text

---

dpc-web/Gemfile
dpc-web/config/environments/production.rb
dpc-web/config/initializers/health_check.rb
dpc-web/docker/entrypoint.sh

**Why**
A few changes are needed for our Ruby docker container to better handle production usage.
- Fixes issues with static assets not being compiled or served correctly on the Rails production profile.
- Adds a health check available at /health_check via the Ruby gem [health_check](https://github.com/ianheggie/health_check)
- Checks the database is up and has connectivity
- Checks the database is running the latest migrations (that the Docker instances knows about)
- Checks the Rails web server is running
- Fixes logging in the Rails production profile.
None
DPC-455: Serve static resource from Apache in web Docker container
**Checklist**

Production Ready Rails Docker Container

---

dpc-web/app/views/shared/_head.html.erb

This will remove the meta tag that prevents search engines from indexing the site.

MERGE 7/30 ONLY!!!! allow site to be indexed by search engines

---

dpc-web/app/views/pages/reference.html.erb

**Why**
Just makes it so the the text can fit on one line.

fixes left nav text to fit on one line

---

dpc-web/app/views/devise/registrations/edit.html.erb
dpc-web/app/views/devise/registrations/new.html.erb

**Why**
Just adds "(optional)" to address line 2 label.

indicate that address 2 is optional

---

dpc-web/app/views/devise/registrations/edit.html.erb
dpc-web/spec/controllers/docs_controller_spec.rb

Danger zone -> Delete my account
Are you sure? -> Are you sure you want to delete your account?

fix delete my account language

---

dpc-web/app/views/pages/reference.md

**Why**
Some wording was weird, some links didn't exist, and some things didn't make sense.
Added some links and reworded things.
Used [CMS's NPI](https://www.cms.gov/Regulations-and-Guidance/Administrative-Simplification/NationalProvIdentStand/) over [FHIR's NPI](http://hl7.org/fhir/namingsystem-registry.html
) Definition
**Checklist**

Made Changes to Developer Documentation

---

dpc-web/app/views/pages/faq.html.erb

update privacy info on faq page

---

dpc-web/app/views/pages/terms_of_service.md

This bullet point was lost after OGC review but before posting to the site, so adding it in now.
**Why**
**Checklist**

Adding in Other Responsibility

---

ig/framework/_includes/analytics.html
ig/framework/_includes/footer.html
ig/framework/_includes/header.html
ig/source/resources/implementationguide/ig-new.json
ig/source/resources/implementationguide/ig-new.xml

**Why**
Analytics were breaking IG 
- moved analytics code to where the other javascript was being imported
- used older version of google analytics' tracking code that doesn't rely on an async external script import
- I'm unfamilar with ig and I wasn't able to figure out where the generated html was being put — so I'm not 100% sure this will work
- I'm not sure what domain this will be on; if it is a different domain than `dpc.cms.gov`, we'll need to create a new thing in analytics (i can do this)
**Checklist**

Potentially Fixed IG Analytics [Needs Proper Testing]

---

dpc-web/package-lock.json

**Why**
Needed to keep dependencies up to date
`package-lock.json`
Update the dependencies again in the future
**Checklist**

Updated Packages for dpc-web

---

dpc-web/app/assets/javascripts/components/_followup.js
dpc-web/app/assets/stylesheets/application.scss
dpc-web/app/assets/stylesheets/components/_fields.scss
dpc-web/app/controllers/application_controller.rb
dpc-web/app/models/user.rb
dpc-web/app/views/devise/registrations/edit.html.erb
dpc-web/app/views/devise/registrations/new.html.erb
dpc-web/app/views/dpc_registrations/profile.html.erb
dpc-web/db/migrate/20190801183311_add_num_providers_to_users.rb
dpc-web/db/schema.rb
dpc-web/spec/models/user_spec.rb
dpc-web/spec/requests/user_registers_spec.rb

**Why**
It would be a benefit to know company sizes for registrations.
Added migration to add num_providers to the User model. Whitelisted num_providers, added specs, and inserted column into views.

Add number of providers to Users: Addresses DPC-495

---

dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIModule.java

Temporarily disable until a better solution is implemented.
**Why**
**Checklist**

Disable attribution healthcheck

---

dpc-web/app/views/pages/reference.md

**Why**
The documentation was unclear as to how to actually update a group, we also had a typo in one of the POST operations. This should fix it.
**Checklist**

Updated documentation to add clarity to attribution flow

---

dpc-web/app/views/pages/reference.md

**Why**
Another copy/paste error in the docs, simple fix.
Fix resource payload in Practitioner submission.
**Checklist**

Fix practitioner submission

---

dpc-web/docker/entrypoint.sh

Set the port to bind rails to to work around a puma issue

---

dpc-web/app/views/pages/reference.md

**Why**
A few documentation issues were noted in the Google group, as well as some stragglers from the Connectathon.
A few small tweaks and corrections.
**Checklist**

Documentation updates to correct FHIR examples.

---

lgtm.yml
src/main/resources/lgtm.settings.xml

**Why**
Static analysis is always a good thing, why not add some more?
The BlueButton frontend team just rolled out support and it looks like there are a lot of good security analysis checks for Java, which CodeClimate doesn't seem to have.
Added LGTM config file and custom maven settings file to ensure we don't get build failures due to Docker not being present on the system.
This may not be a great idea, but we'll give it a shot. It might be really noisy and confusing.
DPC-685: Add LGTM.
**Checklist**

DPC-685: Add LGTM support

---

dpc-web/app/services/api_client.rb
dpc-web/spec/services/api_client_spec.rb

Explicitly use ssl in API requests when not in local dev/test

---

dpc-web/app/assets/stylesheets/components/_buttons.scss
dpc-web/app/assets/stylesheets/components/_navbar.scss

**Why**
This PR will address the purple visited sytling that occurs on the logo. There should be no visited styling on the logo. 
Just added a new CSS selector

fix visited styling on logo

---

dpc-web/app/mailers/application_mailer.rb

Changes default from from from@example to no-reply@dpc.cms.gov

change default mailer from

---

dpc-web/app/views/pages/reference.md
ig/source/resources/patient/DPC-sample-patient.json

**Why**
We need to update the documentation to account for the new negative identifier values in DPR
Updated the patient identifier values in the docs and the FHIR IG to be negative, in accordance with the DPR values.
Also added a note to the docs to let people know that we will be migrating to MBIs in the near future.
**Checklist**

Updated bene_id to new value for BFD DPR.

---

dpc-web/app/views/pages/reference.md

**Why**
Link is broken
Change the link
**Checklist**

Update FHIR backend auth link

---

dpc-consent/src/main/java/gov/cms/dpc/consent/cli/ConsentCommand.java

**Why**
Deploy is still failing. This is one more try to get things working.
Commented out the line of code that's causing the issue. Verified that the service starts correctly.
**Checklist**

Hotfix: Remove call to FHIR client.

---

dpc-aggregation/src/main/resources/migrations/queue.migrations.xml

**Why**
Per our new policy to separate DB migrations from other changes, this is a DB migration-only PR 
New columns in the queue database
The rest of DPC-34 is another PR
**Checklist**

DPC-34: DB Migrations for _since

---

dpc-web/app/views/public/_hero.html.erb

**Why**
Adjust language in the note under request access.
To be clearer about the status of DPC's pilot program.
**Checklist**

Update DPC note language

---

Makefile

**Why**
IG publisher url link changed
**Checklist**

DPC-1368 update url for ig publisher jar

---

Makefile
src/test/prod.smoke_test.yml

**Why**
Prod needs it's own smoke test config
Added a prod smoke test config
https://jiraent.cms.gov/browse/DPC-1205
**Checklist**

add prod smoke test config

---

dpc-web/app/views/user_mailer/provider_sandbox_email.html.erb

**Why**
Updated language in mailer sent to users when they're added to a registered organization.
[DPC-440](https://jira.cms.gov/browse/DPC-440)
**Checklist**
- [\] Swagger documentation has been updated
- [\] FHIR documentation has been updated
- [\] Any required dpc-ops changes have a PR submitted and mentioned in this ticket
- [\] Any manual migration steps are documented, scripts written (where applicable), and tested
- [\] Before merging, any required dpc-ops changes have been approved and merged into master of the dpc-ops repo

DPC-440: Change mailer language

---

.github/pull_request_template.md

**Why**
Because it had to be done for more structure between both teams.
Old template had something left to be desired, ported BCDA template since it was general enough
Everything.
More structure = more consistency 
Add whatever you think is necessary

Feature: Update pull request template

---

dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractEndpointResource.java

**Why**
Swagger file was failing validation due to errors in the "Endpoint" resource.
Extra annotation in a resource was generating extra and unwanted swagger content.
NA
https://jira.cms.gov/browse/DPC-472
NA
**Checklist**
- [NA] FHIR documentation has been updated
- [NA] Any required dpc-ops changes have a PR submitted and mentioned in this ticket
- [NA] Any manual migration steps are documented, scripts written (where applicable), and tested
- [NA] Before merging, any required dpc-ops changes have been approved and merged into master of the dpc-ops repo

Removed @Api annotiation from AbstractEndpointResource

---

src/test/EndToEndRequestTest.postman_collection.json

Several Postman tests were inadvertently duplicated with pull request #894 . This PR removes them.

Deduplicate Postman tests

---

dpc-api/src/main/java/gov/cms/dpc/api/auth/DPCAuthFilter.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java
dpc-api/src/main/resources/application.conf

Log use of APIs along with Organization Id and token Id.
- Added log statement in DPCAuthFilter to log the URI path and method of the resource requested.
- Added token id to MDC
- added DropWizard config: enableThreadNameFilter = false
The organization id was already being added to the MDC and would be added to all logs; however, there were many resources that where not logging anything. 
Decided to add the log statement to the auth filter instead of adding a log statement to all resources.
Since we also had the id of the token while in the Auth filter I went ahead and added that to the MDC too.
By default DropWizard was appending the URI (along with query parameters) to the thread name and printed with all logs, since there was a possibility of a query param containing sensitive …

DPC-519 Log Authenticated Requests With Org Id

---

dpc-api/src/main/resources/DPCCapabilities.json

the DPC Capabilities stmt needs to include Patient/$everything:
 
modified DPCCapabilities.json to include
"operation": [
{
"name": "patient-everything",
"definition":
{ "reference": "http://hl7.org/fhir/OperationDefinition/Patient-everything" }
}
no further details
No
None
No
No
No
No
- [ X] no PHI/PII is affected by this change
tested manually
Nothing in particular.

DPC-569 add /Patient/$everything to Capabilities stmt.

---

dpc-macaroons/src/main/java/gov/cms/dpc/macaroons/MacaroonBakery.java

…sent, it will throw a 400 error instead of 500
If a bad token is sent to the server, and base 64 decoding fails, the server returns 500 instead of 401, unauthorized.  FHIR expects 401 errors to be returned if authentication fails for any reason, especially a bad token
Add try catch around decoding statements, so if they fail, the error is handled the same as other errors in the function (http 401), instead of using default error handling that results in a 500.
no more details to provide
None
No
None
No
No
N/A
No
- [ X] no PHI/PII is affected by this change
Yes, with postman
standard, nothing special

DPC-552 - add try catch to ensure bad access token returns 401

---

dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractGroupResource.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java

The Prefer header must be set to respond-async on POST to /Group/$export
added checks to make sure the header is set to the correct value
n/a
n/a
n/a
n/a
- [ X] no PHI/PII is affected by this change
Yes, locally via Postman.
feedback on the @Valid annotation's correctnesss.

DPC 555 - The Prefer header must be set to respond-async on POST to /Group/$export

---

dpc-api/src/main/resources/DPCCapabilities.json

…peration per the FHIR bulk data standard
Capabilities Stmt is not in compliance with the bulk FHIR standard
changed export operation to group-export to comply with FHIR bulk standard.
Small change to DPCCapabilities.json
No
N/A
N/A
N/A
N/A
N/A
- [X ] no PHI/PII is affected by this change
Yes
N/A

DPC-559 - changed export operation to group-export to comply with FHIR bulk standard.

---

dpc-api/src/main/resources/DPCCapabilities.json

To declare conformance with this IG, a server should include the following URL in its own CapabilityStatement.instantiates:
http://hl7.org/fhir/uv/bulkdata/CapabilityStatement/bulk-data.
The CapabilityStatement should contain something like:
"instantiates": [
"http://hl7.org/fhir/uv/bulkdata/CapabilityStatement/bulk-data"
]
change "instantiates" to 
"instantiates": [
"http://hl7.org/fhir/uv/bulkdata/CapabilityStatement/bulk-data"
]
nothing further
N/A
No
None
None
None
N/A
N/A
- [ X] no PHI/PII is affected by this change
Yes
Nothing inparticular

DPC-566 fix errant uri for instantiates in Capabilities stmt

---

dpc-api/src/main/java/gov/cms/dpc/api/auth/AuthModule.java
dpc-api/src/main/java/gov/cms/dpc/api/auth/DPCAuthFactory.java
dpc-api/src/main/java/gov/cms/dpc/api/auth/DPCAuthFilter.java
dpc-api/src/main/java/gov/cms/dpc/api/auth/DPCUnauthorizedHandler.java
dpc-api/src/main/java/gov/cms/dpc/api/auth/filters/PathAuthorizationFilter.java
dpc-api/src/main/java/gov/cms/dpc/api/auth/filters/PrincipalInjectionAuthFilter.java
dpc-api/src/test/java/gov/cms/dpc/api/auth/AuthHandlerTest.java
dpc-api/src/test/java/gov/cms/dpc/api/auth/jwt/JWTUnitTests.java

If a server returns a 401, it should return JSON instead of a regular text string, ie:
```
{
"resourceType": "OperationOutcome",
"issue": [
{
"severity": "error",
"code": "exception",
"details": {
"coding": [
{                         "system": "http://hl7.org/fhir/ValueSet/operation-outcome",                         
"code": "Credentials are required to access this resource."                     }
]
}
}
]
}
```
with a content type of 
```
application/fhir+json 
```
instead of the current return:
```
Credentials are required to access this resource.
```
with a content type of 
```
text/plain
```
This required a new implementation of the DropWizard unauthorized Handler customized for DPC.
- Created new implementation class DPCUnauthorizedHandler, which implements Dropwizard …

DPC-561 - Responses with 401 Unauthorized should return JSON Operation Outcome

---

dpc-api/src/main/resources/DPCCapabilities.json

FHIR conformance issue.  FHIR Capabilities stmt lacks security definitions defining security scheme and token endpoint
added json that defines security scheme and token endpoints
No further details
None
No
n/a
n/a
n/a
n/a
n/a
- [X ] no PHI/PII is affected by this change
Yes
n/a

DPC-558 - Add Security scheme and token endpoint to Capabilities stmt.

---

dpc-test.sh

Failures of integration tests don't propagate to the host and fail the jenkins or ci job
adjust docker-compose command

DPC-578 propagate failure to host to end jenkins job

---

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceUnitTest.java

Revert "DPC-445 check provider in provenence header and group match"

---

dpc-aggregation/src/main/resources/application.conf
dpc-aggregation/src/main/resources/prod.application.conf
dpc-api/src/main/resources/prod.application.conf
dpc-attribution/src/main/resources/prod.application.conf

Debug logs not being printed in prod.
Change log level in prod for loggers: gov.cms.dpc 
- [X ] no PHI/PII is affected by this change
Missed any config?

Change prod debug level

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/dao/RosterDAO.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackServiceImpl.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/dao/RosterDAOTest.java
pom.xml

Add more logging to see the values in the fields look back is inspecting
More logs
More logs

DPC-389 adding more logs

---

dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/PatientDAO.java
dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/PatientResource.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PatientResourceTest.java
dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClientImpl.java
dpc-common/src/main/java/gov/cms/dpc/common/entities/PatientEntity.java
src/test/EndToEndRequestTest.postman_collection.json

No new data is stored. 
- No "bad" MBIs in DB.
- A script (attached to ticket) will need to be ran in order to convert previously stored MBIs to uppercase.
`UPDATE patients SET beneficiary_id=UPPER(beneficiary_id);`
- No way for "bad" MBIs to get in DB.
- Added UPPER function to MBI field.

DPC-640 Persist MBI as uppercase

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackServiceImpl.java
dpc-common/src/test/java/gov/cms/dpc/common/logging/DPCJsonLayoutTest.java

Need to convert list to string joined by semicolon to be properly parseable by the dpc json layout logging
Some logs of lookback was not being parsed into json because the providerNPIs is a list with commas in it.
Convert lists into String joined by semi-colon
Convert lists into String joined by semi-colon

DPC-674 Need to convert list to string joined by semicolon to be properly parseable by the dpc json layout logging

---

dpc-testing/performance/README.md
dpc-testing/performance/dpc-perf-load-test.sh
dpc-testing/performance/scripts/get_metadata-load.js
dpc-testing/performance/scripts/get_metadata-perf.js
dpc-testing/performance/scripts/modules/config.js

In order to measure our current performance, and prioritize and measure improvements, we need a performance and load test suite for our API.
Begin setting up a performance and load testing suite.
* Sets up a basic test suite using k6, including:
* Two JavaScript files for testing the `/metadata` endpoint: one for performance, one for load
* Shared `/modules/config.js` for configuring environment URL
* Shell script for running both JS tests via Docker
* `README.md` with instructions to run with or without Docker
This is a test suite and makes no changes to our application code.
See README for instructions for running the tests. Sample output below.
We can of course make adjustments as our test suite matures, but wondering about things like:
* Should the performance tests and load tests run …

DPC-613: Build a basic performance test suite for attribution

---

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java

Smoke tests weren't ran before merging in DPC-714, so this ticket is fixing the smoke test by having the test expect operation outcomes.  This will be further refined in the future when we use non mock blue button client and can skip look back.
remove the expectation that the job has no operation outcomes

DPC-714 fix smoke tests

---

docker/Dockerfiles/Dockerfile.base

Install curl so it's possible to call the dropwizard admin tasks from within the docker image for ansible

DPC-639 install curl on image

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackAnalyzer.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackService.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/BatchAggregationEngineTest.java
src/test/EndToEndRequestTest.postman_collection.json

Currently, we return an operation outcome when a patient fails look back, either because the patient had no EoBs or the patient's EoBs did not match the look back criteria.  Our current pilot partner would like more insight into why a patient's EoBs would not pass look back, therefore we are now adding which criteria the EoBs failed for look back into the operation outcome.
Determine reason for look back failure by looking at the set of EoB's for a particular patient
* Determine reason for look back failure

DPC-754 add lookback failure reason to operation outcome

---

package-lock.json
package.json

This PR replaces https://github.com/CMSgov/dpc-app/pull/1071
Snyk shows a possible vulnerability: Prototype Pollution due to `lodash@4.17.19`. The solution would be to upgrade to version `4.17.20`, but lodash is a dependency of a dependency as seen here: 
```Issues with no direct upgrade or patch:
✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-LODASH-590103] in lodash@4.17.19
introduced by newman@5.2.1 > postman-collection-transformer@3.3.3 > lodash@4.17.19
This issue was fixed in versions: 4.17.20
```
`newman@5.2.1` is already importing `lodash@4.17.20`, but `postman-collection-transformer@3.3.3` has not yet fixed this. In fact, they have [their own Snyk PR](https://github.com/postmanlabs/postman-collection-transformer/pull/320) addressing this that is yet to be …

DPC 766 fix: update newman and remove minimist in response to Snyk alert

---

dpc-web/app/assets/javascripts/application.js
dpc-web/app/assets/stylesheets/components/_field-groups.scss
dpc-web/app/assets/stylesheets/components/_pills.scss
dpc-web/app/controllers/internal/organizations_controller.rb
dpc-web/app/controllers/internal/users_controller.rb
dpc-web/app/models/concerns/taggable.rb
dpc-web/app/models/organization.rb
dpc-web/app/models/user.rb
dpc-web/app/services/base_search.rb
dpc-web/app/views/internal/organizations/_filter_modal.html.erb
dpc-web/app/views/internal/users/_filter_modal.html.erb
dpc-web/config/database.yml
dpc-web/spec/features/internal/organization_management/searching_and_filtering_organizations_spec.rb
dpc-web/spec/features/internal/user_management/searching_and_filtering_users_spec.rb
dpc-web/vendor/assets/javascripts/tag-selector.js

We have tagging available for both users and organizations, but we cannot currently filter views according to those tags. We will start using tags to designate users who reply to emails with "Do Not Contact" - we need a tool to be able to find those users quickly.
An admin user in the portal can filter views by tags.
- The User model is throwing an error with code climate for being one line too long
- Added UX design for tags in the filter modal (may want to consult designer for better design if number of tags becomes too many for a single view)

DPC-828: Update filtering to allow filtering by tag

---

dpc-test.sh

DB container was not being purged before postman e2e tests were being ran. A possible hiccup caused resources to not be deleted during a certain run and sequential e2e tests failed due to resources already existing.
run docker-compose explicitly before postman tests. There is a theory that integrations tests were affecting e2e tests.
run docker-compose explicitly after integration tests but before postman tests.

DPC-900: Bring down containers after app integration tests

---

dpc-testing/performance/pkg/dpc/test_key.go

Ticket claimed there were occasional key mismatches when parallelism was increased in performance tests.
During the investigation of this ticket I was able to uncover an issue with the access token expiring; however, I was not able to reproduce the issue reported in this ticket. Refactoring of the performance tests did happen after this ticket was created so that could have unknowingly fixed the key mismatch issue.
This PR covers fixing the access token expiration issue.
In the /key performance tests the keys to be used for testing are all generated at once; this can take more than than 5 minutes depending on the number of keys generated.
Fix: Generate the access token AFTER generating all of the key pairs.
Could not reproduce original issue.
Fixed access token issue.
Attempting to run …

DPC-737 Fixed key performance tests access key expiration issue

---

dpc-testing/performance/pkg/dpc/api.go
dpc-testing/performance/pkg/dpc/dpc.go
dpc-testing/performance/pkg/dpc/targeter/targeter.go

Investigated the patient tests, noticed that changing the duration and/or frequency would break the tests, reason was we have a set number of sample patients and it'll send in nil for the rest. Also, org can fail to create and it would be useful to see the message and failure at that point instead of later in the process (getting a token for the non created org)
* loop around the patients
* read the operation outcome of the org creation to determine if it should fail

DPC-774  investigate patient tests

---

.github/workflows/ci-workflow.yml

Run smoke test in Github Actions workflow.
Use `make smoke` to launch smoke tests
Unfortunately, you can only verify this with a PR so check the GH action below 
https://github.com/CMSgov/dpc-app/pull/1135/checks?check_run_id=1508340485
```
[INFO] Replacing /home/runner/work/dpc-app/dpc-app/dpc-smoketest/target/dpc-smoketest.jar with /home/runner/work/dpc-app/dpc-app/dpc-smoketest/target/dpc-smoketest-0.4.0-SNAPSHOT-shaded.jar
[INFO] Attaching shaded artifact.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for DPC Application 0.4.0-SNAPSHOT:
[INFO] 
[INFO] DPC Application .................................... SUCCESS [ 45.954 s]
[INFO] Common DPC testing code ............................ SUCCESS [ 22.426 s]
[INFO] DPC Common Libraries …
```

DPC-815 Feature: Add smoke test to Github Actions workflow

---

dpc-web/app/assets/stylesheets/components/_field-groups.scss
dpc-web/app/assets/stylesheets/components/_pills.scss
dpc-web/app/views/internal/organizations/_filter_modal.html.erb
dpc-web/app/views/pages/reference.md

- Update documentation (concerning Access Tokens)
- Fix tags in filter modal
- Noticed that the tags weren't wrapping around in the filer modal in the internal portal. Made the small change to make it responsive.
Before:
After:
**Small suggestion:** get rid of the filter modals and embed the search parameters in the dashboard. The filter modals are big and clunky and will be annoying if a large number of tags are added. [Created a ticket just in case.](https://jira.cms.gov/browse/DPC-940)

DPC-915: Website Updates

---

dpc-api/src/main/java/gov/cms/dpc/api/APIHelpers.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PractitionerResource.java
dpc-api/src/test/java/gov/cms/dpc/api/APITestHelpers.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PatientResourceTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PractitionerResourceTest.java
dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/GroupResource.java
dpc-testing/src/main/java/gov/cms/dpc/testing/factories/FHIRPractitionerBuilder.java
dpc-testing/src/test/java/gov/cms/dpc/testing/factories/FHIRGroupBuilderUnitTest.java
dpc-testing/src/test/java/gov/cms/dpc/testing/factories/FHIRPatientBuilderUnitTest.java
dpc-testing/src/test/java/gov/cms/dpc/testing/factories/FHIRPractitionerBuilderUnitTest.java

During the audit/risk assessment of DPC API it was discovered that for certain resources are not validating values passed in by the client.
Practitioner: 
Specifying an org id in the meta tag allows an authenticated clients to register a practitioners under any org.
Group:
Specifying an org ID in the met tag and NPI allows the retrieval of another org's roster during creation.
Cause:
- Organization tag is added using the authenticated principal in API.
- Attribution retrieves the value of the FIRST tag with DPC System code. 
- A client is capable of adding their own tag with DPC SYSTEM code and specifying another org's id for the value.
- API would append the authenticated org's id to the tag, but it wold no longer be the first in the list so it would be ignored by attribution and use the …

DPC-979 Fix Group & Practitioner resource request body forgery issue.

---

dpc-api/src/main/java/gov/cms/dpc/api/tasks/tokens/GenerateClientTokens.java
dpc-api/src/test/java/gov/cms/dpc/api/tasks/ClientTokenTests.java

While the API endpoint accepts token label and expiration query params when creating tokens, the admin task was not passing them along to API when provided.
When query params are provided for a token label and/or expiration, pass these on to the call to the API. Otherwise, ignore.
- Update tests to check that the label and expiration get passed to the API call
- Check the parameters for label and expiration, and if found, pass along with the call to API; otherwise default to null / empty Optional respectively
No change in security; simply making admin task do what API already does.
Any

DPC-865 fix: Pass label and expiration to API from admin task

---

.github/workflows/ci-workflow.yml
dpc-web/Dockerfile

Currently, we are performing Snyk analysis after a branch gets merged to master (triggered by Jenkins). This is great, but it means that a build could fail if a vulnerability was introduced in a feature branch (it isn't detectable by Snyk until the code makes it to master).
We should add a Snyk analysis into our feature branch CI via a Github Action.
https://github.com/snyk/actions
- Add `snyk/actions` to Github Actions
- Fail on high severity failures
- Add SNYK_API_TOKEN to Github Repo Secrets and KeyBase
Can only test Workflow change via a PR...
- https://github.com/CMSgov/dpc-app/actions/runs/432800008
Will block success of action run.
- Match this: https://app.snyk.io/org/oeda/reports/

DPC 971 Feature: Add Snyk scans for Github Actions

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/ResourceFetcher.java
dpc-aggregation/src/main/resources/migrations/queue.migrations.xml
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/AggregationEngineBFDClientTest.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/AggregationEngineTest.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/BatchAggregationEngineTest.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/health/AggregationEngineHealthCheckTest.java
dpc-api/src/main/java/gov/cms/dpc/api/APIHelpers.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java
dpc-api/src/test/java/gov/cms/dpc/api/FHIRSubmissionTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/DataResourceTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceUnitTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/JobResourceTest.java
dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClient.java
dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClientImpl.java
dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/MockBlueButtonClient.java
dpc-bluebutton/src/test/java/gov/cms/dpc/bluebutton/client/BlueButtonClientTest.java
dpc-common/src/main/java/gov/cms/dpc/common/Constants.java
dpc-common/src/main/java/gov/cms/dpc/common/MDCConstants.java
dpc-queue/src/main/java/gov/cms/dpc/queue/IJobQueue.java
dpc-queue/src/main/java/gov/cms/dpc/queue/JobQueueCommon.java
dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobQueueBatch.java
dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java
dpc-queue/src/test/java/gov/cms/dpc/queue/DistributedBatchQueueTest.java
dpc-queue/src/test/java/gov/cms/dpc/queue/QueueTest.java
dpc-queue/src/test/java/gov/cms/dpc/queue/models/JobQueueBatchTest.java

Need to send different headers depending on being bulk or non bulk requests to BFD.
* add new boolean column to indicate if it's a bulk job or not
* refactor passing down BFD headers (don't use MDC anymore, just pass a Map of headers down to the bb client)
* use the newly added boolean column to determine which headers to pass down
Create a new `is_bulk` column for `JobQueueBatch` that allows `JobBatchProcessor` to be able to determine which BFD headers to pass down to the `BlueButtonClientImpl`

DPC-948 ability to differentiate BFD headers when requesting patient everything vs bulk data

---

dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractGroupResource.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractPatientResource.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractTokenResource.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java

The presenting "problem" in this ticket was a recognition of the fact that there are several annotations on the concrete resource class methods, making the code difficult to quickly parse at times. The suggestion was to move swagger-related annotations to the abstract classes to improve readability.
- Remove duplicate annotations (between abstract and concrete classes) where possible
- auto-format the resource classes to clean up the code a bit and improve readability
- fix a couple pre-existing errors that had popped up in the swagger documentation since the last time we audited it
Initially, I moved swagger annotations to the abstract class for the GroupResource. This resulted in duplicate params and other errors in the swagger documentation due to inheritance from the abstract classes. …

DPC-975: Clean up annotations in abstract and concrete resource classes

---

dpc-web/app/views/devise/mailer/reset_password_instructions.html.erb
dpc-web/app/views/layouts/mailer.html.erb
dpc-web/app/views/pages/faq.html.erb
dpc-web/app/views/public/_hero.html.erb
dpc-web/app/views/shared/_footer.html.erb

In the ITOPS Sonar instance we're now having JS and CSS scanned in our web app. Sonar is wanting us to tweak our links.
Admittedly, we're never linking anywhere nefarious. But it does seem like a good practice!
Add `rel="noopener noreferrer"` to all links identified by Sonarqube

DPC-1050: Add rel="noopener noreferrer" to links

---

dpc-web/config/initializers/devise.rb
dpc-web/spec/features/confirmation/user_confirmation_email_spec.rb

In our pre-ACT penetration test, the testers were able to tell whether a given email address was registered in the web app by trying to reset a password.
We should be able to overcome this data leakage by setting the Devise configuration to use paranoid mode.
- [Use paranoid mode](https://github.com/heartcombo/devise/wiki/How-To:-Using-paranoid-mode,-avoid-user-enumeration-on-registerable)
- Create an automated test to prove that account enumeration is not happening in the future
- Retest all account capabilities, especially those sending emails. Make sure 1) everything still works and 2) there's no difference between reseting a password for an account that exists and one that doesn't exist
Turned on `config.paranoid = true` so that it gives a vague notice to the user that if the email …

DPC-1069: Do not enumerate account info on password reset

---

dpc-web/app/views/pages/reference.md

- Update the user guide language with approved edits: https://docs.google.com/document/d/1g7nhqhXjkI7osew6tgkTxuIeLM58L1p_gupTlOImOnk/edit?ts=60005403#
- Update language
- Fix broken link for Attestation for X-Provenance header
**Before**
**After**

DPC-1085: Update language in webapp

---

dpc-api/src/main/java/gov/cms/dpc/api/tasks/tokens/GenerateClientTokens.java
dpc-api/src/test/java/gov/cms/dpc/api/tasks/GenerateClientTokenTests.java

There is a small bug in GenerateClientTokens task where an empty expiration time is not being handled correctly. Passing in the expiration with in empty value results in a 400. Task should use the default expiration time when a blank value is passed but it tries to parse it.
Ensure the GenerateClientToken task in API is handling empty values for expiration correctly.
The GenerateClientToken task was checking for the expiration parameter and using the default value if it was missing; however, the admin task was sending the expiration parameter, but with a blank value.
Added an extra check for the expiration value.
I attempted to create a client token with an empty expiration before the fix (Generate Client Token Build #52) and that resulted in an error (notice the size of s3 file)
After …

DPC-1112 Allow default expiration time for Client token creation

---

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java

During a the recent refactoring of the api smoke tests the wrong url was used for handling export jobs. The admin url was being used instead of the host url, causing the smoke tests to fail when running them against prod.
Use the correct url for testing export.
Reverted to using APIHost instead of APIAdminUrl during group export.
Does not deal with PII/PHI
Ran smoke tests against dev and prod. The screenshot below is from a prod run.

DPC-1134 Fixed smoke test bug where the wrong export url was being used

---

dpc-common/src/test/java/gov/cms/dpc/common/logging/DPCJsonLayoutUnitTest.java

DPCJsonLayout tests were not running and Sonar was complaining about code coverage.
The tests were not using JUnit 5. Used JUnit 5
Docker Build #1452

Used Junit 5 for DPCJsonLayoutTest

---

dpc-web/app/views/pages/reference.md

Users were being directed to the wrong URL to request access or update their profile after the static site separation effort.
* Updated the guide with the new URLs
Updated URLs are added to the guide. Other redirect changes occurring in the `ops` repo

DPC-1178 fix routing issue with user resource

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/OutcomeReason.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackAnalyzer.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/util/AggregationUtils.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/BatchAggregationEngineTest.java
dpc-common/src/main/java/gov/cms/dpc/common/MDCConstants.java

To better understand the limitations of claims look back, we want to know why patients are failing at a more granular level. 
We want to introduce new dashboard panels in the pilot dashboard, but we first need to log the operation outcomes so that we may run queries against the results.
The lookback analyzer determines why lookback failed, we should log the reason so that we may build splunk queries.
- Re-ordered the failure reasons in the analyzer.
- Added MDC flag to determine if logs are for a smoke test org.
- Added a breakdown to DPC Stats dashboard

DPC-1164 metric break down for look back failures

---

dpc-admin/app/assets/javascripts/components/_modals.js
dpc-admin/app/assets/stylesheets/application.scss
dpc-admin/app/assets/stylesheets/base/1_base.scss
dpc-admin/app/assets/stylesheets/components/_fields.scss
dpc-admin/app/assets/stylesheets/components/_pills.scss
dpc-admin/app/controllers/taggings_controller.rb
dpc-admin/app/controllers/tags_controller.rb
dpc-admin/app/helpers/tags_helper.rb
dpc-admin/app/views/shared/_sidenav.html.erb
dpc-admin/app/views/tags/index.html.erb
dpc-admin/app/views/users/index.html.erb

This ticket is intended to accomplish the part of the coding involved with 1 which affects the tags dashboard. Out of scope: tags dashboard tests.
- Internal users can create, read, and delete tags
- Internal users can tag users and organizations
- Internal users can filter users and orgs by tags
- Add tagSelector javascript function in modals javascript file
- Add styling for tags
- Add tags controller
- Update sidenav to see all providers or all vendors

DPC-1077: Admin site separation: add tags dashboard

---

.gitignore
dpc-go/dpc-api/Makefile
dpc-go/dpc-api/unit_test.sh

We've been carefully adding unit tests to our Golang code, but currently do not have a simple, memorable way to run them all at once.  To improve local development, and to support further devops work, we need a make test target for the v2 API service.
- Make a unit_test.sh that runs all unit tests for the v2 API service
- Create a Makefile target for make unit-test that runs unit_test.sh after any test setup, if needed
- Create a Makefile target for make lint that runs golangci-lint and gosec
- Create a Makefile target for make test that invokes make unit-test and make lint
created a `unit_test.sh` script to run unit tests and output results.
created a `unit-test` make target that runs unit tests
created a `lint` make target that runs liners and security scans
created a `test` make target …

DPC-1229 Add target for running dpc-go-api unit tests and linters

---

dpc-admin/app/helpers/nav_helper.rb
dpc-admin/app/models/registered_organization.rb
dpc-admin/app/services/api_client.rb
dpc-admin/app/views/layouts/mailer.html.erb
dpc-admin/app/views/organizations/_filter_modal.html.erb
dpc-admin/app/views/user_mailer/provider_sandbox_email.html.erb
dpc-admin/app/views/user_mailer/vendor_sandbox_email.html.erb
dpc-admin/config/locales/kaminari.en.yml
dpc-admin/public/404.html
dpc-admin/public/422.html
dpc-admin/public/500.html

Fix the same bugs that showed in [Sonarqube for the web app](https://github.com/CMSgov/dpc-app/pull/1247) with [DPC-1059](https://jira.cms.gov/browse/DPC-1247) that are present in the admin app.
- Assigned constants to strings in `nav_helper` and `api_client`
- Simplified css in mailer, deleted deprecated attributes, and added default general font (sans-serif)
- add language to html tags where missing
- Removed unnecessary `#TODO` items
- Will be addressed in v2 of the app
- For the mailer (outside of the css), sonarqube wants every table to have a <th> header tag and a description, but since most of the tables are containers (due to the nature of email styling), there is no need for either.
- Sonarqube also throws up an error for mso- attributes but these are required for microsoft …

DPC-1247: Sonarqube bugs with admin-app

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackServiceImpl.java

Remove excessive aggregation engine logs
During the “disk space full” incident on 4/10/2021 it was discovered that aggregation was extremely chatty and filling up disk space quickly.
aggregation service logs 1 event per EoB per patient per job. On the day of the incident one of our production organizations had triggered many group exports simultaneously, causing our logs the grow past the available disk space.
We are re-evaluating our log rotation; however, we are also removing the unnecessary aggregation log. (We no longer need the EoB analysis results, it is being handled elsewhere)
- Changed the log level of the EoB analysis log to TRACE, this will prohibit the log from being printed in our prod and sbx environments.
Any other logs we should remove or disable?

Hotfix Remove Unnecessary log in DPC-Aggregation

---

dpc-go/dpc-api/src/middleware/fhir_filter_test.go
dpc-go/dpc-api/src/middleware/fhir_test.go
dpc-go/dpc-api/src/model/fhir.go

Need to filter everything out except for name and identifiers for organization
* update the org filter

DPC-1318 filter out everything except identifiers and name for org

---

.github/workflows/ci-workflow.yml

DPC-1173 unpin ubuntu for GHA

---

dpc-admin/Gemfile
dpc-admin/Gemfile.lock
dpc-admin/config/newrelic.yml

This branch adds the new relic agent to the dpc-admin app.
* Adding newrelic gem
The environment variables have the new relic app name and license key so they don't need to be included in the `newrelic.yml` file.
All feedback is welcome.

DPC-1205: Adding New Relic Agent to dpc-admin

---

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceUnitTest.java

* Check if the group retrieved contains any patient and if not, throw an error
* `fetchPatientMBIs` already only grabs active patients, so the only the change will be to see if the list of active patients is empty or not.  If it's empty, will return a WebApplicationException that gets converted to an OperationOutcome in our FHIR exception handlers.

DPC-1337 return operation outcome when no active patients

---

dpc-impl/.gitignore
dpc-impl/app/views/shared/_google-analytics.html.erb
dpc-impl/app/views/shared/_head.html.erb

Right now, the Google Analytics account is only tracking user interactions with the DPC Implementation Guide. We should be tracking all pages of the static site and webportal.
- Add google analytics to the impl app
- Paired with [PR for the static site](https://github.com/CMSgov/dpc-static-site/pull/40)
- added `.env.development.local` and `.env.test.local` to `.gitignore`
Google Analytics is tracking user activity for entire web experience.

DPC-1397: Update webapp to work with Google Analytics

---

dpc-impl/Gemfile
dpc-impl/Gemfile.lock
dpc-impl/config/environments/production.rb
dpc-impl/config/initializers/lograge.rb

This branch adds lograge as a dependency to dpc-impl so that logs are properly formatted as json in prod for ingestion in splunk.
* Adding `lograge` gem
This is consistent with how `dpc-web` and `dpc-admin` output their logs.
All feedback is welcome.

DPC-1336: Enable log ingestion in splunk

---

dpc-go/dpc-attribution/src/model/v1/batch.go
dpc-go/dpc-attribution/src/repository/job_repository_v1_test.go
dpc-go/dpc-attribution/src/service/v1/data.go
dpc-go/dpc-attribution/src/service/v1/job.go

No ticket here, just fixing some linting and gosec stuff caught by make test

fix go lint and go sec stuff

---

dpc-impl/app/assets/stylesheets/components/_dashboard.scss
dpc-impl/app/models/user.rb
dpc-impl/app/services/api_client.rb
dpc-impl/app/views/portal/show.html.erb
dpc-impl/spec/features/auth/user_password_expire_spec.rb
dpc-impl/spec/features/auth/user_resets_password_spec.rb
dpc-impl/spec/features/auth/user_sign_in_spec.rb
dpc-impl/spec/features/confirmation/user_confirmation_email_spec.rb
dpc-impl/spec/features/invitation/user_sends_invitation_spec.rb
dpc-impl/spec/features/registration/new_user_signs_up_for_account_spec.rb
dpc-impl/spec/features/registration/user_edits_profile_spec.rb
dpc-impl/spec/services/api_client_spec.rb

For consistency change all mentions of client_org to provider_org in impl portal.
- Change all `client_org` to `provider_org` in methods, class names, and content.
- Made sure nothing broke via tests and user testing.

DPC-1476: Change client_org to provider_org in rails portal

---

dpc-admin/Gemfile.lock
dpc-adminv2/Gemfile.lock
dpc-web/Gemfile.lock

```
ruby-advisory-db:
advisories:	511 advisories
last updated:	2021-07-12 11:39:42 -0700
Name: addressable
Version: 2.7.0
CVE: CVE-2021-32740
GHSA: GHSA-jxhc-q857-3j6g
Criticality: High
URL: https://github.com/advisories/GHSA-jxhc-q857-3j6g
Title: Regular Expression Denial of Service in Addressable templates
Solution: upgrade to >= 2.8.0
```
Run `bundle update addressable` in `dpc-admin` and `dpc-web`
`dpc-impl` and `dpc-adminv2` do not need to be updated as the `addressable` gem was already versioned at `2.8.0`.
**Updated in `dpc-web`**
**Updated in `dpc-admin`**

DPC-1594: Fix addressable gem depreciation

---

Makefile
dpc-go/dpc-api/src/client/ssas_client.go
dpc-go/dpc-api/src/main.go
dpc-go/dpc-api/src/router/router.go
dpc-go/dpc-api/src/router/router_test.go
dpc-go/dpc-api/src/v2/controller.go
dpc-go/dpc-api/src/v2/implementer_org_test.go
dpc-go/dpc-api/src/v2/implementer_test.go
dpc-go/dpc-api/src/v2/organization_test.go
dpc-go/dpc-api/src/v2/ssas_controller.go
dpc-go/dpc-api/src/v2/ssas_controller_test.go

Need to return system information for the portal to be able to use, IPs, client tokens and public keys info is returned
* create endpoint to get system from ssas
Does all the same checks as when registering a system for impl/org relationship except this method expects a relationship so asserts that system id is not null and then proxies to ssas

DPC-1305 get the system from ssas

---

Makefile
dpc-go/dpc-api/docker-compose.yml
dpc-go/dpc-api/src/client/attribution_client.go
dpc-go/dpc-api/src/client/ssas_client.go
dpc-go/dpc-api/src/main.go
dpc-go/dpc-api/src/v2/ssas_controller.go
dpc-go/postman/functional-tests/DPC_V2_Functional_Tests.postman_collection.json
dpc-go/postman/functional-tests/DPC_V2_Functional_Tests_Local.postman_environment.json
make_ssas_creds.sh

During local manual testing a few bugs were discovered, to help developers test dpc integrations this functional test suite was created. 
- Added postman test suite
- Add make target "make ssas-creds" to reset ssas admin credentials
- attribution url fixes

DPC-1621 Added initial functional test suite + Make ssas-creds command

---

dpc-go/dpc-api/src/v2/implementer_org.go
dpc-go/dpc-attribution/src/model/v2/implementer_org_relation.go
dpc-go/dpc-attribution/src/service/v2/implementer_org.go

org id and npi were not being returned when creating the org under and implementer
* fix the structs

DPC-1622 return org id and npi

---

dpc-go/dpc-api/src/v2/implementer_org_test.go
dpc-go/dpc-api/src/v2/implementer_test.go
dpc-go/dpc-attribution/src/model/v2/implementer_org_relation.go
dpc-go/dpc-attribution/src/service/v2/implementer_org_test.go

When creating a system in api, the conversion of the enum in the attribution layer was not correct.  Correcting the issue
* add MarshalJson back to original struct too

DPC-1624 fix enum conversion

---

dpc-go/dpc-api/src/v2/ssas_controller.go
dpc-go/dpc-api/src/v2/ssas_controller_test.go

…key and create system
Currently, create system and adding a public key does not enforce the presence of a signature for the public key. This PR enforces that presence.
* add signature field to create system request
* check signature in both createSystem and addPublicKey and return fhir error (operation outcome) when the signature is not present.

DPC-1627 add signature check

---

dpc-go/dpc-api/src/client/ssas_client.go
dpc-go/dpc-api/src/model/batch.go
dpc-go/dpc-api/src/service/public/router_test.go
dpc-go/dpc-api/src/v2/data.go
dpc-go/dpc-api/src/v2/data_test.go
dpc-go/dpc-api/src/v2/job_test.go
dpc-go/dpc-api/src/v2/ssas_controller.go
dpc-go/dpc-api/src/v2/ssas_controller_test.go

Looks like a bad merge happened as some files weren't updated with new method names and other where the mock methods were removed so correcting that.  Job status url for the file needs to have the lower case resource type in the url instead of the capitalized resource type.  Getting the file needs to strip out the .ndjson extension when checking if the file exists in the database

DPC-1637 various fixes

---

dpc-go/dpc-api/src/middleware/constants.go
dpc-go/dpc-api/src/middleware/context.go
dpc-go/dpc-api/src/middleware/context_test.go
dpc-go/dpc-api/src/middleware/fhir_filter.go
dpc-go/dpc-api/src/model/fhir.go
dpc-go/dpc-api/src/service/public/router.go

Added a middleware that validates the provenance header against the ticket description.  If  it passes all validations, then it logs the provenance header and adds the provenance header to the context for later usage.
* create middleware

DPC-1613 require and validate provenance header for posting a group

---

dpc-go/dpc-api/src/middleware/context.go
dpc-go/dpc-attribution/migrator/migrations/6_pluralize_table_names.down.sql
dpc-go/dpc-attribution/migrator/migrations/6_pluralize_table_names.up.sql
dpc-go/dpc-attribution/src/repository/group_repository.go
dpc-go/dpc-attribution/src/repository/group_repository_test.go
dpc-go/dpc-attribution/src/repository/organization_repository.go
dpc-go/dpc-attribution/src/repository/organization_repository_test.go

Tables need to be plural
* Created migration scripts
* Updated tests
* Removed some ctx fns that aren't being used

DPC-1434database tables plural

---

dpc-go/dpc-attribution/src/client/bfd_client.go
dpc-go/dpc-attribution/src/client/bfd_client_test.go
dpc-go/dpc-attribution/src/go.mod
dpc-go/dpc-attribution/src/go.sum

BFD certs need to be passed into attribution as env vars (base64 encoded)
Accept certs and keys as Base 64 encoded values
Introduced env vars for attribution:
DPC_BFD_CA
DPC_BFD_CLIENTCERT
DPC_BFD_CLIENTKEY
Attribution will continue to accept paths to local cert files and will default to the old method if the new base64 variables are not provided. (used for local testing)
Tested locally.

DPC-1655: Accept BFD certs as base 64 encoded env vars

---

dpc-impl/app/controllers/client_tokens_controller.rb

The implementer portal threw a "wrong number of arguments given" error when attempting to add a new client token. The correct number of arguments now get passed to the `render_error` function.
The underlying issue (unable to create a new client token) turned out to be a local config issue (the local DB was running on a different port than expected) and not a bug after all.
Update the implementer portal to display errors properly
Updated the call to the `render_error` function (in `client_tokens_controller.rb`) to include the org ID as required.
Yes, new client tokens can be successfully added and deleted as expected.

DPC-1659 Bugfix: Error when creating new client tokens

---

dpc-impl/app/views/devise/invitations/edit.html.erb
dpc-impl/app/views/devise/registrations/new.html.erb
dpc-impl/app/views/provider_orgs/new.html.erb

Make the requested text updates to the Implementer Portal.
* Improve spacing between "the" and "Terms"
* Add requested text to "Add Provider Organization" page
This PR adds text to one component and makes a slight change to text in another. No functionality changes were made, making it unlikely that there are security implications to consider with this PR.
Yes.

DPC-1661: Implementer Portal language updates

---

dpc-impl/app/assets/javascripts/character-count.js
dpc-impl/app/views/client_tokens/new.html.erb

We enforce a limit of 25 characters for client token labels but don't let the user know. This PR adds a counter to signify that client token labels can be no longer than 25 characters.
* Use JS function to add a character limit count, similar to how its done in `dpc-web`.
As a user enters the new label for a client token, the counter counts up to 25 characters, conveying to the user a character count limit of 25.
This PR adds a front-end JavaScript character counter to ensure users understand that new client tokens in the implementer portal can have a maximum of 25 characters.
Yes, the new character counter works as expected.

DPC-1639: Feature Add counter to convey label length limit to user

---

dpc-admin/package-lock.json
dpc-admin/package.json

Snyk has identified two arbitrary file overwrite vulnerabilities ([1](https://snyk.io/vuln/SNYK-JS-TAR-1536528) & [2](https://snyk.io/vuln/SNYK-JS-TAR-1536531)) in the version of tar used in the admin portal's package.json file.
https://app.snyk.io/org/oeda/project/a2679c93-4776-42dd-83bc-8625acf868ef#issue-SNYK-JS-TAR-1536531
https://app.snyk.io/org/oeda/project/a2679c93-4776-42dd-83bc-8625acf868ef#issue-SNYK-JS-TAR-1536528
- To override `tar` in `package-lock.json` file, add `"tar": "6.1.11",` to `package.json` to meet snyk requirements.
- In addition to updating `tar`, upgrade `webpacker` to `5.4.2`.
Not necessarily new, but upgrading existing software dependencies to meet security requirements as noted by Snyk (links above)
**Before**
**After upgrading webpacker to `5.4.2`**
**After …

DPC-1745: Upgrade tar

---

dpc-common/pom.xml

Snyk alerted us to the need to upgrade hibernate-core to version 5.4.24 or higher. All modules are on 5.5.6 except for dpc-common.
- upgrade hibernate-core in dpc-common to version 5.5.6
-- Note: we are already using version 5.5.6 of hibernate-core in the project. This is an upgrade online in dpc-commons to bring it up to the same version as the others
-- This is only an upgrade to a dependency in dpc-commons and will not affect PII or PHI
- make ci-app successfully builds and all tests pass
- snyk no longer lists hibernate-core as a vulnerability
- all smoke tests pass locally
Any

DPC-1744: Upgrade hibernate-core in dpc-commons to 5.5.6

---

dpc-bluebutton/pom.xml

snyk complaining so updating version to something snyk won't complain about
* update json-smart
https://confluence.cms.gov/display/DAPC/2021-09-21%3A+DPC+4.3+Security+Checklist
`
Issues to fix by upgrading:
Upgrade net.minidev:json-smart@2.4.1 to net.minidev:json-smart@2.4.5 to fix
✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-JAVA-NETMINIDEV-1298655] in net.minidev:json-smart@2.4.1
introduced by net.minidev:json-smart@2.4.1
`

DPC-1773 update json smart

---

dpc-go/dpc-api/src/auth/ssas.go
dpc-go/dpc-api/src/go.mod
dpc-go/dpc-api/src/go.sum
dpc-go/dpc-api/src/service/public/router_test.go

jwt-go maintainer has been deprecated and maintained by new group.  Migrating to new group for the jwt-go library
* update go.mod to new location
Should be no security implications as the version is being updated to use the new maintainer.
using new maintainer, should be backwards compatible

DPC-1784 migrate to new maintainer for jwt-go

---

.gitignore
README.md

Experience during recent onboarding highlighted some gaps in our documentation. This PR adds a few details to the project README.
- Mention required tools and languages
- Document the need for a copy of .vault_password for the Go-based dpc-attribution service
- Add to .gitignore (regarding test results)
No functionality is changed, and no secrets revealed. This level of change should not require a security checklist.
- Can anyone think of additional requirements we should add to the list?

DPC-1721: Add Documentation details

---

pom.xml

Log4j has an exploit, we don't use log4j for logging but that doesn't mean we don't have dependencies that bring in log4j. We can upgrade those dependencies just for the sake of updating them.
update log4j to 2.15.0

we don't use log4j, but we can update the dependencies to a non vulnerable version

---

dpc-attribution/src/main/resources/application.conf

Due to an increase of usage in PROD we need to reduce the number of logs. To do so we need to change the very chatty log level of hibernate.sql from TRACE to INFO
Set SQL log level to INFO
"org.hibernate.SQL" : TRACE -> "org.hibernate.SQL" : INFO
As a result of this we will be dropping sanitized SQL log queries.
Tested in DEV

changed org.hibernate.SQL log level to INFO

---

dpc-admin/Gemfile.lock
dpc-adminv2/Gemfile.lock
dpc-impl/Gemfile.lock
dpc-web/Gemfile.lock

* Bundle update the Rack gem according to guidance from https://groups.google.com/g/ruby-security-ann/c/LWB10kWzag8

Bump Rack Gem

---

Makefile

* Update the smoke testing command in the DPC makefile

Update Smoke tests command

---

dpc-web/package-lock.json

* Run 'npm audit fix' to fix vulnerabilities found in npm audit

Fix vulnerabilities found in npm audit

---

docker-compose.portals.yml

* Remove the DB definition from the docker-compose.portals.yml as it creates a port conflict

Fix docker-compose.portals.yml

---

dpc-smoketest/pom.xml
src/test/smoke_test.yml

* Updated jmeter to 5.5 to resolved log4j issues.

updated jmeter to version 5.5 to resolve log4j issue

---

docker/Dockerfiles/Dockerfile.ssas

* Update golang version for the BCDA SASS Docker image from 1.13 to 1.18 based on guidance from: https://github.com/golang/go/issues/55078

Update golang version for SASS Docker image

---

dpc-admin/Gemfile.lock
dpc-adminv2/Gemfile.lock
dpc-impl/Gemfile.lock
dpc-web/Gemfile.lock

* Bundle update nokogiri based on guidance from https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2qc6-mcvw-92cw

Bundle update Nokogiri gem

---

dpc-impl/README.md

* Add a readme for the dpc-impl service with instructions for running the app locally

Add basic readme for dpc-impl

---

dpc-admin/Gemfile
dpc-admin/Gemfile.lock
dpc-adminv2/Gemfile
dpc-adminv2/Gemfile.lock
dpc-impl/Gemfile
dpc-impl/Gemfile.lock
dpc-web/Gemfile
dpc-web/Gemfile.lock

* Update nokogiri gem to non-vulnerable version

Update Nokogiri to latest version without vulnerabilities

---

dpc-web/Dockerfile

* Update the dpc-web Dockerfile to install a specific version of Jekyll

Install a specific Jykll version for dpc-web

---

requirements.txt

Replicates #1813 
The following vulnerabilities are fixed by pinning transitive dependencies:
- https://snyk.io/vuln/SNYK-PYTHON-NUMPY-2321964
- https://snyk.io/vuln/SNYK-PYTHON-NUMPY-2321966
- https://snyk.io/vuln/SNYK-PYTHON-NUMPY-2321970

[DPC-3312] Security upgrade numpy from 1.21.3 to 1.22.2 

---

scripts/generate_credentials.rb

https://jira.cms.gov/browse/DPC-3534
Filled in code for generate_token()

dpc-3534 Fill in code for generate_token()

---

dpc-common/src/main/java/gov/cms/dpc/common/consent/entities/ConsentEntity.java
dpc-consent/src/main/resources/consent.migrations.xml

Dpc 3599/aweaver fork

---

dpc-web/app/views/layouts/application.html.erb
dpc-web/app/views/layouts/devise.html.erb
dpc-web/app/views/layouts/landing-page.html.erb
dpc-web/app/views/layouts/public-key-new.erb
dpc-web/app/views/layouts/table_index.html.erb
dpc-web/app/views/shared/_head.html.erb
dpc-web/app/views/shared/_tealium.html.erb

https://jira.cms.gov/browse/DPC-3582

Set up Tealium for sandbox.dpc.cms.gov

---

.codeclimate.yml
pom.xml

https://jira.cms.gov/browse/DPC-3672

[DPC-3672] Ignore MockBlueButtonClients in code coverage

---

dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/handlers/exceptions/DataFormatExceptionHandlerTest.java
dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/handlers/exceptions/DefaultFHIRExceptionHandlerTest.java
dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/handlers/exceptions/HAPIExceptionHandlerTest.java
dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/handlers/exceptions/JerseyExceptionHandlerTest.java
dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/handlers/exceptions/PersistenceExceptionHandlerTest.java

https://jira.cms.gov/browse/DPC-3673
Added tests for exception handlers in dpc-common.
Coverage increased to 89% for exceptions directory.

[DPC-3673] Add tests for exception handlers

---

dpc-api/pom.xml
dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractAdminResource.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractBaseResource.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/AdminResource.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/BaseResource.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/AdminResourceTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/AdminResourceUnitTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/BaseResourceUnitTest.java

https://jira.cms.gov/browse/DPC-3689
- Added adminResource, unit test and integration test

DPC-3689: Add new endpoint for retrieving multiple organizations

---

dpc-api/src/main/java/gov/cms/dpc/api/cli/organizations/OrganizationDelete.java
dpc-api/src/main/java/gov/cms/dpc/api/cli/organizations/OrganizationList.java
dpc-api/src/test/java/gov/cms/dpc/api/cli/OrganizationTests.java

https://jira.cms.gov/browse/DPC-3677
Adds tests to cover dpc-api/cli/organizations.

[DPC-3677] Add tests for organization CLI commands

---

docker-compose.yml
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/AggregationServiceTest.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/AbstractAttributionTest.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionFHIRTest.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/cli/SeedCommandTest.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/jobs/ExpirationJobTest.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PractitionerResourceTest.java
dpc-consent/src/test/java/gov/cms/dpc/consent/AbstractConsentTest.java
dpc-consent/src/test/java/gov/cms/dpc/consent/cli/ConsentCommandsTest.java
dpc-consent/src/test/java/gov/cms/dpc/consent/resources/ConsentResourceTest.java
pom.xml

https://jira.cms.gov/browse/DPC-3675
Add tests to cover dpc-attribution/cli.

[DPC-3675] Add tests for CLI seeding utilities

---

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/AdminResource.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/AdminResourceTest.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/AdminResourceUnitTest.java
dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/OrganizationDAO.java
dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/OrganizationResource.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/OrganizationResourceTest.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/v1/OrganizationResourceUnitTest.java

https://jira.cms.gov/browse/DPC-3734

DPC-3734: Add multiple org search to attribution service

---

docker-compose.portals.yml
dpc-portal/.rubocop.yml
dpc-portal/app/components/core/card/basic_component.html.erb
dpc-portal/app/components/core/card/basic_component_preview.rb
dpc-portal/app/components/core/table/table_component_preview.rb
dpc-portal/app/controllers/organizations_controller.rb
dpc-portal/app/models/organization.rb
dpc-portal/app/services/cpi_api_gateway_client.rb
dpc-portal/spec/components/core/card/basic_component_spec.rb
dpc-portal/spec/models/organization_spec.rb
dpc-portal/spec/support/dpc_client_support.rb

https://jira.cms.gov/browse/DPC-3691
- Minor style tweaks to components
- Raise 404 on no organization found
Responding to ignored comments from Kevin

DPC-3691 additional fixes

---

dpc-portal/Gemfile
dpc-portal/Gemfile.lock

Update view_component to 3.9

---

dpc-api/src/test/java/gov/cms/dpc/api/cli/tokens/TokenCommandUnitTest.java
dpc-api/src/test/java/gov/cms/dpc/api/cli/tokens/TokenCreateUnitTest.java
dpc-api/src/test/java/gov/cms/dpc/api/cli/tokens/TokenDeleteUnitTest.java
dpc-api/src/test/java/gov/cms/dpc/api/cli/tokens/TokenListUnitTest.java

https://jira.cms.gov/browse/DPC-3678
- new testing folder /tokens and 4 new test files

DPC-3678: Add tests for token cli

---

dpc-portal/Gemfile.lock
dpc-portal/app/components/page/credential_delegate/list_component_preview.rb

No ticket
Upgraded lookbook to upgrade yard
Fixed weird class-loading issue in credential_delegate/list_component_preview
Blocking rollout

Upgrade to address yard vulnerability CVE-2024-27285

---

dpc-portal/Gemfile
dpc-portal/Gemfile.lock

No ticket
json-jwt forced upgrade version
Fixes security vulnerability CVE-2023-51774
Builds

fix security issue

---

.github/workflows/opt-out-import-test-unit.yml
lambda/opt-out-import/.gitignore
lambda/opt-out-import/Makefile
lambda/opt-out-import/README.md
lambda/opt-out-import/main.go
lambda/opt-out-import/main_test.go

https://jira.cms.gov/browse/DPC-3916

[DPC-3916] Split Unit Tests from Integration Tests

---

dpc-api/src/main/resources/application.yml

Wrap auth_db_pass in quotes to avoid escape chars

---

lambda/opt-out-export/main.go
lambda/opt-out-export/main_test.go
lambda/opt-out-import/README.md
lambda/opt-out-import/db.go
lambda/opt-out-import/db_test.go
lambda/opt-out-import/main.go
lambda/opt-out-import/models.go
lambda/opt-out-import/parsers.go
lambda/opt-out-import/parsers_test.go

https://jira.cms.gov/browse/DPC-3917

[DPC-3917] Update File Naming Conventions for opt-out

---

lambda/opt-out-import/main.go

https://jira.cms.gov/browse/DPC-3961
This resolves an issue introduced [in a previous PR](https://github.com/CMSgov/dpc-app/pull/2055/files?diff=split&w=0#diff-c0543357d02d58ebd5ea8e708f60c113e1172cc9b3aa7b64947a3afb4af7db48L175) that broke `make run-local` at `downloadS3File`. The code here simply bypasses the need to assume a role to access the S3 bucket during local development. 
This unblocks local development for the time being. Integration tests still run from GitHub Actions, but they don't appear to work in a local environment (they didn't before either, so not a regression).
The issue may have been exacerbated by the use of the `IS_TESTING` environment variable, which is used for multiple purposes. At the moment, `make run-local` relies on that env var to be `true`, and while some …

[DPC-3961] Split downloadS3File for local development

---

lambda/opt-out-import/main.go

N/A
- Switch warning log to info log
Our Splunk alert will notify for any error or warning logs. This log should not send an alert to anyone.
N/A

Switch from warn --> info log

---

docker-compose.portals.yml

No ticket
Duplicate entries in dpc_web environment stanza
Breaking github action tests
Passes github actions test

Remove duplicates in docker compose file

---

Makefile

Fix make seed-db

---

dpc-web/app/views/shared/_head.html.erb
dpc-web/app/views/shared/_tealium.html.erb

https://jira.cms.gov/browse/DPC-3979
In header and on page, use 'prod' tealium for sandbox

DPC-3979: Sandbox use prod tealium

---

dpc-aggregation/pom.xml
dpc-api/pom.xml
dpc-attribution/pom.xml
dpc-bluebutton/pom.xml
dpc-common/pom.xml
dpc-consent/pom.xml
dpc-queue/pom.xml
pom.xml

https://jira.cms.gov/browse/DPC-4104
Pom files referencing dropwizard-guicey points to new groupId
Tests started breaking when minor change in structure to mvn repository for dropwizard-guicey.
Tests passed

DPC-4104 make integration tests work

---

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java
dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/ResourceFetcher.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/JobBatchProcessorUnitTest.java
dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/ResourceFetcherUnitTest.java

https://jira.cms.gov/browse/DPC-3846
Remove repeated calls for same resources.

[DPC-3846] Reduce redundant calls to BFD

---

dpc-portal/app/components/page/session/invitation_login_component.html.erb
dpc-portal/spec/components/page/session/invitation_login_component_spec.rb

No ticket
Invitations login page less duplicates real login page

Fix duplicate

---

dpc-web/Gemfile

https://jira.cms.gov/browse/DPC-4059

Remove spring as dependency in dpc-web

---

Makefile
dpc-portal/README.md
dpc-portal/bin/console
dpc-portal/bin/sh
dpc-portal/lib/tasks/dpc.rake

N/A
- Add scripts to generate GOLDEN_MACAROON as part of `make portal-console` and `make portal-sh`
- Update README with instructions on how to go through Org setup and AO invitation flow
- Reorganize README a bit to consolidate test instructions and such
Wanted to go through the current workflow and had to trawl through the code a bit to figure out AO invitations as it is currently built. Added documentation while getting it to work.
Walked through the steps as written in order to get AO invitation working for myself.

docs: Update portal README with manual workflow instructions

---

.github/workflows/opt-out-export-dev-deploy.yml
.github/workflows/opt-out-import-dev-deploy.yml
README.md
bbcerts/README.md
dpc-admin/app/views/user_mailer/provider_sandbox_email.html.erb
dpc-admin/app/views/user_mailer/vendor_sandbox_email.html.erb
dpc-testing/README.md
dpc-web/app/views/user_mailer/provider_sandbox_email.html.erb
dpc-web/app/views/user_mailer/vendor_sandbox_email.html.erb
engines/api_client/README.md
src/main/resources/README.md

https://jira.cms.gov/browse/PLT-326
Reference to master branch was changed to main
Github repository master branch renamed to main. changes made to reference main in jenkins instead of master

modify reference of  master branch to main

---

Makefile
dpc-admin-portal-test.sh
dpc-portal-test.sh
dpc-portals-test.sh
dpc-test.sh
dpc-unit-test.sh
dpc-web-portal-test.sh

No Ticket
This updates the docker-compose commands that run in our GitHub Actions, so that our builds will succeed. See https://github.com/orgs/community/discussions/116610 for relevant discussion.

Fix GitHub Actions

---

docker-compose.portals.yml
dpc-portal/app/controllers/application_controller.rb
dpc-portal/app/controllers/credential_delegate_invitations_controller.rb
dpc-portal/app/controllers/invitations_controller.rb
dpc-portal/app/controllers/login_dot_gov_controller.rb
dpc-portal/app/controllers/organizations_controller.rb
dpc-portal/app/controllers/users/sessions_controller.rb
dpc-portal/app/lib/dpc_json_logger.rb
dpc-portal/app/models/invitation.rb
dpc-portal/app/services/ao_invitation_service.rb
dpc-portal/config/initializers/logging.rb
dpc-portal/spec/lib/dpc_json_logger_spec.rb
dpc-portal/spec/models/invitation_spec.rb
dpc-portal/spec/requests/credential_delegate_invitations_spec.rb
dpc-portal/spec/requests/invitations_spec.rb
dpc-portal/spec/requests/login_dot_gov_spec.rb
dpc-portal/spec/requests/organizations_spec.rb
dpc-portal/spec/services/ao_invitation_service_spec.rb

https://jira.cms.gov/browse/DPC-3820
- Created a set of string constants for standard logging events and fields
- Log all events described in the ticket

[DPC-3820] DPC Portal Audit Logging

---

dpc-portal/bin/sidekiq-dev
dpc-portal/bin/sidekiq-nonprod

https://jira.cms.gov/browse/DPC-4185
- update regex to fix the way logs are formatted in splunk. See attached.
- created 4 new alerts (prod and prod-sbx marked disabled) linked in the ticket above

[DPC-4185] update log regex for portal sidekiq instances

---

dpc-attribution/src/main/java/gov/cms/dpc/attribution/jobs/ExpireAttributions.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/jobs/ExpireAttributionsUnitTest.java

https://jira.cms.gov/browse/DPC-4212
- Add a test for the error case in ExpireAttributions job.
After merging the [previous PR](https://github.com/CMSgov/dpc-app/pull/2251), CI failed due to a SonarQube Quality Gate failure. The only case that isn't covered, according to SonarQube, is the error case, so this PR should resolve the issue.

[DPC-4212] Test error case in doJob

---

dpc-admin/Gemfile.lock
dpc-portal/Gemfile.lock
dpc-web/Gemfile.lock

None
This upgrades a dependency in our Gemfile.lock in order to unblock PRs. See https://github.com/CMSgov/dpc-app/actions/runs/11015023600/job/30587060583?pr=2267

[No Ticket] Upgrade Webrick dependency

---

.github/workflows/ci-workflow.yml

https://jira.cms.gov/browse/DPC-4258
sonarqube wait uncommented
sonarqube wait was commented out to unblock tickets until fixed
Verified wait step in actions

Uncomment wait for sonarqube

---

dpc-portal/app/views/invitation_mailer/invite_cd.html.erb

https://jira.cms.gov/browse/DPC-4325
This updates a link in the cd invite mailer to be consistent with the equivalent link in the ao invite mailer.
I [originally](https://github.com/CMSgov/dpc-app/pull/2291#discussion_r1805186111) set this link to what was in the Confluence doc, but was made aware that this is inconsistent from the AO mailer. Upon discussing with content, we decided to make them consistent.

[DPC-4325] Update CD Invite mailer link

---

dpc-web/app/views/shared/_head.html.erb
dpc-web/app/views/shared/_tealium.html.erb

https://jira.cms.gov/browse/DPC-4181
Updated Tealium scripts in dpc-web.
The BlastX team asked us to update the Tealium scripts we use in dpc-web.  See https://github.com/CMSgov/dpc-static-site/pull/130 for static site changes.
Ran the code locally to make sure the new scripts were called.

DPC-4181 Tealium updates to dpc-web

---

dpc-portal/app/controllers/application_controller.rb
dpc-portal/spec/requests/organizations_spec.rb

https://jira.cms.gov/browse/DPC-4355
- block_prod_sbx hook removed
We are pushing the portal to prod-sbx, and we need to be able to pass smoke tests and verify it is working
Tests pass

DPC-4355 Portal allow sandbox

---

.gitignore
dpc-portal/app/concerns/verification.rb
dpc-portal/app/controllers/credential_delegate_invitations_controller.rb
dpc-portal/app/controllers/invitations_controller.rb
dpc-portal/app/services/ao_invitation_service.rb
dpc-portal/config/initializers/logging.rb
dpc-portal/spec/requests/credential_delegate_invitations_spec.rb
dpc-portal/spec/requests/invitations_spec.rb
dpc-portal/spec/services/ao_invitation_service_spec.rb

https://jira.cms.gov/browse/DPC-4370
Supports DPC-4370 by adding to Splunk logs.

[DPC-4370] Add onboarding time logs

---

dpc-portal/app/components/page/invitations/register_component.html.erb
dpc-portal/app/components/page/invitations/register_component_preview.rb
dpc-portal/app/components/page/invitations/start_component.html.erb
dpc-portal/app/components/page/invitations/success_component.html.erb
dpc-portal/app/components/page/invitations/success_component_preview.rb
dpc-portal/app/views/invitation_mailer/invite_ao.html.erb
dpc-portal/spec/components/page/invitations/register_component_spec.rb
dpc-portal/spec/components/page/invitations/start_component_spec.rb
dpc-portal/spec/components/page/invitations/success_component_spec.rb
dpc-portal/spec/mailers/invitation_spec.rb

https://jira.cms.gov/browse/DPC-4378
Added NPI to display wherever Organization Name is.

[DPC-4378] Add organization NPI where missing

---

dpc-aggregation/pom.xml
dpc-attribution/pom.xml
pom.xml

No ticket
base, aggregation, and attribution poms
Snyk created PRs for upgrading these libraries, but the branches they used were quite out of date.
Passes ci

Upgrade snyk-recommended libraries

---

.github/workflows/docker_build.yml

[DPC-4446](https://jira.cms.gov/browse/DPC-4446)
- this PR adds a CI workflow to build dpc-web-portal when a new PR is made to main
- then the newly built image is pushed to AWS ECR
- long-term this is intend to replace jenkins for building docker images for all apps in dpc-app repo, but we need to be able to successfully build all the apps for a given commit first
- currently unable to run make command for building all rails apps at once due to lack of disk space
- see related job [HERE](https://github.com/CMSgov/dpc-app/actions/runs/13037133079/job/36370226051#step:11:7559)
- tested in the CI

[DPC-4446] Build dpc web portal in github action

---

dpc-test.sh

https://jira.cms.gov/browse/DPC-4478
dpc-test.sh: took out line removing database volume
Was having intermittent failures at this point.
CI continues to work.

Leave db volume until end in make ci-app

---

.github/workflows/docker_build.yml

[DPC-4496](https://jira.cms.gov/browse/DPC-4496)
- add job to build dpc-api, dpc-consent, dpc-attribution, and dpc-aggregation and push successfully built docker images  to ECR
- this was previously blocked by flaky build script failing in the CI. Fixed in https://github.com/CMSgov/dpc-app/pull/2405
Tested in CI.
See last successful java build on push [HERE](https://github.com/CMSgov/dpc-app/actions/runs/13078047679/job/36494931949)

[DPC-4496] Build java apps and push to AWS ECR

---

dpc-api/pom.xml
dpc-api/src/main/java/gov/cms/dpc/api/auth/jwt/ValidatingKeyResolver.java
dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/TokenResource.java
dpc-api/src/test/java/gov/cms/dpc/api/auth/jwt/JWTUnitTests.java
dpc-common/pom.xml
dpc-queue/pom.xml
dpc-smoketest/pom.xml
dpc-testing/pom.xml
dpc-testing/src/main/java/gov/cms/dpc/testing/APIAuthHelpers.java
pom.xml

No ticket.
Updates several vulnerable dependencies.
Our Snyk scans auto-generate PRs to solve vulnerable dependencies, but they all have merge conflicts with main because of other changes in pom.xml, so this PR fixes them all at once.
Tests passing.

Update dependencies flagged by Snyk

---

.github/workflows/ecs-deploy.yml
.github/workflows/ecs-release.yml
.github/workflows/generate-macaroon.yml
.github/workflows/promote-build.yml
.github/workflows/smoke-test.yml

https://jira.cms.gov/browse/DPC-4542
workflow id replaced with name of workflow.
We were getting blocking collisions when workflows called other workflows.
Promote passed.

DPC-4542 Fix Concurrency

---

dpc-bluebutton/pom.xml
pom.xml

No ticket.
Updates dependencies marked as vulnerable by Snyk.

Address Snyk findings

---

.github/workflows/ci-workflow.yml

https://jira.cms.gov/browse/DPC-4559
Updates workflow to use ubuntu-latest.
@bhodges-navapbc noticed that one of our workflows was using a version of ubuntu that is near EOL.
Workflow passing.

[DPC-4559] Update ci-workflow.yml

---

dpc-load-testing/README.md

N/A
https://github.com/CMSgov/dpc-app/pull/2504 updated the Makefile to update how the load tests build and run. Here, I'm updating the README to reflect the new commands.

[NO TICKET] Update readme with accurate running instructions

---

dpc-load-testing/script.js

No ticket
Check clause added after finding by npi in load test script
I had an issue where findByNpi wasn't working, and this would have made it more obvious

check find results

---

dpc-smoketest/pom.xml
package-lock.json
package.json
pom.xml

no ticket
- update root pom.xml
- update smoketest pom.xml
- update package.json
- handles the following snyk PR's
- https://github.com/CMSgov/dpc-app/pull/2521/files
- https://github.com/CMSgov/dpc-app/pull/2519/files
- https://github.com/CMSgov/dpc-app/pull/2517/files
- https://github.com/CMSgov/dpc-app/pull/2516/files
- https://github.com/CMSgov/dpc-app/pull/2515/files
- https://github.com/CMSgov/dpc-app/pull/2512/files

update packages from snyk findings

---

.github/workflows/load-test-unit-tests.yml
dpc-load-testing/dpc-api-client.js
dpc-load-testing/eslint.config.js
dpc-load-testing/generate-dpc-token.js
dpc-load-testing/package.json
dpc-load-testing/script.js
dpc-load-testing/yarn.lock

https://jira.cms.gov/browse/DPC-4603
Adds ESLint to workflow.
We're adding JS with our load-testing, so to maintain high code quality, we need to add a linter as well.
Linter running and passing in workflow.

Add ESLint to workflow

---

.github/workflows/dpc-load-test.yml

https://jira.cms.gov/browse/DPC-4635
Added test selection drop down in load test workflow.
We'll be adding "average" and "stress" load tests and need a way select a particular test suite.
Triggered GHA and made sure we could successfully run existing load test script.  See workflow run [here](https://github.com/CMSgov/dpc-app/actions/runs/14498818062).

[DPC-4635] Added load test options in GHA

---

.github/workflows/ecs-deploy.yml

[DPC-4668](https://jira.cms.gov/browse/DPC-4668)
- Rather than manually specifying terraform version used, use the terraform version located in[ .terraform-version](https://github.com/CMSgov/dpc-ops/blob/main/.terraform-version)
- Use platform's [existing Github Action](https://github.com/CMSgov/ab2d-bcda-dpc-platform/blob/main/actions/setup-tfenv-terraform/action.yml) to handle the install
- As we update our infrastructure to work with the new AWS greenfield account, we should take care to follow best practices.
- CDAP recommended using tfenv as that's what other teams are doing.
- tested deploy to test environment [HERE](https://github.com/CMSgov/dpc-app/actions/runs/14580194608/job/40895025965)

[DPC-4668] Use tfenv for terraform install in CI

---

dpc-admin/Gemfile.lock
dpc-portal/Gemfile.lock
dpc-web/Gemfile.lock
engines/api_client/Gemfile.lock

update nokogiri dependency to fix failure

---

.github/workflows/ecs-deploy-gf.yml
.github/workflows/opt-out-export-test-integration-gf.yml
.github/workflows/smoke-test-gf.yml
dpc-admin/README.md

No ticket. This is a follow-up to https://github.com/CMSgov/dpc-app/pull/2646. Discussion located [HERE](https://github.com/CMSgov/dpc-app/pull/2646#discussion_r2105376571).
- As part of the migration to AWS greenfield accounts, naming has been updated to "sandbox" for the "sandbox" environment
n/a

update workflow files to use 'sandbox' instead of 'prod-sbx' env naming

---

.github/workflows/api-waf-sync-test-integration-gf.yml
.github/workflows/opt-out-import-test-integration-gf.yml

https://jira.cms.gov/browse/DPC-4719
This creates integration test workflows for both the opt-out-import lambda and the waf api sync lambda, in the greenfield environment.

[DPC-4719] lambda integration tests

---

.github/workflows/dpc-load-test.yml
.github/workflows/load-test-unit-tests.yml
dpc-load-testing/single-iteration.js

https://jira.cms.gov/browse/DPC-4672
Update dpc-load-test workflow:
- runs-on the correct runner for GF infrastructure
- sets permissions needed to access AWS infra
- gets credentials for non-prod AWS infra
Update load-test-unit-tests:
- runs-on the correct runner for GF infrastructure
Post Greenfield migration, these workflows weren't running properly. This PR makes the necessary updates to get our load test suite running again.

[DPC-4672] Update Load Test GHA Workflow

---

dpc-admin/Gemfile.lock
dpc-portal/Gemfile.lock
dpc-web/Gemfile.lock

No ticket
Version of thor library upgraded in Gemfile.lock
Addresses CVE-2025-54314
Builds and passes CI.

upgrade thor

---

.github/workflows/ci-workflow.yml

No ticket
mvn sonar scanner upgraded to 4.0
Upgrade to sonarqube server made former scanner not work
Sonarqube passes

upgrade sonar scanner

---

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PatientResourceUnitTest.java
dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/PatientResource.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/jdbi/PatientDAOUnitTest.java
dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/v1/PatientResourceUnitTest.java

n/a this was a different branch used for debugging SonarQube issues and I accidentally pushed to this remote instead of my original feature branch: ls/task-4420-patient-paging

temporary branch for fixing issues
