.travis.yml, README.md, docker-compose.yml, dpc-attribution/pom.xml, dpc-attribution/src/main/java/gov/cms/dpc/attribution/AttributionAppModule.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/DPCAttributionService.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/cli/SeedCommand.java, dpc-attribution/src/main/resources/application.conf, dpc-attribution/src/main/resources/dev.application.conf
We no longer support using the H2 database for local testing. We now require a local Postgres installation, which simplifies the setup and configuration process.
This also resolves DPC-172 in which the application was leaking database connections because the SessionFactory was not being injected as a singleton.
When running in TravisCI, we need to add a `postgres` service to the .yml file, in order to have something local to test against. Eventually, this will probably go away and get moved into the docker compose file, but we'll rely on the builtin services for now.
=> DPC-168: Remove support for H2 database

.codeclimate.yml, .travis.yml, docker-compose.yml, dpc-attribution/pom.xml, dpc-attribution/src/main/java/gov/cms/dpc/attribution/AttributionAppModule.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/cli/SeedCommand.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/ProviderDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/RelationshipDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/models/ProviderEntity.java, dpc-attribution/src/main/resources/application.conf, dpc-attribution/src/main/resources/dev.application.conf, dpc-common/pom.xml, dpc-common/src/main/java/gov/cms/dpc/common/entities/AttributionRelationship.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/PatientEntity.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/ProviderEntity.java
Added support for the JOOQ SQL framework, which means we now have a clean, typesafe interface for executing custom SQL queries.
This is primarily used in the `SeedCommand` class, since we can't inject the Hibernate context in a `Command` because it's not configured yet. This lets us remove a bunch of code and much more cleanly express our intent.
The Java classes are generated by JOOQ, based on our JPA entities. Due to the order of compilation, we had to move the entities in the `dpc-common` module, so that they would be available for JOOQ to parse. This add a step to the `generate-sources` phase of maven, but it should be handled automatically. The resulting classes are generated in the `target/` directory, so there's nothing for us to commit to git.
=> DPC-169: Implement typesafe SQL

README.md, dpc-aggregation/pom.xml, dpc-aggregation/src/main/resources/application.conf, dpc-api/pom.xml, dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIConfiguration.java, dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIService.java, dpc-api/src/main/resources/application.conf, dpc-attribution/pom.xml, dpc-attribution/src/main/resources/application.conf, dpc-queue/src/main/resources/reference.conf, dpc-queue/src/test/resources/hibernate.cfg.xml, src/main/resources/server.conf
This PR is mainly around reworking the configuration files so that we have single points of contact for making changes.
Each service now has its options isolated into its own namespace (e.g. `dpc.attribution{}`), which means we can override settings for each service as we need to.
In order to reduce config duplication, most of the common settings (e.g. service ports, database connection properties, logging, etc) have been moved into a `server.conf` file in the `src/main/resources` directory. Each service can then `include "server.conf" within its namespace and inherit the default settings, which it is free to override as it sees fit.
In order for this to work correctly, each service needs to include the `src/main/resources` directory in its build, which is accomplished by adding:
```xml …
```
=> DPC-94: Unified Dropwizard configuration

.travis.yml, README.md, dpc-attribution/pom.xml, dpc-attribution/src/main/java/gov/cms/dpc/attribution/AttributionAppModule.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/AttributionException.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/cli/SeedCommand.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/AbstractRecordUpserter.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/PatientRecordUpserter.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/ProviderDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/ProviderRecordUpserter.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/RelationshipDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/RosterEngine.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/RosterUtils.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jobs/ExpireAttributions.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/AbstractGroupResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/GroupResource.java, dpc-attribution/src/main/resources/migrations.xml, dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionFHIRTest.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/SharedMethods.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/jobs/ExpirationJobTest.java, dpc-attribution/src/test/resources/application.conf, dpc-common/src/main/java/gov/cms/dpc/common/entities/AttributionRelationship.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/PatientEntity.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/ProviderEntity.java, dpc-common/src/main/java/gov/cms/dpc/common/hibernate/DPCHibernateModule.java, pom.xml
**Why**
This PR adds the ability for vendors to add/remove attribution relationships to their existing rosters. Duplicate records are handled using an *upsert* methodology, where new records are inserted as they are, conflicting records are merged using a user defined function.
**What changed**
The external API did not change much at all. No additional endpoints were created. The majority of the changes are internal, with largest being that I replaced the existing Roster logic (which was using Hibernate) to an alternative implementation using JOOQ. This allows for a much cleaner implementation and type-safe SQL, which is generated from the Hibernate entities.
This also adds logic for merging new data into existing records, in order to do this, I've created an `AbstractRecordUpserter` …
=> DPC-23: Add ability to resubmit roster

dpc-api/src/test/java/gov/cms/dpc/api/EndToEndRequestTest.java
DPC-110 and DPC-206 had some interactions with each other.
When merging DPC-206, I neglected to re-run the tests against the latest master.
This is a small tweak to get things building and passing again.
=> DPC-206: Fix failing compilation in endtoend tests

.travis.yml, docker-compose.yml, dpc-aggregation/pom.xml, dpc-aggregation/src/main/resources/sbx.application.conf, dpc-api/pom.xml, dpc-api/src/main/java/gov/cms/dpc/api/cli/DemoCommand.java, dpc-api/src/main/java/gov/cms/dpc/api/models/JobCompletionModel.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/JobResource.java, dpc-api/src/main/resources/sbx.application.conf, dpc-api/src/test/java/gov/cms/dpc/api/EndToEndRequestTest.java, dpc-attribution/pom.xml, dpc-attribution/src/main/resources/sbx.application.conf, dpc-queue/src/main/java/gov/cms/dpc/queue/DistributedQueue.java, dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobModel.java, pom.xml
**Why**
This ticket was originally opened because the JobModel serialization as failing in the AWS environments. On digging into it further, it turned out the issue was due to an older copy of code running in the environment which did not have DPC-110 included. This was causing things to fail when running the EndToEnd tests locally.
No changes were made for the originally reported issue, except for some additional logging being added to make tracking job states a bit easier.
While working on this ticket a couple of other issues were discovered.
1. Travis CI was not correctly handling integration test failures.
Due to the stage in which we were running the integration tests, Travis was happy to continue even if one of the commands reported an error. The fix was to simply …
=> DPC-216: Fix failing AWS tests

dpc-api/src/main/java/gov/cms/dpc/api/cli/DemoCommand.java
Hi @nickrobison-usds @RickHawesUSDS 
Was running the demo seeder to build a suitable environment for my demo app and found a small bug. Opening a PR with a suggested fix!
**Why**
To fix the following error in the dpc-api jar demo command:
```
$ java -jar dpc-api/target/dpc-api-0.2.0-SNAPSHOT.jar demo
WARN  [2019-05-09 16:03:10,768] com.squarespace.jersey2.guice.JerseyGuiceUtils: It appears jersey2-guice-spi is either not present or in conflict with some other Jar: ServiceLocatorGeneratorImpl(hk2-locator, 1332691311)
Running demo!
ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to retrieve the server metadata statement during client initialization. URL used was http://http://localhost:3002/v1/metadata
```
Making the demo command work will enable [the example client …
=> Fix default url in demo seeder

docker-compose.yml, dpc-aggregation/pom.xml, dpc-api/pom.xml, dpc-attribution/pom.xml, pom.xml
**Why**
The Docker images are currently setup to use the artifactName as the image tag. That's not a good way to handle it, we need to use the versions as the tags, that way we can separate out release and development versions.
Refactored how we handle the Docker configuration and image naming. Most of the configuration now happens in the `dpc-app` pom where we setup the images names using the AWS ECR address and the maven module name. This means each service only needs to specify the variables that it cares about or needs changed. By default, we tag each service with the `latest` tag, which means ECS will automatically update the image on each service reload/restart.
Also added a `release` profile in maven which tags the image with the artifact version, instead of the …
=> DPC-222: Update Docker Image tags

dpc-api/pom.xml, dpc-api/src/main/java/gov/cms/dpc/api/converters/OffsetDateTimeToStringConverter.java, dpc-api/src/main/java/gov/cms/dpc/api/core/Capabilities.java, dpc-api/src/main/resources/app.properties, dpc-api/src/test/java/gov/cms/dpc/api/core/CapabilitiesTest.java, dpc-common/src/main/java/gov/cms/dpc/common/utils/PropertiesProvider.java, dpc-common/src/main/java/gov/cms/dpc/fhir/FHIRFormatters.java, pom.xml
**Why**
FHIR clients use the capabilities statement to determine which operations they can perform against our system. Previously, the statement was really bare bones and hadn't been updated with the new Roster, Job and Data endpoints. That's now been fixed.
Updated the Capabilities Statement to include the new endpoints.
Added a generic ability to inject Maven variables (build time values) into the Java runtime, so we can now automatically use the build timestamp and version number in our capabilities statement.
I'm intentionally keeping things simple for now. The statements are really verbose which means the best option going forward is to find a way to autogenerate values using something like ByteBuddy.
**Tickets closed**
DPC-242 …
=> DPC-242: Update capabilities statement

dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/AggregationManagerTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/AttributionAppModule.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/ProviderDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/RelationshipDAO.java, dpc-common/src/main/java/gov/cms/dpc/common/hibernate/DPCHibernateModule.java, dpc-common/src/main/java/gov/cms/dpc/common/hibernate/DPCManagedSessionFactory.java, dpc-queue/src/main/java/gov/cms/dpc/queue/DistributedQueue.java, dpc-queue/src/test/java/gov/cms/dpc/queue/QueueHealthTest.java, dpc-queue/src/test/java/gov/cms/dpc/queue/QueueTest.java
**Why**
Due to the way we make use of our Hibernate connections, we need to manually create and inject sessions into various classes. This means we also needs to handle the lifecycle correctly (e.g. cleaning up connection pools), which we weren't doing previously.
We no longer directly inject the Hibernate `SessionFactory` into various resources, instead, we wrap the factory into a Manager class that Hibernate knows how to start/stop correctly. This means we had to modify the method signatures of the injection points to accept a manager and then grab the Session Factory. 
It's a little awkward to inject a wrapper class and then grab the protected resource, but avoids the anti-pattern of injecting a closable resource from a Guice provider.
**Tickets …
=> DPC-233: Improved database connection handling

README.md, pom.xml
**Why**
This issue was originally reported by an early user, where the build was failing with a missing dependency error, when the root cause was really building against an incorrect JDK.
We need to be explicit about what versions of Java we do and do not support. Especially since we're blocked on upgrading to Java 12.
We're already using the Maven Enforcer plugin to check for a useable Maven version, this just adds an additional rule that checks the user is building with JDK 11.
I also updated the README a bit to make the version requirement more explicit and clear up some confusing parts.
Keep it simple
**Tickets Closed**
DPC-266: Restrict Java versions
DPC-208: Address build failures in Java 12.
=> DPC-266: Restrict application building to only Java 11

dpc-web/app/views/public/docs.html.erb, dpc-web/config/routes.rb
**Why**
Create a route for API documentation and page in `views/public`. http://localhost:3000/docs should now resolve.
Used `match` method since that's what we were using for the landing page. 
- Breaking up some of the partials and layout files to better improve the design of this site.  
- Don't quite know what will be included in the documentation. Will it be a single page or include multiple sections? I think we are going to follow Bue Button 2.0 for now, which is a single page.
=> create api documentation route

dpc-web/app/assets/javascripts/api_documents.coffee, dpc-web/app/assets/stylesheets/api_documents.scss, dpc-web/app/controllers/api_documents_controller.rb, dpc-web/app/helpers/api_documents_helper.rb, dpc-web/app/helpers/application_helper.rb, dpc-web/app/views/api_documents/home.html.erb, dpc-web/app/views/layouts/application.html.erb, dpc-web/app/views/public/docs.html.erb, dpc-web/app/views/shared/_navbar.html.erb, dpc-web/config/routes.rb, dpc-web/spec/controllers/api_documents_controller_spec.rb, dpc-web/spec/helpers/api_documents_helper_spec.rb
**Why**
Need to set up controller for API documentation
- Created a new controller the API Documentation
- Organized layout files to support appropriate content
- Set up a better way of handling page titles.
- New controller for API documentation would the section up better for future needs
- Need page help to organize page titles outside of main content, also in the `<title>` tag.
https://jiraent.cms.gov/browse/DPC-299
=> Create API documents controller

dpc-aggregation/src/main/resources/sbx.application.conf, dpc-api/src/main/resources/sbx.application.conf, dpc-attribution/src/main/java/gov/cms/dpc/attribution/DPCAttributionConfiguration.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/DPCAttributionService.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/cli/SeedCommand.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/tasks/TruncateDatabase.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/utils/DBUtils.java, dpc-attribution/src/main/resources/application.conf, dpc-attribution/src/main/resources/migrations.xml, dpc-attribution/src/main/resources/queue_migrations.xml, dpc-attribution/src/test/java/gov/cms/dpc/attribution/AbstractAttributionTest.java, dpc-macaroons/src/test/resources/hibernate.cfg.xml, dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobModel.java, dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobResult.java, dpc-queue/src/main/resources/queue.conf, dpc-queue/src/test/resources/hibernate.cfg.xml
**Why**
While working on DPC-30 some of the integration tests were failing due to the `root_key` table being missing. It turns out the Liquibase DB migrations were not being applied automatically on application startup. Most of the tests were passing because a config option in the `dpc-queue` module meant Hibernate was automatically creating some of the tables, but only ones that it knew about. This was not only incomplete, but also really brittle.
Added support for automatically migrating the database schema when the `attribution` service starts. We can disable this by setting `schemaMigrationEnabled = false` in the configuration settings.
Moved the queue table creation into the main migration script and removed the errant Hibernate config option.
The …
=> DPC-315: Automatically apply database migrations

dpc-web/Gemfile, dpc-web/Gemfile.lock, dpc-web/app/assets/stylesheets/_rouge.scss.erb, dpc-web/app/assets/stylesheets/application.scss, dpc-web/app/controllers/api_documents_controller.rb, dpc-web/app/helpers/application_helper.rb, dpc-web/app/views/api_documents/home.html.erb, dpc-web/app/views/api_documents/home.md, dpc-web/config/initializers/rouge_highlighter.rb, dpc-web/monokai.css, dpc-web/package-lock.json
**Why**
The API documentation will have a lot of copy, so supporting markdown will make writing it much easier. In addition, the syntax highlights will help make the code examples much easier to read.
- 1 markdown file per view
- Syntax highlighting 
- [Kramdown](https://kramdown.gettalong.org/quickref.html) - This was the easiest markdown syntax to use.
https://jiraent.cms.gov/browse/DPC-310
=> Markdown support and syntax highlighting

dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIService.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/DataResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/JobResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PractitionerResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/RosterResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/DPCAttributionService.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/EndpointResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/GroupResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/OrganizationResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/PractitionerResource.java, dpc-bluebutton/pom.xml, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/BlueButtonClientModule.java, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClientImpl.java, dpc-common/src/main/java/gov/cms/dpc/common/utils/MetricMaker.java, dpc-queue/src/main/java/gov/cms/dpc/queue/DistributedQueue.java
**Why**
This pull requests adds more instrumentation to the API and Attribution servers. 
For each end-point method a Timer and an Exception Meter metric was added. For each Blue Button client method a Timer and an Exception Meter was added as well. Combined with the previously added metrics, a good set of metrics is now pushed to the logs.  
- DropWizard provides a very complete set of JVM and Servlet metrics. Decided not to add more. 
- Looked at adding Hibernate metrics. Decided against it after researching the performance cost of these metrics. See: https://www.baeldung.com/hibernate-common-performance-problems-in-logs. 
- Using the Dropwizard InstrumentedHttpClient was tried, but it proved too awkward to use for our system.   …
=> DPC-318: Instrumentation

dpc-web/app/views/public/_hero.html.erb
**Why**
SVG scaling is messed up in IE11. Removing the` viewbox` from the `svg` tag resolves the issue, and the property is already in the sprite.
=> Remove viewbox to fix IE scaling

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/AggregationAppModule.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/DPCAggregationConfiguration.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/OperationsConfig.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/ResourceFetcher.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/AggregationEngineTest.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/BatchAggregationEngineTest.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/EncryptingAggregationEngineTest.java, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/MockBlueButtonClient.java, dpc-common/src/main/java/gov/cms/dpc/fhir/hapi/ContextUtils.java
**Why**
Finish the parallel execution work on the aggregation engine to improve throughput.  
- Turn on parallel execution by default
- Made fixed sized thread pools to avoid thread exhaustion error cases. 
- Added a new thread pool for parallel writes of files
- Added configuration fields for number of thread for fetches and writes
- Separate thread pools for fetches and writes to accommodate the different throughput requirements of each operation. 
- Initially, made the fetch pool 5x the size of the write because BB fetch latency dominates. 
- Made the global error handler setup in multiple places including tests. Made the handler a static method. 
- Made the thread pool size based on the CPU count, so configs do not need to be adjust as much between …
=>  DPC-145: Finish parallel execution

src/main/resources/server.conf
**Why**
During integration testing, we're opening a ton of database connections (nearly 100) since the connection pool will automatically scale to 100. Since Postgres only allows 100 connections by default, this means we quickly run into errors.
Reduced the default thread pool size, and the maximum value as well. We now start 5 DB connections and can flex up to 10. This prevents Postgres from throwing exceptions when too many clients are open. Such as when rapidly running integration tests where the connection pool doesn't get cleaned up in time.
This can (and will be) be overridden in higher environments.
Small for now, with the theory that we'll always override in production, plus our unit of scaling isn't making the individual services bigger, it's …
=> DPC-320: Reduce default threadpool size

dpc-web/.dockerignore, dpc-web/Dockerfile, dpc-web/README.md, dpc-web/config/database.yml, dpc-web/docker-compose.yml
**Why**
The DPC hosting infrastructure will involve hosting the website in a Docker container on ECS. To prepare going live with the website, the static website should be dockerized for development testing in preparation for standing up staging and production environments.
- A Docker file and docker-compose.yml file has been added to dpc-web to facilitate building the docker container.
- The dpc-web readme documentation has been updated with instructions for building the docker container.
- The dpc-web Ruby configuration has been tweaked to allow for environment variable overrides needed by the Docker container.
The base Ruby docker image was based off `ruby:2.6.2-alpine`. This is an official Docker image provided by Ruby. The Alpine Linux variant was …
=> DPC-328: Docker container for website

dpc-api/src/main/java/gov/cms/dpc/api/resources/TestResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/DefinitionResourceTest.java, dpc-common/src/main/java/gov/cms/dpc/fhir/validations/profiles/PatientProfile.java, dpc-common/src/main/resources/validations/DPCPatient.json
**Why**
When updating our FHIR profiles, I neglected to update all the other references, which was causing some of the tests to fail.
Updated the URL changes across the application
DPC-422
=> DPC-422: Fixed a bad profile renaming

README.md
**Why**
When @jaysheth1998 and I were starting on this project, we encountered a few hiccups that I wanted to make sure wouldn't happen again. I also fixed some of the formatting to be more consistent. 
- Added links to Docker, Docker-Compose docs
- Specified when to clone (as a more clear 'start' point for getting started)
- Changed the 'note' section below Running via Docker to be in blockquote format
None
Potentially rehauling the `README` to follow traditional Github open source projects to have a full table of contents and a getting started section. (though this might be on the actual dpc website)
Example of a Table of Contents: [Bootstrap](https://github.com/twbs/bootstrap/#table-of-contents)
=> Made README easier to follow for new devs

dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/RosterUtils.java, dpc-attribution/src/main/resources/migrations.xml, dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionFHIRTest.java
**Why**
The attribution list was growing uncontrollably, because we were missing a constraint that avoids patient being double attributed.
Simple change to add the constraint and update the Roster logic to check before trying to write again.
Simple, quick solution.
DPC-424
Nothing
=> DPC-424: Fix missing attribution constraint

dpc-api/src/main/java/gov/cms/dpc/api/resources/TestResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/BaseResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/DataResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/DefinitionResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/JobResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PractitionerResource.java, dpc-api/src/test/java/gov/cms/dpc/api/APIResourceAnnotationTest.java
**Why**
A large amount of the `dpc-api` methods did not have the appropriate annotations specifying the level of authentication provided.
- Added `allResourcesHaveSecurityAnnotations()` test to `APIResourceAnnotationTest`
- Attempted to fix all the `v1` endpoints to make the test pass -- this needs review, I'm not sure if I added the correct annotations for everything, specifically the `PathAuthorizer` tests
**Tickets closed**
**Checklist**
=> Add auth annotation tests

dpc-web/app/views/public/home.html.erb
**Why**
- Broken links are bad.
- Bold text in accordions help improve readability. This was something that got flagged in a usability research call.
**Checklist**
=> fix empty links and text styling

dpc-web/app/views/shared/_head.html.erb
**Why**
This PR adds the `charset` meta tag, and, more importantly, the `viewport` meta tag which allows the site to scale down on mobile devices.
=> add viewport and charset meta tags

dpc-attribution/src/main/java/gov/cms/dpc/attribution/macaroons/ExpirationCaveatVerifier.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/macaroons/ExpirationVerifierTest.java, pom.xml
**Why**
The token expiration logic is currently messed up.
* Re-enabled ExpirationVerifierTest
* Fixed ExpirationCaveatVerifier: The token contains the expiration time. The ExpirationCaveatVerifier was assuming the token contained a generated time and not an expiration time. Due to this, it was applying the token expiration policy to the current time when all that needed to occur was verify that expiration time was after the current time.
N/A
DPC-312
None.
**Checklist**
=> DPC-312: Fix token expiration logic

dpc-web/app/views/pages/faq.html.erb, dpc-web/app/views/pages/support.html.erb, dpc-web/app/views/public/home.html.erb
**Why**
Now that we have the google group set up, let's link to it!
https://jiraent.cms.gov/browse/DPC-445
=> link to google group

dpc-web/Dockerfile, dpc-web/README.md, dpc-web/config/application.rb, dpc-web/docker/entrypoint.sh
**Why**
Database migrations are not currently run anywhere in our manual deployment process.
- Executes the rails `db:migrate` task on Docker container boot.
- Fixes Rails logs not making it to Docker.
The Rails `db:migrate` task is safe to run concurrently on multiple nodes according to: https://github.com/rails/rails/issues/22092
None.
None.
**Checklist**
=> Run db migrations when starting dpc-web Docker container

dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PatientResourceTest.java, dpc-test.sh
**Why**
There's a bug in the `PatientResource` test, which only occurs in Travis, I'm not sure what's going on. DPC-451 has been created to track it, but until then, it's causing all of our builds to be red.
This simply disables the test until we can get DPC-451 working.
I know this is bad, but we can come back to it in the future.
DPC-451
**Checklist**
=> disabling patient updating test

dpc-web/Dockerfile, dpc-web/docker-compose.yml
**Why**
We should also ensure we have the latest documentation every time we build. This ensures the Dockerfile for the website also build the IG documentation.
Adds IG build process to Dockerfile.
**Checklist**
=> IG publisher build for dpc-web Docker

dpc-web/app/helpers/application_helper.rb, dpc-web/app/views/layouts/pages.html.erb, dpc-web/app/views/pages/guide.html.erb, dpc-web/app/views/pages/reference.html.erb
**Why**
When we moved the docs to the pages controller, we lost the ability to have "Docs" as the banner title. This fix will allow us to override using the `<title>` as the banner title
=> create helper method to allow overrides to banner text

Makefile, dpc-common/src/main/resources/validations/DPCPatient.json, dpc-web/app/views/shared/_head.html.erb
The Google Analytics tag needs to be the first element in the head block, otherwise the reporting doesn't work correctly.
Also fixed a typo in one of our FHIR profiles and added a `website` target to the make file.
=> Fix google analytics tag and update bad link in FHIR IG

ig/framework/_includes/header.html
This time, it should actually stick.
Addressing what should have been fixed with #162. The IG doesn't seem to parse analytics tags correctly, so I just pulled them out.
=> Hotfix to address IG header

dpc-web/app/assets/javascripts/components/navbar.js
**Why**
There's a JS a error on pages that do not include a navbar… mainly in the authentication/sign up flow. 
Check if element exists before adding a listener. 
https://jiraent.cms.gov/browse/DPC-478
=> check if close navbar button exists before adding a listener

dpc-web/app/helpers/devise_helper.rb
**Why**
There was an annoying error message when signing out and then signing in. 
Redid the devise helper to return nothing if there is not a login error, or if the flash contains a sign out message. Otherwise, displayed the custom email/pw error message.
Needed devise helper because we changed the default logout behavior.
=> Fixed up devise helper

ig/framework/_includes/analytics.html
**Why**
We weren't getting any analytics data for [https://dpc.cms.gov/ig/index.html](https://dpc.cms.gov/ig/index.html)
I put the wrong analytics tracking code, total goof, so I put the proper tracking code
**Checklist**
=> Fixed Analytics Id (IG Analytics Fix)

dpc-web/app/assets/stylesheets/base/_base.scss
**Why**
Blockquotes need styling
Added styles to element selector.
https://jiraent.cms.gov/browse/DPC-472
=> blockquote styling

dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/BatchAggregationEngineTest.java
**Why**
Until we get DPC-465 merged in, this disables the parallel testing (which we're not using in production) in order to get CI back up and running.
We need CI, so we'll disable testing for what we're not using.
DPC-465
**Checklist**
=> Temporarily disable parallel job processing

dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/PatientDAO.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PatientResourceTest.java
**Why**
Patient update tests are failing in CI, but not on local machines. It seems the Hibernate cache use the root issue, as it appears we're reading stale data when doing a GET immediately after a PUT.
Updated the patient test to avoid potential test issues with the Hibernate cache, as well as to be more realistic of how people will actually use it.
We don't need the final GET request, because we're already returning the actual database entry, so we already know that the update works.
DPC-451: This ticket
**Checklist**
=> DPC-451: Address failing Patient Update tests

dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIModule.java, dpc-api/src/main/java/gov/cms/dpc/api/cli/DemoCommand.java
Our siteURL provider now pulls the context from the config and builds that into the path.
The Demo command now takes a full url, rather than doing the funky appends, which should help make it more portable between environments.
=> Fix base url generation

dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIModule.java, dpc-api/src/main/java/gov/cms/dpc/api/cli/DemoCommand.java, dpc-api/src/main/java/gov/cms/dpc/api/client/ClientUtils.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractDataResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/DataResource.java
We now just require that the user have a valid auth token, we don't do any specific checking of permissions before returning the file. This will probably have to be revisited at a later date.
Also fixed a small bug in the base URL and updated the Demo Command to fully download the outputted files.
=> Updated authorization pattern in Data resource

docker-compose.yml, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PractitionerResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/PractitionerResourceTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/AbstractEndpointResource.java, dpc-test.sh
**Why**
Authorization was failing for Practitioners because it was still using the old PractitionerRole resource.
Updated the path parameters to use the correct resource. Added a new step in the integration tests to make sure the fix sticks.
Reenabled the API integration tests, which hadn't been running since adding the Postman tests. This makes CI longer, but should be ok.
Also fixed a bug in the docker compose file that was causing it to fail when not running under CI.
DPC-543: Practitioner role fixes
**Checklist**
=> DPC-543: Fix authentication on Practitioner resource

dpc-aggregation/src/main/resources/prod-sbx.application.conf, dpc-aggregation/src/main/resources/test.application.conf, dpc-api/src/main/resources/prod-sbx.application.conf, dpc-api/src/main/resources/test.application.conf, dpc-attribution/src/main/resources/prod-sbx.application.conf, dpc-attribution/src/main/resources/test.application.conf
**Why**
We're having searching trouble for logs in CloudWatch. This is because CloudWatch does not recognize the `\n` character. See: https://stackoverflow.com/questions/53961216/new-line-problem-in-cloutwatch-output-when-logging-with-slf4j-and-io-symphonia/53961294#53961294
Log format changes.
The log format change was only applied to AWS environments so the log format still looks okay locally.
DPC-554
DPC-555: Apply logging changes to future AWS environments
**Checklist**
=> DPC-554: Fix CloudWatch logging format for Java apps

dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractPatientResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PractitionerResource.java, dpc-common/src/main/java/gov/cms/dpc/fhir/helpers/FHIRHelpers.java
**Why**
There was some bad handling of outcome values, which could be null and throw an NPE. This meant that if you tried to double-create a resource it would throw a 500 even though the request returned from the attribution service correctly.
This centralizes our MethodOutcome handling into a helper method, so we don't make the same mistake again, it now just checks to see if a resource is returned, if not, it throws a 500, otherwise it parses the created flag to determine if it should return a 200 or 201.
DPC-551: Fix group double creation.
**Checklist**
=> DPC-551: Fix resource creation failing on duplicates

dpc-api/src/main/java/gov/cms/dpc/api/auth/MacaroonsAuthenticator.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/GroupResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/utils/RESTUtils.java
**Why**
Group operations were failing due to the Macaroons authenticator not building the search query correctly. This surfaced a number of issues that need to be address, most pressingly, our lack of authenticated test suites.
Made quick fix to have the authenticator specially handle Group resources, along with a ticket (DPC-552) to centralize how we're handling Organization tagging.
Also fixed an NPE that was happening in the Group search method when a providerNPI wasn't passed.
Just a quick fix for now, because when we make these changes we'll need to really work on improving our test suite.
DPC-547: Fix Group authorization bug
DPC-552: Standardize on Organization tags for searching
DPC-553: Move Postman tests to …
=> DPC-547: Fix authentication Group operations

dpc-aggregation/src/main/resources/prod-sbx.application.conf, dpc-aggregation/src/main/resources/test.application.conf, dpc-api/src/main/resources/prod-sbx.application.conf, dpc-api/src/main/resources/test.application.conf, dpc-attribution/src/main/resources/prod-sbx.application.conf, dpc-attribution/src/main/resources/test.application.conf, src/main/resources/server.conf
**Why**
The previous PR #195 only partially fixed the issue. Logs were being grouped, but newlines were being lost. This resolves the issue in a way that keeps CloudWatch logs grouped.
Replaces the `\n` character in logs with `\r`, which CloudWatch recognizes as a newline.
This fix now applies to all environments, as `\r` will be recognized locally. Therefore we can close DPC-555 as well, and not have to worry about this for future environments.
DPC-554
DPC-555
None
**Checklist**
=> DPC-554: Fix CloudWatch Logs

Makefile, dpc-api/src/main/java/gov/cms/dpc/api/cli/DemoCommand.java, dpc-api/src/main/java/gov/cms/dpc/api/client/ClientUtils.java, dpc-smoketest/pom.xml, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java, pom.xml, src/main/resources/SmokeTest.jmx, src/main/resources/prod-sbx.properties, src/main/resources/test.properties
**Why**
We need a way to run load and smoke tests against our AWS environments. This PR adds a really basic JMeter script which should accomplish this.
Added a `dpc-smoketest` module, which contains the necessary classes for building a custom `JavaRequestSampler` which is how we can wrap our custom Java logic into something that JMeter can understand.
Also added `smoke/test` and `smoke/sbx` targets to the Makefile, which should make it nice and easy to run tests after deploys.
Everything is in a single class right now, which was easy to get working, but doesn't really give us deep insights into which parts of the application are slow, or how long individual requests take. We may want to improve that in the future, but JMeter makes it really hard to have …
=> DPC-256: JMeter load test

.dockerignore, .travis.yml, Makefile, docker-compose.yml, dpc-test.sh, dpc-web-test.sh, dpc-web/Dockerfile, dpc-web/docker-compose.yml
**Why**
We'd like to run our integration tests as part of the build process on Jenkins (in addition to Travis CI). This PR makes it easier to share the logic between Jenkins and TravisCI, as well as adds integration tests for dpc-web.
- Two new make commands `ci-app` and `ci-web` to build and run all integration tests.
- dpc-web will now run the existing integration test suite in Travis via rspec. (These were not being run before.)
- Speeds up the dpc-web Docker build by better reusing layers.
- Fixes issues with the `dpc-test.sh` script running code coverage steps without the `REPORT_COVERAGE` environment variable.
- Refactored the `dpc-test.sh` script to install dependencies instead of doing it via `travis.yml`. This allows Jenkins to share installation …
=> DPC-558: Jenkins Integration Tests

docker-compose.yml, dpc-test.sh
**Why**
We have a race condition during testing where the db sometimes will not be started when the attribution / aggregation sever starts. The docker container would exit and the attribution / aggregation server would not be started, causing the API tests to fail.
This PR includes the DB and Redis server in our `start_dependencies` and `start_api` targets to ensure the ports are ready for traffic before starting any server that depends on them. This pattern was introduced in #199 but did not include the DB and Redis servers in the dependencies.
**Checklist**
=> DPC-558: Fix testing race condition

dpc-web/app/views/pages/reference.md
The profile information in the docs was either missing, or pointed to the wrong URL. This should fix that.
**Why**
One of our partners reported that they were unable to submit patient and practitioner records. The issue was due to missing profiles in the submitted resources, but the documentation was wrong on the website, which may have been adding to the confusion.
Updated the documentation have the correct URL and be present on both the patient and practitioner examples.
DPC-604
DPC-532: Profile validations are not apply correctly.
**Checklist**
=> DPC-604: Updated documentation to be clearer about profiles

pom.xml
**Why**
When rebasing our HAPI fork against the latest master, we introduced some breaking changes that caused all of our builds to fail. This was due to our current pom coordinates pointing to the tip of our branch, rather than a specific commit.
Rather than pointing to our fork head, we're targeting a specific commit, which should be much more stable.
Eventually, we'll need to mainline some of our changes.
**Checklist**
=> Lock HAPI FHIR dependencies to specific commit

dpc-web/Gemfile, dpc-web/Gemfile.lock, dpc-web/app/views/internal/auth/sessions/new.html.erb
**Why**
We need to make sure that we're mitigating the Cross Site Scripting
Forgery vulnerability by using a POST method to initiate the Omniauth
flow. For more info:
https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284
https://github.com/omniauth/omniauth/pull/809
* Add a gem that enforces using `post` only with oauth initiation requests
* Change out github link to use the `post` method
=> Resolve CVE-2015-9284 vulnerability

dpc-web-test.sh, dpc-web/docker-compose.yml
**Why**
My most recent Docker builds have been failing in Jenkins, the error thrown is that the database isn't ready when the tests start.
Added the `wait-for-dependencies` docker image to block until the DB is truly ready.
**Checklist**
=> Setup docker-compose file to wait for Database before running specs

dpc-api/src/main/java/gov/cms/dpc/api/auth/DPCAuthFilter.java, dpc-api/src/test/java/gov/cms/dpc/api/AuthenticationTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/OrganizationResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/TokenResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/utils/RESTUtils.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/OrganizationRegistrationTest.java, dpc-macaroons/src/main/java/gov/cms/dpc/macaroons/MacaroonBakery.java, dpc-macaroons/src/main/java/gov/cms/dpc/macaroons/exceptions/BakeryException.java
**Why**
We received a bug report where 500 errors were being returned for all endpoints, this was due to the client sending a malformed authorization token, which was causing Bakery to throw an exception. This was really confusing for both us and the client.
Bakery now traps `DeSerializationExceptions` and re-throws them as a `BakeryException`. We then catch that in the token routines and return a `422`, rather than simply failing with a `500` status.
Only `422` errors are caught and handled (which covers missing tokens and malformed tokens), anything else is returned as a 500, which I think makes sense.
DPC-613:
**Checklist**
=> DPC-613: Improve handling of malformed tokens

dpc-web/config/environments/production.rb
**Why**
We want to see more detailed logs sometimes. 
Make Log level an ENV var so we can change it at will. Default to the standard prod level, :warn.
=> Make log level an ENV var for debugging purposes

dpc-common/src/main/java/gov/cms/dpc/fhir/FHIRExtractors.java, dpc-common/src/main/java/gov/cms/dpc/fhir/dropwizard/handlers/FHIRExceptionHandler.java, dpc-web/app/views/pages/reference.md
**Why**
During the connectathon we ran into some issues with opaque error messages when trying to great a Group with an incorrect codeable concept.
Turns out, the documentation was incorrect which caused the confusion, but we needed to propagate the errors up from the attribution service.
Split up the code parsing in the Group resource, so we can be a bit more detailed as to what's going on.
Improved our FHIRException handler to check to see if the thrown exception is a HAPI error, if so, we can pull the status and operation outcome from the object and send that along. This should really help improve our error handling and verbosity.
DPC-627
**Checklist**
=> DPC-627: Address NPE in malformed group resource

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/JobResource.java, dpc-api/src/test/java/gov/cms/dpc/api/FHIRSubmissionTest.java, src/test/EndToEndRequestTest.postman_collection.json
**Why**
When starting an export job, we were sending a 204 response, but it's actually supposed to be 202. 
Small tweak to the response and tests. Also updated the test suite to pass and the docs as well.
**Checklist**
=> Export endpoint now correctly returns 202 status

dpc-api/src/main/java/gov/cms/dpc/api/models/JobCompletionModel.java
**Why**
We actually need an access token to retrieve the exported resources, so let's say so.
Fixed the hard coded `false` value to be true.
It's still hard coded, because that's easy and will be mostly correct.
**Checklist**
=> Correct access token requirement on export response

dpc-web/app/views/pages/reference.md
**Why**
The `Provider.identifier` block was incorrect, the actual NPI should be in the `value` field, rather than `code`.
Simple documentation change, the underlying code is correct.
**Checklist**
=> Corrected Identifier value in Provider example

dpc-web/app/controllers/internal/taggings_controller.rb, dpc-web/app/controllers/internal/tags_controller.rb, dpc-web/app/helpers/internal/tags_helper.rb, dpc-web/app/helpers/internal/users_helper.rb, dpc-web/app/models/tag.rb, dpc-web/app/models/tagging.rb, dpc-web/app/models/user.rb, dpc-web/app/views/internal/tags/index.html.erb, dpc-web/app/views/internal/users/index.html.erb, dpc-web/app/views/internal/users/show.html.erb, dpc-web/app/views/shared/_alerts.html.erb, dpc-web/config/routes.rb, dpc-web/db/migrate/20190916190939_create_tags.rb, dpc-web/db/schema.rb, dpc-web/spec/controllers/internal/taggings_controller_spec.rb, dpc-web/spec/controllers/internal/tags_controller_spec.rb, dpc-web/spec/factories/taggings.rb, dpc-web/spec/factories/tags.rb, dpc-web/spec/features/authentication/internal_user_sign_in_spec.rb, dpc-web/spec/features/authentication/user_resets_password_spec.rb, dpc-web/spec/features/authentication/user_sign_in_spec.rb, dpc-web/spec/features/internal/user_management/searching_and_filtering_users_spec.rb, dpc-web/spec/features/internal/user_management/updating_users_spec.rb, dpc-web/spec/features/registration/new_user_signs_up_for_account_spec.rb, dpc-web/spec/helpers/internal/tags_helper_spec.rb, dpc-web/spec/helpers/internal/users_helper_spec.rb, dpc-web/spec/models/tag_spec.rb, dpc-web/spec/models/tagging_spec.rb
**Why**
We want to use tags to help internal users manage users.
Add tags to the user page so that an internal user can see and add tags to the user. Also add UI for creating tags themselves so that the internal user adds a tag before they can tag the user with that tag (eventually we probably want to change this UI but this was the fastest for now).
Managing tags:
When you try to delete a tag that is being used:
Adding tags to a user:
Tags visible from the index page:
I made this a polymorphic association with a `has_many: :through` association, so that we can use tags for organizations, vendors, etc, eventually rather than creating separate tables for those taggings. This architecture is more extensible and DRYer. 
Part of DPC-510 …
=> As a CMS user, I want to tag users.

dpc-api/src/test/java/gov/cms/dpc/api/APITestHelpers.java, dpc-common/src/main/java/gov/cms/dpc/fhir/validations/dropwizard/FHIRValidationModule.java, dpc-common/src/main/java/gov/cms/dpc/fhir/validations/dropwizard/FHIRValidatorProvider.java
**Why**
During the FHIR Connectathon we ran into an issue where incorrect profiles were being applied to resources, for seemingly no reason.
Turns out, we can't inject the FHIRValidator as a singleton, because it's not thread-safe. That means we need a new `FhirInstanceValidator` per invocation.
Removed the `Singleton` scope from the `FHIRValidatorProfile` class, which solves the threading issue. Unfortunately, that breaks our cache priming so the first couple of invocations are incredibly slow.
Added a hacky double lock-checking process in the provider constructor to prime the cache, but only once.
DPC-626 …
=> DPC-626: Refactor Validator injection to avoid multi-threading issues

dpc-aggregation/docker/entrypoint.sh
**Why**
Now that we have private keys and certs that need to be setup for connecting to the BB backends, we need the containers to be able to grab the files from S3 on startup.
Updated the Docker entrypoint to install the AWSCLI and sync the S3 config bucket on startup. This is behind the BOOTSTRAP environment variable, so it should only run when running in AWS.
Rather than rebasing our Docker image onto something with the cli already installed, we just grab it on startup each time. It should only had a half a minute or so to the startup time, and we can always optimize later.
Ongoing work as part of DPC-560
**Checklist**
=> DPC-562: Update docker entrypoint to download S3 config files

dpc-web/app/assets/stylesheets/application.scss, dpc-web/app/assets/stylesheets/components/_left-nav.scss, dpc-web/app/views/shared/internal/_sidenav.html.erb
**Why**
Creating separate pages for all users, unassigned users, and assigned users will improve the usability and interaction design of all the filter menus. This means we had to create a collapsible left nav menu to support the additional levels.
Added CSS for the left navigation and provide sample HTML to use as we build out the internal user experience.
Use the accordions javascript for the interactions so we don't have to write new javascript. This is consistent with the way the US Web Design system handles the mobile navigation menus. 
Hook up to actual views
=> style collapsible left nav, static html for later use

dpc-attribution/src/main/resources/queue_migrations.xml
**THIS TICKET SHOULD NOT BE MERGED UNTIL DPC-499 (#218) IS DEPLOYED IN PROD-SBX AND TESTED**
**Why**
We've built an entirely new database to manage the queue. The old tables are no longer needed and should be removed.
Includes the database changeset to remove the old queue tables.
- A separate PR was created to ensure the new queue is working before we delete the data from the old tables.
- If we need to ensure old jobs are still retrievable, we should not merge this. Since we're only in synthetic data, I believe a breaking change of this scale is acceptable.
DPC-603: This ticket.
- This PR should be rebased after #218 is merged to get a clean changeset.
**Checklist**
=> DPC-603: Remove the old queue tables

.github/pull_request_template.md, Makefile, README.md, dpc-web/app/views/public/_hero.html.erb
**Why**
When running builds with @embh and @DeirdreHolub we discovered some of the documentation is out of date.
- Adds a new `make start-app` target to simplify starting the application through Docker.
- Removes all references to Redis (killed in DPC-499 ☠️) 
- Fixes some inaccuracies.
- Fixes a typo in our PR template.
**Checklist**
=> README Documentation Update

dpc-common/pom.xml, pom.xml
**Why**
Our Maven project when imported into IntelliJ complained of several warnings and errors. This was due to missing Maven plugins and a plugin incompatibility.
Additionally, our dpc-common tests were not running because they were missing the dropwizard tests dependency.
- Adds missing Maven plugins.
- Updates a Maven plugin to be compatible with the other plugins.
- Adds missing test dependencies to dpc-common.
**Checklist**
=> Maven / IntelliJ Error Fixes

dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/ProviderDAO.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/ProviderEntity.java, src/test/EndToEndRequestTest.postman_collection.json
**Why**
A bug was reported where calling `DELETE` on a provider was resulting in a 500 error. This was because the deletion logic wasn't correctly remove attribution relationships. So our unit tests were passing, but the actual functionality was borked.
Simple tweak to iterate through the rosters linked to a given provider and remove all the attribution relationships and the rosters themselves.
Also verified that patient removal is working as well.
DPC-644: This ticket
**Checklist**
=> DPC-644: Fix provider deletion

.gitignore, .travis.yml, dpc-test.sh, package-lock.json, package.json
**Why**
We ran into some issues with running Postman tests on various machines, which seems related to running with an older version of Node. Basically, we need a proper method for locking and tracking our javascript dependencies.
Added a root package.json file to track our Newman dependencies.
Restrict node versions to 0.12 or higher.
Cache node modules for both dpc-web and newman.
DPC-679: This ticket
**Checklist**
=> DPC-679: Add package.json file for Postman dependencies

dpc-web/Gemfile, dpc-web/Gemfile.lock, dpc-web/app/controllers/internal/users_controller.rb, dpc-web/app/models/user.rb, dpc-web/app/views/internal/users/index.html.erb, dpc-web/config/routes.rb, dpc-web/spec/controllers/internal/users_controller_spec.rb, dpc-web/spec/fixtures/users.csv, dpc-web/spec/models/user_spec.rb
**Why**
Right now if Amy wants to get data about users and run her own queries or analytics in Excel, she has to request a download from developers. This feature lets her get what she needs herself.
Adds a link to the users index page for internal users to download a CSV of all users.
* Make this a separate controller action because we don't want to
apply search/filters that might be set in the index action (request
from Amy)
* Introduce Fake FS gem to mock the file system in tests so we're not
addign files to the test host when running
=> Add internal feature to download CSV of all users

dpc-api/src/main/resources/dev.application.conf, dpc-api/src/main/resources/prod-sbx.application.conf, dpc-api/src/main/resources/test.application.conf
**Why**
Per a discussion with pilot users, including the default HTTPS port in our file output response seems to be causing some issues. I'm assuming it has to do with corporate proxies, but since we're just being explicit about the default port, it seems fine to remove it. This was confirmed to solve the issue at the pilot site.
Removed the default HTTPS port (443) from the publicURL value in the application configs.
DPC-728
**Checklist**
=> DPC-728: Remove default HTTPS port from public export paths.

.github/pull_request_template.md
**Why**
To ensure we don't miss important dpc-ops changes, reminders for dpc-ops should be added to a PR template.
- Adds reminders to the PR checklist.
=> Add ops reminders to PR template

dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIService.java, dpc-api/src/main/java/gov/cms/dpc/api/core/Capabilities.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/BaseResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/DPCAttributionService.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/AbstractAttributionResource.java, dpc-common/src/main/java/gov/cms/dpc/common/utils/PropertiesProvider.java, pom.xml
**Why**
As we now have 3 environments that could have 3 different application versions deployed, we need a way to distinguish between them. We previously had a `/v1/version` endpoint, but it always returned the wrong value. This fixes that endpoint to return the build version of the application.
Updated our Properties Provider to output the application build version.
This is the first 7 characters of the git sha, followed by the build timestamp. The git value is provided by a maven [plugin](https://www.github.com/git-commit-id/maven-git-commit-id-plugin).
Both the Attribution service and the API service return this value correctly.
DPC-548
DPC-475: Add the build version to the Rails website.
**Checklist**
=> DPC-548: Add build version to application

dpc-api/src/main/resources/prod-sbx.application.conf
**Why**
I fat fingered the publicURL, it should end with /api rather than /v1. This means progress and download url's won't work correctly.
Fixed the publicURL to be correct.
Shame.
**Checklist**
=> Hotfix: Fix publicURL root for prod sbx.

Makefile, README.md, docker-compose.base.yml, docker/Dockerfiles/Dockerfile.base, dpc-aggregation/docker/entrypoint.sh, dpc-api/docker/entrypoint.sh, pom.xml
**Why**
Rather than installing common dependencies via each service's `entrypoint.sh`, we want to build a baseline image with said dependencies that individual service images can be based on.
Assuming the base image changes infrequently, this should mean marginally faster build times for individual services. It also reduces external requirements for services to start successfully.
- Added `docker-compose.base.yml` and `docker/Dockerfiles/Dockerfile.base`
- `Dockerfile.base` builds from the `openjdk:11-jdk-slim` (same that was previously used in `pom.xml` as the base for jib builds)
- Moved `apt-get` commands out of api and aggregation `entrypoint.sh` files
- Added `make docker-base`, made `docker-base` part of `make ci-app` target to ensure the base image is available …
=> DPC-653: Create custom Docker image for services

dpc-api/src/main/java/gov/cms/dpc/api/tasks/GenerateClientTokens.java
**Why**
The Website uncovered a bug where we weren't Base64 encoding the Golden Macaroon. Which makes it awkward and error prone to pass around as a string.
Base64 the golden macaroon
Base64 the golden macaroon
DPC-750: This ticket
**Checklist**
=> DPC-750: Encode golden macaroon as a Base64 String

.gitignore, Makefile, src/test/smoke_test.yml
**Why**
The smoke test is currently failing in Jenkins. These changes attempt to correct this issues with running the smoke test.
* Removes failure time constraint from Taurus passfail module.
* When tests were quickly failing, like is in the case of DEV due to BFD peering, the failure scenario was not being triggered.
* Adds a prompt when running local smoke tests to ensure authentication is enabled.
* The API requires a token to derive the organizationID that is sent to the attribution server. If authentication is disabled, the API sends an empty organizationID to the attribution server and the tests fail.
* Links with https://github.com/CMSgov/dpc-ops/pull/69 to re-install virtualenv on Jenkins.
**Checklist**
=> Resolve Smoke Test Issues

Makefile
**Why**
The smoke tests are not running on Jenkins because the SmokeTest class is not compiled.
* Adds a make target to build the application without tests and no docker images (for fast compiling). This will be used in dpc-ops change.
**Checklist**
=> Add a make target to build the smoke tests

dpc-api/src/main/java/gov/cms/dpc/api/tasks/GenerateClientTokens.java, dpc-macaroons/src/main/java/gov/cms/dpc/macaroons/MacaroonBakery.java
**Why**
We discovered that the Ruby Macaroons library does not support V2 encoded Macaroons. Which is annoying, but manageable. That means we need to generate the appropriate Macaroons in the API services.
This is required by #363 
Updated the GenrateClientTokens task to generate V1 binary encoded Macaroons, rather than V2 JSON.
DPC-673
**Checklist**
=> DPC-763: Generate V1 encoded Golden Macaroons

dpc-api/src/main/java/gov/cms/dpc/api/auth/jwt/JwtKeyResolver.java, dpc-api/src/main/java/gov/cms/dpc/api/cli/tokens/TokenList.java, dpc-api/src/main/java/gov/cms/dpc/api/converters/PublicKeyDeserializer.java, dpc-api/src/main/java/gov/cms/dpc/api/entities/PublicKeyEntity.java, dpc-api/src/main/java/gov/cms/dpc/api/jdbi/PublicKeyDAO.java, dpc-api/src/main/java/gov/cms/dpc/api/models/CollectionResponse.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractKeyResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractTokenResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/KeyResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/TokenResource.java, dpc-api/src/main/java/gov/cms/dpc/api/tasks/ListClientTokens.java, dpc-api/src/test/java/gov/cms/dpc/api/APITestHelpers.java, dpc-api/src/test/java/gov/cms/dpc/api/AbstractSecureApplicationTest.java, dpc-api/src/test/java/gov/cms/dpc/api/AuthenticationTest.java, dpc-api/src/test/java/gov/cms/dpc/api/auth/jwt/BackendServicesAuthTest.java, dpc-api/src/test/java/gov/cms/dpc/api/auth/jwt/JWTUnitTests.java, dpc-api/src/test/java/gov/cms/dpc/api/auth/jwt/JwtKeyResolverTests.java, dpc-api/src/test/java/gov/cms/dpc/api/cli/TokenTests.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/KeyResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/OrganizationResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PatientResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PractitionerResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/TokenResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/validations/ProfileTests.java, dpc-web/app/views/pages/reference.md
**Why**
Work on #370 revealed a bug in our public key handler code where the JWTKeyResolver was expecting key labels to be unique, but that constraint was not enforced in the database. This meant that key labels have to be unique within the _environment_ rather than just the org, which was no good. That was a problem that turned out to have a solution that made things much, much better.
Also, @switzersc-usds pointed out that it's brittle to return raw arrays from REST methods and that we should be wrapping them in order to avoid situations in the future where we need to make a breaking change to the array structure.
Public keys are now handled by their unique UUID key ids, rather than labels. This makes things MUCH less error prone and avoids the issue of having to rely …
=> DPC-784: Fix public key IDs

dpc-web/app/views/shared/internal/_sidenav.html.erb
**Why**
The providers left nav dropdown should use the `current_class` when viewing organizations 
=> use current class in providers menu when org is selected

dpc-api/src/main/java/gov/cms/dpc/api/converters/BakeryKeyPairDeserializer.java, dpc-api/src/main/java/gov/cms/dpc/api/converters/BakeryKeyPairSerializer.java, dpc-api/src/main/java/gov/cms/dpc/api/tasks/GenerateClientTokens.java, dpc-api/src/main/resources/local.application.conf, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java, dpc-testing/src/main/java/gov/cms/dpc/testing/APIAuthHelpers.java, src/main/resources/keypair/bakery_keypair.json
**Why**
Smoketests were failing hard in dev. There were a couple of reasons for this. But most of them were pretty simple to address.
Confirmed passing locally, confirmed passing when I addressed the key pair issue happening in dev.
Disables strict SSL checking, so we can run our tests against the internal ALBs and in Dev, which doesn't have a DNS record yet. We had to manually override the SSL Context in the tests, but that wasn't too terrible.
Fixed bad serialization of Bakery Keypairs, they were double base64 encoded.
Likewise, fixed double encoding of V1 binary macaroons, which are automatically base64 encoded.
**Checklist**
=> Fix failing smoke tests in dev.

src/test/dev.smoke_test.yml
**Why**
We're still having issues running the smoke tests in DEV due to the dev.dpc.cms.gov DNS entry not existing yet. We came up with the solution to allow the smoke tests to run over HTTP via the internal load balancer.
* Uses the internal ALB to run smoke tests: https://github.com/CMSgov/dpc-ops/pull/78
**Checklist**
=> Hotfix: Use the internal ALB for smoke tests

README.md, docker-compose.yml
**Why**
As we've been developing the website, @switzersc-usds has run into a number of issues that were tracked back to having the full authentication disabled by default in the docker containers.
While this is the required configuration for the Postman tests, it breaks functionality when working with multiple organizations. Previously, you had to modify a config file and rebuilt, in order for the auth to come back up.
Added an environment variable to Docker compose which allows enabling full authentication on the API service. `AUTH_DISABLED=false`
The default is disabled, but now we can easily switch it.
This ticket is pretty much required by #379 
DPC-808
**Checklist**
=> DPC-808: Add environment variable overriding to Docker containers

dpc-web/db/seeds.rb
**Why**
Right now when we are developing the app, if we need to reset the database, we have to go through the process of creating users and organizations all over again. 
This PR adds seeds that create an assigned user and an unassigned user, and the unassigned user also has a tag. This should be enough for getting basic dev up and running for UI changes or QA. 
Adds seeds. The seeds file gets run whenever you run `rails db:reset` in terminal.
=> Add some simple DB seeds to speed up development

src/test/test.smoke_test.yml
**Why**
The location of `test` env admin endpoint has changed.
Updates `test/test.smoke_test.yml` with the new location.
=> Update admin_url in test env smoke test config

dpc-consent/src/test/java/gov/cms/dpc/consent/jobs/SuppressionFileImportTest.java, dpc-consent/src/test/resources/synthetic-1800-files/copy/.gitignore
**Why**
The tests for the 1-800-MEDICARE ETL involve importing synthetic files. Because the ETL cleans up the import directory, the synthetic files need to be copied before the tests are run to preserve the originals. A `/copy` directory with only a `.gitignore` file was created for that purpose, but the `.gitignore` file ends up deleted after tests run, causing a bit of a mess when looking at changes in Git.
The `/copy` directory in `src/test/resources/synthetic-1800-files` is now created and deleted in the testing process.
[DPC-824](https://jiraent.cms.gov/browse/DPC-824)
**Checklist**
=> DPC-824: Fix fragile test strategy for synthetic 1-800 files

dpc-queue/src/main/java/gov/cms/dpc/queue/DistributedBatchQueue.java, dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobQueueBatch.java, dpc-queue/src/test/java/gov/cms/dpc/queue/models/JobQueueBatchTest.java
**Why**
We are finding cases of aggregator jobs that fail into a status of queued with the aggregatorID still set. This is an invalid state, and leads to further issues in the application.
The issue turned out to be the stuck batch logic. It was resetting the status without resetting the aggregatorID (or clearing files, which could have led to a separate issues). Both of those issues have been fixed and tests were written to verify.
The fact that the stuck batch logic was triggering is concerning, so I added additional logging as well for us to hopefully track down the reason these batches get stuck. We had a ton of issues with deployments lately, so it could be related to those, but I would not be surprised if there are more cases that lead to stuck batches.
**Choices …
=> DPC-814: Fix invalid job state

dpc-web/app/assets/javascripts/application.js, dpc-web/app/assets/javascripts/components/_modals.js, dpc-web/app/assets/javascripts/components/navbar.js, dpc-web/app/assets/javascripts/utils/_trap-focus.js
**Why**
For keyboard users, whenever a modal, flyout or any other "top layer" element is enabled, the focus state should be confined to that element. Otherwise, the focus state is lost. 
In addition, when that element is triggered, the focus state should also be moved to the close button for that element in the event that it was accidentally opened.
- Added a javascript utility to trap focus
- Updated modal js so that focus state is transferred to the close button when it is opened
The keyboard navigation should function as such:
A JS utility is generic and can be used in a number of different instances.
=> trap focus in modals, dialogs, etc.

dpc-web/app/services/api_client.rb
**Why**
Dev env has some cert issues and we want to skip past that during some testing.
Use env var to determine whether to verify ssl cert of API.
=> Do not verify cert in some envs

dpc-web/app/services/api_client.rb, dpc-web/spec/features/internal/organization_management/creating_and_updating_organizations_spec.rb, dpc-web/spec/services/api_client_spec.rb, dpc-web/spec/services/organization_registrar_spec.rb
The API requires application/fhir+json for FHIR endpoints. The web app
hits one FHIR endpoint right now, organization $submit.
Also clean up some styles in the tests.
=> Use fhir media type for organization API calls

dpc-common/src/main/java/gov/cms/dpc/fhir/validations/dropwizard/FHIRValidationModule.java, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java, src/test/smoke_test.yml
**Why**
A user reported in the Google group that they were experiencing issues with the validator rejecting resources because it was associating them with an incorrect profile.
This issue occurred previously and is related to the fact that none of the HAPI validator classes are thread-safe. I had thought it was fixed, but apparently not.
In addition, our smoke tests are passing even though the validator was throwing a 422 exception.
Updated the smoke tests to _hopefully_ improve error handling, we're now throwing errors from the main `SmokeTest` class, rather than deeper in the helper utils.
Also, staggered the startup time so the tests ramp up a bit slower and hopefully surface more threading and resource issues.
The SmokeTests now use FHIR creations when uploading …
=> DPC-849: Fix thread safety issue with HAPI Validator

src/main/resources/SmokeTest.jmx
**Why**
Smoke tests do not appear to be submitting the correct patient IDs form DPR environment, we'll need to investigate this further.
* Passes the config files through the .jmx file. Somehow I missed this in the original PR.
DPC-859
**Checklist**
=> DPC-859: Smoke Tests are submitting incorrect patient IDs

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java, src/test/smoke_test.yml
**Why**
As we've been in the perennial debug loop for our JMeter tests, I made a couple of small tweaks to make life better.
Reduced the test ramp-up time from 120s to 60s, this was a change that I missed on an earlier branch, still catches the threading issues but makes the tests run a bit quicker.
Improved the error message when an export job completes but has error outcomes.
Updated the `done` handling in the export job monitoring. Now, if a non-202 status is returned we check to see if it's an error response and if so, parse out the error as a string.
=> Smoke test cleanups

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java
**Why**
Adds some better logging for some failure situations were seeing with the smoke tests.
* Adds the groupId to the exception message, to better track down the exact export having issues
* Outputs the raw response body on a JobCompletionModel parsing failure
**Checklist**
=> Smoke Test Logging Improvements

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java
**Why**
More terrible errors from the smoke tests
Pulled out the hammer, `EntityUtils.readString()`
=> Update status handling to pull out the response code and error string

dpc-web/app/views/client_tokens/show.html.erb
**Why**
Needed the word "it"
Added "it"
Decided proper grammar was better
=> add missing word to the token alert

dpc-web/app/assets/stylesheets/components/_navbar.scss
**Why**
Flash messages were covering parts of the nav bar dropdown. 
Updated CSS to the topnav fixes the issue
Applied a z-index to the topnav dropdown
=> add z-index to topnav__dropdown

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java, dpc-web/app/controllers/application_controller.rb, dpc-web/app/models/user.rb, dpc-web/app/views/devise/registrations/new.html.erb, dpc-web/spec/factories/users.rb, dpc-web/spec/features/registration/new_user_signs_up_for_account_spec.rb, dpc-web/spec/models/user_spec.rb
**Why**
We're not saving number of providers when users register. The param needed to be added to the devise params in Application Controller from when I renamed this column.
Updated allowed devise params. Changed validation to require number be greater than 0 (not greater than or equal to).
See commit messages.
DPC-850
=> DPC-850: Bugfix - Save number of providers on registration

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/TokenResource.java, dpc-api/src/test/java/gov/cms/dpc/api/auth/jwt/JWTUnitTests.java, dpc-testing/src/main/java/gov/cms/dpc/testing/APIAuthHelpers.java
**Why**
@embh reported an issue where the SMART scopes were separated by a semi-colon, rather than a period, per the docs and the specs.
Updated internal checks and tests to account for new delimiter.
DPC-865
**Checklist**
=> DPC-865: Correct scopes to match SMART spec and documentation

dpc-api/pom.xml, dpc-smoketest/pom.xml, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java, pom.xml, src/main/resources/SmokeTest.jmx, src/test/smoke_test.yml
**Why**
We want to run smoke tests against organizations that already exist, so we can test that the website security works.
Added custom parameters to smoke tests, which allow us to specify our org id, client_token, private key path, etc. Here they are:
```javascript
organization-id: "{organization UUID}"
client-token: "{client_token}"
private-key: "{path to private key}"
```
You can find them in `src/test/resources/smoke_test.yml`, the empty values cause an organization to be created automatically.
It's a giant ball of hot garbage, but it works, and we need to rework the smoke tests anyways, so this should be ok.
=> Smoke test existing organizations

dpc-web/app/views/dashboard/_assigned_content.html.erb, dpc-web/app/views/dashboard/_unassigned_content.html.erb, dpc-web/app/views/pages/faq.html.erb, dpc-web/app/views/public/home.html.erb
**Why**
Need to modify some of the of the copy to include references to the sandbox
- Landing page
- FAQs
- Dashboard
No tickets, but the copy is in this Confluence doc: 
https://confluenceent.cms.gov/pages/viewpage.action?spaceKey=DAPC&title=Updates+to+screen+text+after+token+changes
Added all content except the updates under:
- Text for the top of the screen when an organization is assigned but no NPI or vendor (added in other branch)
- When editing an organization, the NPI field can have help text (added in other branch)
- Developer Documentation Updates (not sure where to place)
- OpenAPI Documentation (not sure where to place)
=> content updates

dpc-api/src/main/resources/prod-sbx.application.conf, src/test/prod-sbx.smoke_test.yml
**Why**
Tweaks for prod-sbx deployment.
* Updates the smoke tests to use the newly deployed internal ALB in prod-sbx
* Fixes an incorrect configuration of the API URL for prod-sbx
**Checklist**
=> Smoke test config for prod-sbx

dpc-web/app/models/organization.rb
**Why**
From @amgleason: 
> Hey there is kind of a critical bug i found in test. if I go as an admin user and create an org, it is saying the null NPI is "not unique". so it won't let me save it without an NPI. Shelby had put in a fix to not require it when saving, but it is broken. assuming this isn't something you can fix in her absence?
Updated the `organization` modal to allow blank in its uniqueness rule.
-  DPC-871
=> except null or blank npi from uniqueness

dpc-api/src/main/java/gov/cms/dpc/api/auth/TokenLoggingFilter.java, dpc-api/src/main/resources/META-INF/services/io.dropwizard.logging.filter.FilterFactory, dpc-api/src/main/resources/application.conf
**Why**
We've noticed that client_tokens are being logged into CloudWatch, while not immediately useful in and of themselves, they are one part of our two-phased API auth, so they definitely should not be in the log output.
Dropwizard has this nifty mechanism for filtering out log events that we don't want. Which we can use to ensure that the request/response of our `Token/auth` endpoint is never logged. Added a custom `FilterFactory` which simply ignores any log events coming from the `Token/auth` endpoint. Internal log messages are still passed along, as is, by the actual request/response logging is disabled.
We can add additional filters as we go along, to ensure we're not spamming ourselves with too many issues. (e.g. healthchecks)
Manually verified …
=> DPC-873: Add custom logging filter to avoid logging client_tokens

dpc-web/app/views/layouts/mailer.html.erb
Leftover maybe from a copypasta job. This PR gets rid of MC template
tags and links. Adds unsubscribe language instructing folks to email us.
=> Remove Mailchimp data from mailer template

dpc-web/app/views/internal/users/_form.html.erb
**Why**
Amy requested these be sorted alphabetically to make her workflow easier when assigning users to orgs.
Sort the orgs in the select menu on the user edit page alphabetically by name.
=> Sort orgs alphabetically for Amy

dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractOrganizationResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/OrganizationResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/OrganizationResourceTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/OrganizationDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/AbstractOrganizationResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/OrganizationResource.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/OrganizationResourceTest.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/OrganizationEntity.java, dpc-common/src/main/java/gov/cms/dpc/fhir/validations/ProfileValidator.java, dpc-common/src/main/java/gov/cms/dpc/fhir/validations/profiles/OrganizationProfile.java, src/main/resources/organization.tmpl.json, src/test/EndToEndRequestTest.postman_collection.json
**Why**
There should be a way to update Organization resources.
`PUT` methods added to dpc-api and dpc-attribution for submitting updates.
When updating an organization, no changes can be made to its endpoints. Any endpoint references provided in the request body will be ignored. The existing endpoint references will remain unchanged.
[DPC-307](https://jiraent.cms.gov/browse/DPC-307)
[DPC-857](https://jiraent.cms.gov/browse/DPC-857) will add create, update, and delete methods for Endpoint resources.
**Checklist**
=> DPC-307: Add update capability to Organization resources

.codeclimate.yml, dpc-web-test.sh, dpc-web/Gemfile, dpc-web/Gemfile.lock
**Why**
We want to get vulnerability warnings when a PR is opened.
Add bundler-audit to codeclimate config. For more info:
https://docs.codeclimate.com/docs/bundler-audit
https://github.com/rubysec/bundler-audit
=> Add bundler audit to CI

src/test/EndToEndRequestTest.postman_collection.json
In the Postman test for updating organizations, the number of endpoints cannot be assumed to be the same in every environment. This PR removes that expectation.
=> Remove inconsistent Postman test expectation

dpc-web/app/views/pages/reference.md
**Why**
At the FHIR connectathon we had a nightmare of a time getting an organization onboarded, it turns out, it was mostly documentation issues.
Fix the _client_assertion_ typo in the curl example.
Increase the required key length spec to 4096.
**Checklist**
=> Fix auth misinformation in reference.md

dpc-web/Gemfile, dpc-web/Gemfile.lock
**Why**
We don't use this so let's prune it. 
Remove bootstrap gem. 
Unnecessary. I did a quick click-through locally to confirm no UI changes. We never included the bootstrap assets in the app/assets dir so never even loaded them. 
**Checklist**
=> Remove Bootstrap: We are not using it

dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractEndpointResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/EndpointResource.java, dpc-api/src/test/java/gov/cms/dpc/api/APITestHelpers.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/EndpointResourceTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/EndpointDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/OrganizationDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/AbstractEndpointResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/EndpointResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/OrganizationResource.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionTestHelpers.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/EndpointResourceTest.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/OrganizationResourceTest.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/EndpointEntity.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/OrganizationEntity.java, dpc-common/src/main/java/gov/cms/dpc/fhir/converters/entities/EndpointEntityConverter.java, dpc-common/src/main/java/gov/cms/dpc/fhir/validations/profiles/EndpointProfile.java, dpc-testing/src/main/java/gov/cms/dpc/testing/OrganizationHelpers.java, dpc-testing/src/main/java/gov/cms/dpc/testing/factories/OrganizationFactory.java, src/test/EndToEndRequestTest.postman_collection.json
**Why**
Endpoints can be created as part of an Organization or read directly, but cannot be created separately, updated, or deleted.
This branch adds create, update, and delete operations for Endpoint resources in dpc-attribution and dpc-api.
[DPC-857](https://jiraent.cms.gov/browse/DPC-857)
**Checklist**
=> DPC-857: Add create, update, and delete operations for Endpoint resources

dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIModule.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractOrganizationResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/OrganizationResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/OrganizationResourceTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/ProviderDAO.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/OrganizationResourceTest.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PatientResourceTest.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PractitionerResourceTest.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/OrganizationEntity.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/ProviderEntity.java, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java
**Why**
Each time the smoke tests run (and on each iteration), they create a new organization to test with. This means that we have a bunch of fake organizations left over in the database which makes it difficult to see what actually is real or fake, plus it takes up space in the DB.
Added a teardown task to the JMeter test script which removes the organization when the test run terminates, regardless of whether or not the test passed or failed.
This revealed some issues with our current org deletion logic which meant we couldn't actually clean anything up.
I updated some of the Hibernate entities to ensure that they cascade deletions correctly, also verified that removing patients does not remove any of the groups they're a part of, it just removes them from the member …
=> DPC-585: Have smoke tests cleanup after themselves

dpc-web/app/views/pages/reference.md
**Why**
A couple more issues cropped up in the documentation, a user was trying to execute one the access token request using the curl command, and it wasn't working as expected.
- The JWT algorithm type is RS384, not RSA384
- The access token request needs to be completely wrapped in double quotes, and have the accept header set correctly.
**Checklist**
=> Update access token documentation

dpc-common/src/main/java/gov/cms/dpc/fhir/dropwizard/filters/FHIRRequestFilter.java, dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/filters/FHIRRequestFilterTest.java, src/test/EndToEndRequestTest.postman_collection.json
**Why**
On the Google Group, a user reported an issue where they were getting a weird exception when trying to submit their practitioners. It turned out to be due to our request filters accepting incorrect content types, but then it gets delegated to the Jackson parser which fails to deserialize it.
Improved the request checking in the `FHIRRequestFilter` class to verify that both the `Accepts` header and the `Content-Type` header are correct. Really, content-type is the most important one, because it's the one that determines which `MessageBodyReader` gets called, and we need it to correctly call our custom FHIR reader.
DPC-921: Reject non-FHIR requests to FHIR endpoints.
**Checklist**
=> DPC-921: Update request filters to reject non-FHIR content types

dpc-aggregation/docker/entrypoint.sh, dpc-aggregation/pom.xml, dpc-api/docker/entrypoint.sh, dpc-api/pom.xml, dpc-attribution/docker/entrypoint.sh, dpc-attribution/pom.xml, dpc-consent/docker/entrypoint.sh, dpc-consent/pom.xml, dpc-web/Gemfile, dpc-web/Gemfile.lock, dpc-web/config/newrelic.yml, pom.xml, src/main/resources/newrelic.yml
**Why**
We intend to use New Relic APM to monitor application performance (e.g., response times, throughput, end-user satisfaction metrics, error types and rates) for the suite of DPC services.
The New Relic agent has been added as a dependency to each service via the service's respective dependency manager (e.g., pom.xml for Java applications, Gemfile for the website).
At build time, the New Relic agent and associated configuration file (i.e., `newrelic.yml`) are included in the resultant Docker image.
Some notes on ops changes required to use the agent --
The New Relic agent requires environment variables set, including: `NEW_RELIC_LICENSE_KEY` and `NEW_RELIC_APP_NAME`.
For Java applications, static value of `/app/resources/newrelic.yml` for env var  `NEW_RELIC_FILE` …
=> DPC-247: New Relic APM for DPC services

dpc-common/src/main/java/gov/cms/dpc/common/consent/entities/ConsentEntity.java, dpc-common/src/main/java/gov/cms/dpc/fhir/converters/entities/ConsentEntityConverter.java, dpc-common/src/test/java/gov/cms/dpc/fhir/converters/entities/ConsentEntityConverterTest.java, dpc-consent/src/main/java/gov/cms/dpc/consent/DPCConsentService.java, dpc-consent/src/main/java/gov/cms/dpc/consent/cli/ConsentCommand.java, dpc-consent/src/main/java/gov/cms/dpc/consent/cli/ConsentCommands.java, dpc-consent/src/main/java/gov/cms/dpc/consent/cli/CreateConsentRecord.java, dpc-consent/src/main/resources/consent.migrations.xml, dpc-consent/src/test/java/gov/cms/dpc/consent/cli/ConsentCommandsTest.java
**Why**
Until we have our consent pipeline fully functional, including ACO OS integration, we need a way to manually opt-out patients if we receive notice from a pilot site, or CMS.
A CLI command has been added to create new consent records. The command has been added in such a way as to support additional commands, like list or delete.
- In order to know how a record was created --- manually or via an ETL import --- I added a source_code column. We wanted explicit identification of the import source to make audit trails and problem investigation easier.
- Added a custodian column to hold the organization id when the consent record was provided to DPC by a DPC provider organization.
DPC-821
List any additional tickets …
=> create consent command

dpc-aggregation/pom.xml, dpc-aggregation/src/main/resources/application.conf, dpc-api/pom.xml, dpc-api/src/main/resources/application.conf, dpc-attribution/pom.xml, dpc-attribution/src/main/resources/application.conf, dpc-consent/pom.xml, dpc-consent/src/main/resources/application.conf, pom.xml, src/main/resources/server.conf
**Why**
Logs are difficult to scan and search due to the current format, which complicates debugging.
This branch adds `dropwizard-json-logging` to format log output as JSON. General logging is configured in `server.conf`, and request logs are configured in individual applications' `application.conf` files.
[DPC-813](https://jiraent.cms.gov/browse/DPC-813)
Additional logging improvements will be made with [DPC-835](https://jiraent.cms.gov/browse/DPC-835).
**Checklist**
=> DPC-813: Improve log format

dpc-consent/pom.xml
**Why**
The fhir client needs to be available for the consent service to talk to the attribution service. Flipping it from test scope should do it.
Removed the test scope from the `hapi-fhir-client` jar.
**Checklist**
=> Hotfix: Make hapi-fhir-client available at runtime.

dpc-consent/src/main/resources/prod-sbx.application.conf, dpc-consent/src/main/resources/test.application.conf
**Why**
Another copy-paste error on my part, this should point the consent service to the test and dev DBs in AWS.
**Checklist**
=> Update consent configs to point to the correct database.

dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClient.java, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClientImpl.java, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/MockBlueButtonClient.java, dpc-bluebutton/src/test/java/gov/cms/dpc/bluebutton/client/BlueButtonClientTest.java, dpc-common/src/main/java/gov/cms/dpc/fhir/DPCIdentifierSystem.java, src/main/resources/server.conf, src/test/resources/bb-test-data/patient/20140000008325-bundle.xml
**Why**
Because rosters identify beneficiaries by MBI, DPC needs a way to obtain data from BFD with that identifier. This can be done by requesting Patient resources from BFD by hashed MBI.
Added `requestPatientFromServerByMbiHash()` to `BlueButtonClient`.
[DPC-908](https://jiraent.cms.gov/browse/DPC-908)
Additional tickets exist for hashing MBIs, setting up test data with MBI, and using the returned Patient to get the CCW bene ID for other resource requests (ExplanationOfBenefit, Coverage).
**Checklist**
=> DPC-908: Update DPC's BB client to support requesting Patient with hashed identifier 

dpc-attribution/src/test/java/gov/cms/dpc/attribution/scripts/AddMBIToPatients.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/scripts/GenerateRosters.java, src/main/resources/patient_bundle-dpr.json, src/main/resources/patient_bundle.json
**Why**
As we get ready to roll out MBI support, we need to update our test data to include the new identifiers.
Added a script to automatically update patient bundles with MBIs, from the sample CSV file provided by the BFD team.
Committed the MBI hash CSV to the repo, as we may find uses for it in the future.
Added both the hashed and un-hashed MBI value to the patient records, it may not be necessary to include the hashed value, it it's possible it would help improve data loading time in the future.
DPC-936
All the other MBI work to come.
**Checklist**
=> DPC-936: Add MBIs to sample beneficiaries

dpc-attribution/src/main/resources/migrations.xml, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClient.java, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClientImpl.java, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/MockBlueButtonClient.java, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/config/BBClientConfiguration.java, dpc-bluebutton/src/test/java/gov/cms/dpc/bluebutton/client/BlueButtonClientTest.java, dpc-bluebutton/src/test/resources/test.application.conf, dpc-common/src/main/java/gov/cms/dpc/common/entities/PatientEntity.java
**Why**
In order to request Patient resources from BFD by MBI, the MBIs must be hashed.
* Created `hashMbi()` in `BlueButtonClient`
* Updated attribution `patients` table to add `mbi_hash` column
[DPC-937](https://jiraent.cms.gov/browse/DPC-937)
Work is continuing on adding MBIs (Patient profile, retrieving bene ID by MBI before EOB and Coverage requests).
**Checklist**
=> DPC-937: Add MBI hashing support

dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClientImpl.java, dpc-bluebutton/src/test/java/gov/cms/dpc/bluebutton/client/BlueButtonClientTest.java, src/test/resources/bb-test-data/eob/20140000008325.xml, src/test/resources/bb-test-data/eob/20140000008325_10.xml, src/test/resources/bb-test-data/eob/20140000008325_20.xml, src/test/resources/bb-test-data/eob/20140000008325_30.xml, src/test/resources/bb-test-data/eob/20140000009893.xml
**Why**
Data provided by DPC cannot include substance abuse and mental health claims.
* Adds `excludeSAMHSA=true` on ExplanationOfBenefit requests to BFD
* `fetchBundle()` in `BlueButtonClientImpl` now accepts a `List` of criteria (`ICriterion` objects); if more than one is provided, it is added to the query with `and()`
[DPC-956](https://jiraent.cms.gov/browse/DPC-956)
**Checklist**
=> DPC-956: Modify BFD client to use excludeSAMHSA=true when making EOB requests

dpc-aggregation/docker/entrypoint.sh, dpc-api/docker/entrypoint.sh, dpc-attribution/docker/entrypoint.sh, dpc-consent/docker/entrypoint.sh
**Why**
We don't want NewRelic running when we do our migration and seed commands, as it slows everything down with its reporting and instrumentation.
Updated the Docker entrypoints to make the CMDLINE variable more flexible and only add in JACOCO and NR_AGENT when necessary.
DPC-970
**Checklist**
=> DPC-970: Update Docker entrypoints to limit NewRelic use

docker-compose.yml, dpc-test.sh
**Why**
Per one of our discussions with the web team, we'd like to change the defaults to always launch the application with auth enabled.
Updated both the docker-compose.yml and the dpc-test.sh to ensure auth is disabled when running the postman tests.
This will make `AUTH_DISABLED` default to `false` unless otherwise specified. This should make developing against the website and using the smoke tests a lot easier.
DPC-961
**Checklist**
=> DPC-961: Change Docker default to always enable auth.

dpc-web/db/migrate/20200204135210_fhir_endpoint_data_migration.rb, dpc-web/db/schema.rb
**Why**
In DPC-954 we refactored the relationships between FhirEndpoint and
Organization and RegisteredOrganization. Now, fhir_endpoints are associated with an organization's registered_organization record directly. This data migration updates
the existing data to match the new structure.
Data migration that should be run once to update the data in the rails app to associate existing fhir endpoints with their organization's registered organization. This will be run automatically on deploy as part of `rails db:migrate`. Tested locally.
This is a small, low-cost, one-time data change, so we decided to do this is a migration in the rails db. There are less than 100 records that need to change.
DPC-1016
DPC-1017 …
=> DPC-1016: Data migration to populate fhir_endpoints.registered_organization_id

README.md, dpc-web-test.sh, dpc-web/app/models/organization.rb, dpc-web/db/migrate/20200204190846_add_vendor_id_column_to_organizations.rb, dpc-web/db/schema.rb
**Why**
Breaking up the vendor workflow ticket into smaller, more manageable sized tickets. This was just adding a column to the `organizations` table.
I also fixed a line the DPC-APP's README.md file.
Added a column for vendor ids that will be created when an external user creates a vendor account. (The next ticket will be adding the generated id number to relevant accounts.)
Corrected the app's main README file to include the correct `docker-compose up` instructions.
`venid` to keep it short but recognizable and different from `npi` and `id` columns.
DPC 1010
Will continue with the vendor workflow ticket DPC-997.
**Checklist**
=> DPC-1010 Vendor Id Column

dpc-web/app/views/pages/reference.md
**Why**
We locked down our production API url this morning, and we have a link in our documentation that isn't pointing to sandbox.
**Checklist**
=> Hotfix: Point swagger links to sandbox (and fix typo)

dpc-common/src/main/java/gov/cms/dpc/fhir/dropwizard/handlers/FHIRHandler.java, dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/handlers/FHIRHandlerTest.java
**Why**
In our Splunk logs we've been seeing some `500` related to users submitting invalid FHIR resources to our endpoints. Currently, these errors get returned to the user as a generic 500 exception, rather than in a more useful format.
This is similar to the work in #582 as we're slowly purging the system of generic exceptions.
Updated the FHIRHandler to catch DataFormatExceptions and rethrow them as `400` errors with a message, rather than simply leaking the raw exception as a 500 error.
We need to do this because the custom FHIR exception handlers aren't loaded at this point in the request chain so we have to handle things manually.
Also updated the unit tests to fully cover the class.
DPC-1075
**Checklist**
=> DPC-1075: Catch and rethrow DataFormatException

dpc-api/src/main/resources/prod-sbx.application.conf
**Why**
The sandbox API is currently configured to use the production API URL. This is causing a number of problems with token creation.
The configuration URL of the sandbox API has been changed from `https://dpc.cms.gov/api` to `https://sandbox.dpc.cms.gov/api`.
This change will break token creation for users who were using the incorrect URL, but working URL. [In our documentation](https://dpc.cms.gov/docs#authentication-and-authorization) we say to use `https://sandbox.dpc.cms.gov/api/v1/Token/auth` for the aud claim, but this was never actually working in sandbox. Users had to use `https://dpc.cms.gov/api/v1/Token/auth` as the aud claim for token authentication to work.
**This is a change we will need to communicate to our Google Group.** It's going to …
=> Fix broken token creation in sandbox

dpc-web/config/newrelic.yml, src/main/resources/newrelic.yml
**Why**
In order to get under the account CU limit, we need to disable our distributed tracing support.
Disabled the `distributed_tracing` flag for all services.
This is the simplest way to remove the feature, in the future, we could add a JVM flag in prod-sbx and prod to re-enable.
DPC-1088: Enable distributed tracing in higher environments.
**Checklist**
=> Disable New Relic distributed tracing

dpc-aggregation/src/main/resources/dev.application.conf, dpc-aggregation/src/main/resources/prod-sbx.application.conf, dpc-aggregation/src/main/resources/test.application.conf
This amends https://github.com/CMSgov/dpc-app/pull/640 to set `bbclient.baseServerUrl` in the aggregation dev, test, and prod-sbx configuration files to environment variable `BFD_URL`.
=> Correct BFD server URL env var name in configuration files

dpc-web/app/services/api_client.rb
**Why**
Users could not disable sandbox access for organization (or delete orgs with sandbox access).
Changed the `delegated_macaroon` to `golden_macaroon`.
Using the admin `golden_macaroon` to bypass the credential requirements of the API.
DPC-1158
**Checklist**
=> DPC-1158: As an internal user I cannot disable sandbox access for an organization

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/AggregationEngineTest.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/BatchAggregationEngineTest.java
**Why**
From the ticket:
> We've seen NPEs on the subscriber at AggregationEngine:149. We can add a null check there, but it would be even better to determine how it is ending up null in the first place.
* Refactors the queue stopped check to not use the RxJava disposable as the queue stopped indicator (since it can be null in some cases), and instead use our more reliable thread-safe boolean.
* Refactors the main queue loop to address the following issues:
* Improved logging (now includes a trace for when items are being processed, and an output message when the queue stopped entirely)
* Sets the queue to a stopped state when it exits the processing loop for any reason
* This should not happen once we fix the root issue, but if this does happen again, the queue will now …
=> DPC-1171: Queue NPE fixes

dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobQueueBatch.java, dpc-queue/src/test/java/gov/cms/dpc/queue/DistributedBatchQueueTest.java
**Why**
Stuck jobs are failing with the exception:
```
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "batch_id" violates not-null constraint
```
* Adds a unit test to reproduce this issue
* Adds additional flags on the Hibernate relationship to instruct Hibernate how to delete the object during a cascade (https://stackoverflow.com/questions/25455280/hibernate-cascade-delete-for-one-to-many-call-sql-update-instead-of-delete)
DPC-1171: One of many fixes related to this issue
**Checklist**
=> Fix: Stuck jobs are unable to be restarted due to SQL constraint exception

dpc-queue/src/main/java/gov/cms/dpc/queue/DistributedBatchQueue.java, dpc-queue/src/test/java/gov/cms/dpc/queue/DistributedBatchQueueTest.java, dpc-queue/src/test/java/gov/cms/dpc/queue/QueueHealthTest.java
**Why**
Our existing health check that markes instances as unhealthy when the aggregator is not making progress on the job was not working. The query was a mix of native SQL and JQL, and didn't return what were testing for.
* Re-wrote the query using JQL
* Added unit tests testing the query both in health and unhealthy scenarios, in addition to our previous tests that asserted using mocks on the query
**Checklist**
=> Fix stuck batch health check not marking the instance as unhealthy

dpc-queue/src/main/java/gov/cms/dpc/queue/DistributedBatchQueue.java, dpc-queue/src/main/java/gov/cms/dpc/queue/JobQueueModule.java, src/main/resources/server.conf
**Why**
The queue health check still was not failing on a stuck job.
* The `aggregatorID` was not stable between injectors. Each time the `@AggregatorID` annotation was called, a new UUID was generated, so the health check'd ID didn't match the actual queues.
* Adds additional debug statements around the health check in the event the `aggregatorID` fix still does not resolve the health check issue.
* Remove the log level DEBUG configuration for `gov.cms.dpc.queue.DistributedBatchQueue` after we are confident the health checks are working.
**Checklist**
=> Queue Health Check Fix

dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionFHIRTest.java, dpc-common/src/main/java/gov/cms/dpc/fhir/FHIRExtractors.java, dpc-common/src/test/java/gov/cms/dpc/fhir/FHIRExtractorTests.java, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java, dpc-web/app/views/pages/reference.md, src/test/EndToEndRequestTest.postman_collection.json
**Why**
A Google Group user reported that a request for a `Group` with a `characteristic-value` parameter was returning a 500. DPC is expecting a format for that query parameter that does not match the FHIR spec. http://hl7.org/implement/standards/fhir/STU3/search.html#combining
The API no longer expects a composite `characteristic-value` parameter to always include pipes (`|`) to separate system and code. For example, `|attributed-to$|12345` was the expected format when each side had only a code and no system. It is now `attributed-to$12345`.
[DPC-1182](https://jiraent.cms.gov/browse/DPC-1182)
**Checklist**
=> DPC-1182: characteristic-value query parameter error

dpc-aggregation/src/main/resources/prod.application.conf, dpc-api/src/main/resources/prod.application.conf, dpc-attribution/src/main/resources/prod.application.conf, dpc-consent/src/main/resources/prod.application.conf
**Why**
We are attempting to bootstrap `prod`.
Need the appropriate `application.conf` files for `prod`.
It is unclear why these env vars can't be defined as part of `dpc-ops` (i.e., SSM).  To expedite the bootstrap process, a choice was made to align these files with the way the existing environments are configured.  
N/A
In the future, I'd image it would be best to deprecate these files and control variables via SSM.
**Checklist**
=> Create prod.application.conf file

dpc-web/config/database.yml
**Why**
When trying to deploy `dpc-web`, we saw this error:
```
YAML syntax error occurred while parsing /dpc-web/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected comment or line break while scanning a block scalar at line 26 column 13
```
This YAML syntax error is referring to the line that contains a password, which can contain any of these special characters: `!#$%&*()-_=+[]{}<>:?`
In YAML, the `>` character is a [reserved indicator](https://yaml.org/spec/1.2/spec.html#id2774228) and cannot start a string.
In this case, the current database password starts with `>`. This branch puts the ERB interpolation inside double quotes so that the YAML is valid after interpolation.
According to …
=> Use quotes around database password

dpc-web/config/database.yml
**Why**
This branch is a follow up from #740 which fixed the problem for only one line in `database.yml`. We now need to use single quotes around all other lines that interpolate `DB_PASS` so that the file is valid YAML.
* Adding single quotes around all interpolated passwords.
* The choice was made to put single quotes around anywhere a password is interpolated so that the file is valid YAML.
N/A
N/A
**Checklist**
=> Adding quotes around all password interpolations

dpc-api/src/test/java/gov/cms/dpc/api/FHIRSubmissionTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PatientResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/validations/ProfileTests.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/PatientResource.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionFHIRTest.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/jobs/ExpirationJobTest.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/OrganizationResourceTest.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PatientResourceTest.java, dpc-common/src/main/java/gov/cms/dpc/common/entities/PatientEntity.java, dpc-common/src/main/java/gov/cms/dpc/fhir/FHIRExtractors.java, dpc-common/src/test/java/gov/cms/dpc/fhir/FHIRExtractorTests.java
**Why**
DPC needs to validate that the values provided as identifiers within the `http://hl7.org/fhir/sid/us-mbi` system match the [MBI format](https://www.cms.gov/Medicare/New-Medicare-Card/Understanding-the-MBI.pdf).
Validation added to check MBI format in the `PatientEntity` and `FHIRExtractors`.
The pattern fits the MBI format for placement of letters and numbers, but in order to allow synthetic data, **does not** limit the letters or numbers that may be used.
There is a lot of room for improvement in API responses across the board. Rather than spending time setting up better responses for just this ticket, we should review as part of [DPC-878](https://jiraent.cms.gov/browse/DPC-878).
**Tickets Closed** …
=> DPC-1283: Patient resource input validation

dpc-web/spec/features/registration/new_user_signs_up_for_account_spec.rb, dpc-web/spec/spec_helper.rb
**Why**
There have been random rspec failures coming from the `new_user_signs_up_for_account_spec.rb` file. Particularly the `expect(page).to have_css('[data-test="my-account-menu"]')` check. This needed to be investigated so we dont experience random failures from our CI anymore.
It turns out a regex wasn't accounting for certain characters and cutting off the ctoken when we try to pull it out from the email. In particular, the `-` was not being accounted for (`\w` only accounts for `[a-zA-Z0-9_]`). I've also introduced running the rspec tests in a random order.
I updated the regex to just look for the first double quote delimiter and otherwise eat all characters hungrily. This should account for any weird characters devise is using in their token. …
=> Dpc 1369 fix rspec error

dpc-web/config/initializers/devise.rb
**Why**
To improve security, have the users automatically need to sign back in when a password changed or reset.
Changed devise's default to keep the session from `true` to `false`.
[DPC-859](https://jiraent.cms.gov/browse/DPC-859)
N/A
**Checklist**
=> DPC-859: Changing the password should invalidate the session & force login

dpc-smoketest/pom.xml
Reverts CMSgov/dpc-app#770
Why: Smoke tests break!  (Why didn't they break in Travis?)
=> Revert "Bump jackson-datatype-jsr310 from 2.10.3 to 2.11.0"

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/EndpointResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/EndpointResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/OrganizationResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PatientResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PractitionerResourceTest.java, dpc-common/src/main/java/gov/cms/dpc/fhir/dropwizard/handlers/FHIRHandler.java, dpc-common/src/main/java/gov/cms/dpc/fhir/validations/ProfileValidator.java, dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/handlers/FHIRHandlerTest.java
**Why**
Ensure and demonstrate that DPC API's create operations return appropriate error responses.
Tests were added to show that appropriate error responses are returned from API create operations for Endpoint, Group, Organization, Patient, and Practitioner resources. Some logic was updated accordingly.
Information about create operation error status codes may be found at https://www.hl7.org/fhir/http.html#create.
> Common HTTP Status codes returned on FHIR-related errors (in addition to normal HTTP errors related to security, header and content type negotiation issues):
> 
>     400 Bad Request - resource could not be parsed or failed basic FHIR validation rules
>     404 Not Found - resource type not supported, or not a FHIR end-point
>     422 Unprocessable Entity - …
=> DPC-92: Responses for create operations

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java, dpc-testing/src/main/java/gov/cms/dpc/testing/APIAuthHelpers.java
**Why**
Our smoke tests did not run in our neo prod environment because there are no DNS entries for the hosts. The smoke test code assumes that urls for posting and the domain name are the same, which is not the case in the prod environment right now.
There are two operations in the code that needed attention:
1) tokens must be created using the domain name
2) the job location returned by an $export request must be converted from domain -> 
This code is a temporary bypass until we have completed our testing and are ready to make DNS changes.
I assume we will remove these bypasses when we make the DNS changes.
**Checklist**
- [ x ] All tests are passing via `make ci-app` (app change) and `make …
=> Get smoke test working in prod env

dpc-common/src/main/java/gov/cms/dpc/fhir/dropwizard/handlers/exceptions/HAPIExceptionHandler.java
the operation outcome is not guaranteed to be set according to HAPI base client
Null check
Since HAPI Base Client does not guarantee setting of the operationOutcome, will need to add a null check and produce an empty operationOutcome with the log id
N/A
Would like to know if it's possible that PII is in our exceptions since the new code takes the message from the exception and puts it into the operation outcome
=> DPC-442 Feature: null check in hapi exception handler

dpc-web/Gemfile.lock, dpc-web/config/initializers/redis.rb
Due to a recent Redis update, running the sidekiq/rails server has resulted in a warning:
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists? instead`
This is affecting our splunk forwarder and causing issues. The culprit of the warning is Sidekiq as it is, as the warning describes, using an old from of the `exists` method.
Update Sidekiq to version `6.1`. The newest version has updated this functionality.
Simple version bump. We can also remove the `redis.rb` file since it holds no pertinent information anymore.
N/A
Running both the sidekiq server and the rails server locally with the new sidekiq version has verified the warning is gone. …
=> Remove redis exists warning

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/ResourceFetcher.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackServiceImpl.java, dpc-common/src/main/java/gov/cms/dpc/common/MDCConstants.java
- Add jobID, batchID and patient MBI Hash to MDC for logs
- Log lookBack stats for each patient
Make sure MBI Hash is not PII
```
{"level":"INFO","logger":"gov.cms.dpc.aggregation.engine.AggregationEngine","thread":"RxComputationThreadPool-1","message":"Processing job, exporting to: /tmp.","mdc":{"jobID":"c925679a-ff7f-4a33-862c-14e46388b3d5","batchID":"1de6b574-5bd5-4b57-8a2f-a5a3597d1206"},"timestamp":"2020-07-09T14:44:35.087+0000"}
{"level":"INFO","logger":"gov.cms.dpc.aggregation.service.LookBackService","thread":"RxComputationThreadPool-1","message":"LookBack stats eobWithinLookBackLimit true, eobContainsProvider true, eobRelatedToOrganization true, eobMonthsDifference 2, hasClaim true","mdc":{"batchID":"1de6b574-5bd5-4b57-8a2f-a5a3597d1206","jobID":"c925679a-ff7f-4a33-862c-14e46388b3 …
```
=> DPC-518 log lookback stats, add jobid, batchid and patient mbi hash to mdc

dpc-api/src/main/java/gov/cms/dpc/api/APIHelpers.java, dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIModule.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractPatientResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PatientResourceTest.java, dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java, ig/ig.json, ig/source/resources/implementationguide/cms-dpc-ig.xml, ig/source/resources/implementationguide/ig-new.json, ig/source/resources/implementationguide/ig-new.xml, ig/source/resources/operationdefinition/dpc-patient-everything.json, src/main/resources/bb-test-data/eob/-19990000002208_40.xml, src/test/EndToEndRequestTest.postman_collection.json
This restores the `/Patient/$everything` endpoint that was previously added in PR #894 and reverted in #901 .
No security implications. All data transmitted was already provided by DPC through other endpoints.
Integration tests are included, in PatientResourceTest and the Postman EndToEndRequestTest collection.
A deployment of this branch to dev can be found in Jenkins, `Full Deploy and Release` job 676. The test errors we saw last time are no longer occurring.
Any
=> DPC-551: Restore /Patient/$everything

dpc-aggregation/src/main/resources/local.application.conf
In the original pull request for adding `/Patient/$everything`, the claims look back date for tests was adjusted by one month to ensure a certain number of results. This was missed when it was restored and is corrected with this PR.
=> Patient/$everything restoration (DPC-551) addendum: Adjust look back date for tests

.gitignore, Makefile, README.md, application.local.conf.sample
When running `mvn clean install` locally as the README indicates, the tests fail because the decrypted environment variables are not available to Maven.
- add new `make maven-config` command in order to turn the decrypted environment variables into Maven flags stored in `.mvn/maven.config`
- add `.mvn/` to `.gitignore` to avoid tracking and committing secrets
- update README for clarity
The most important change here is the new `make` command which uses bash to read the `local.env` key-value pairs and convert them to `-D*` flags which are stored in a `maven.config` file and then accessible by Maven. Specifically, the command first creates a `.mvn` directory if it doesn't already exist. Then, it truncates or creates a `maven.config` file, depending on its existence. Finally, it reads the …
=> DPC-542 Feature: Add new `make` command to simplify local manual build process

dpc-smoketest/pom.xml
This reverts commit 7a304d5229447375e22ed07b6d7eccb42e84329b, which breaks the smoke tests.  Ticket [DPC-607](https://jira.cms.gov/browse/DPC-607) has been created to make code changes necessary for this upgrade.
This is a reversion to a known good state of the code.
Any concerns?
=> Revert "Bump jackson-datatype-jsr310 from 2.10.3 to 2.11.2 (#945)"

dpc-aggregation/src/main/resources/prod.application.conf, dpc-api/src/main/resources/prod.application.conf, dpc-attribution/src/main/resources/prod.application.conf, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/BlueButtonClientImpl.java
We had originally intended to enabled DEBUG logging in prod in order to see a specific debug log for troubleshooting, due to PII concerns with other unrelated debug logs we have decided against enabling DEBUG logs. 
- Revert to INFO log levels for "gov.cms.dpc" loggers (API, Attribution, and Aggregation)
- Log the required log statement in bbclient as INFO 
- Reverted to INFO log levels for "gov.cms.dpc" loggers (API, Attribution, and Aggregation)
- Logged the required log statement in bbclient as INFO instead of DEBUG
We will be logging the MBI hash.
It was mentioned that the MBI hash is PII/psuedo-PII but only linkable not directly linked.
logger.info("Attempting to fetch patient with MBI hash {} from baseURL: {}", mbiHash, client.getServerBase());
- [ X] requires more information or …
=> DPC-628-Reverted back to INFO log level in prod. Changed a bbclient log from DEBUG to INFO

dpc-testing/performance/key.go, dpc-testing/performance/main.go, dpc-testing/performance/token.go
DPC is setting up a basic performance test suite for attribution endpoints.
This pull request adds performance tests for the /Token endpoints.
Tests include:
* POST /Token
* POST /Token/validate
* POST /Token/auth
* GET /Token
* GET /Token/{id}
* DELETE /Token/{id}
The new tests are in token.go, and the existing /Key endpoint tests have been moved into key.go.
This contains tests only. No security impacts.
Any
=> DPC-732: Basic performance test suite for /Token endpoints

dpc-testing/src/main/java/gov/cms/dpc/testing/APIAuthHelpers.java
Sonar scans picked up a few security vulnerabilities in the testing API Auth Helpers class that needed to be fixed.
- Instead of always returning `true` when verifying the host name, check if the name matches the SSL session's peer host
- Specify `TLSv1.2` as suggested by SonarQube
- Add the possibility of throwing a `CertificateException` as required by the overridden methods of `X509TrustManager` See details below for more on this change.
The first two changes above were suggested by SonarQube, meet the guidelines, and still allow the smoke tests to pass. For the `CertificateException` change, however, this is a bit of a workaround. SonarQube wants the `X509TrustManager` to throw an exception when there is a failed certificate check, which is completely reasonable outside of testing. …
=> DPC-643: fix sonar vulnerabilities in `dpc.testing.APIAuthHelpers`

dpc-testing/src/main/java/gov/cms/dpc/testing/APIAuthHelpers.java
Previous fix caused the smoke tests to fail on `test` and then later on `dev`.
- essentially don't check certificates but add in the unreachable possibility of throwing an error so that Sonarqube approves
Since it is still unclear what certificates, if any, are being passed around in what environments during the smoke tests, the present fix is to do nothing regardless the number of certificates. The `CertificateException` should never be thrown, but it is currently there to make Sonarqube happy. This is really not doing anything different than the original empty methods.
A ticket exists already to look into whether we should be handling certificates differently during testing.
- deployed to dev and smoke tests passed
- ran smoke tests locally and they passed
- built the docker image and …
=> DPC-643 fix: modify cert check to avoid smoke test failures

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
Swagger docs were not validating due to the following issues:
- Duplicate param for `Prefer` header in `GroupResource`
- `Patient/$everything` endpoint missing a type definition on the `X-Provenance` header (should be `string`)
- Remove duplicate header in `GroupResource` using `ApiParam(hidden = true)`
- Add `type = "string"` to `X-Provenance` header
The generated `swagger.json` now validates correctly without any errors on `editor.swagger.io`
Any
=> DPC-751 fix: update params for swagger validation

dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractGroupResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceUnitTest.java
Reverts CMSgov/dpc-app#1091
The `FHIRRequestFilter` is already correctly validating that the `Accept` header is a MediaType of `application/fhir+json`.
The smoke tests were passing this requirement before the more strict requirements of the PR to be reverted here.
The diagnostic tool seems to have avoided passing through the filters.
=> Revert "DPC-554 fix: Require `Accept` header"

dpc-web/public/jwt/jwt.html
Same change as https://github.com/CMSgov/dpc-static-site/pull/11
The JWT Tool was not adding an `aud` claim to the JWT that was generated.
In addition, the `aud` claim is environment-specific, so there needed to be a way to select which environment to use when generating the JWT.
- added a select for the environment: `Sandbox` or `Production`
- added `aud` claim to JWT generator
The URL in the `aud` claim includes the environment. For example, if the env is `prod-sbx` (Sandbox), the claim will have the value `https://sandbox.dpc.cms.gov/api/v1/Token/auth`. For production, the value should be `https://dpc.cms.gov/api/v1/Token/auth`
No security implications.
Tested by using the generator to create JWTs for various environments and then validated those JWTs using Postman.
All tests were …
=> fix: add `aud` to JWT and switch on env

dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/PractitionerResource.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/PractitionerResourceTest.java
If a new user with no existing providers tried to do a bulk upload of more providers than allowed, they would receive a 500 due to an IndexOutOfBounds error. This is because the response was trying to include the first of a list of existing providers when there were no existing providers. The test was missing this case by first successfully uploading a provider and then trying to upload the same provider again with the same NPI.
First, change the test so that the 2nd provider uploaded has a different NPI and therefore has no existing providers to return from. Secondly, include the entity in question in the response instead of trying to find one from a list when there possibly isn't one there.
- create a new practitioner with a new NPI for 2nd attempt in the test
- just return the `entity` …
=> DPC-902: Fix return value when adding too many providers

Makefile, docker-compose.yml, dpc-test.sh, dpc-unit-test.sh
Maven excessively logs transfer progress when downloading artifacts.  This makes it extremely difficult to parse logs locally and in Github Actions.  Because the transfer progress is purely informational, we can safely suppress it.
See example below of logging exceeding 50,000 lines.
- Updated the calls to `mvn` to pass in `-ntp` to ensure the _no transfer progress_ is passed, in order to suppress transfer progress when downloading artifacts with Maven.
In Github Actions, the `Build and Test API` step was previously logging over 50,000 lines.
Now, [with this feature branch](https://github.com/CMSgov/dpc-app/runs/1514114057?check_suite_focus=true), the logging is less than 10,000 lines.
Please review.
=> Suppress the transfer progress logging when downloading artifacts with Maven

.github/workflows/ci-workflow.yml, pom.xml
In Github Actions, we are running with a pinned JDK and pinned version of error-prone.  But, in Jenkins, the JDK can get updated automatically.  We should ensure that our local CI aligns with our AWS CI.
- Removed the JDK pin from the Github Actions configuration file, and simply specified the major Java version so that we pick up minor version upgrades for free.  This aligns with the same thing we are doing in Jenkins.  
- Updated to error-prone version 2.4.0.  
- Since we are updating to a new version of static analysis (along with a Java minor version upgrade), it is expected that there be some static analysis issues.  Fortunately, there are no errors or major findings; but, there are warnings.  The scope of fixing the warnings is out of scope of this activity. 
- Created [a …
=> Remove JDK Pin in CI and Update error-prone Static Analysis

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/AggregationAppModule.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/dao/ProviderDAO.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/dao/RosterDAO.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/service/LookBackServiceImpl.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/health/AggregationEngineHealthCheckTest.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/service/LookBackServiceImplTest.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/PatientResourceTest.java, dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java
The Patient/$everything endpoint was unnecessarily requiring both a Provenance header (attesting to the provider/patient relationship) and a Roster for the given patient and provider. This was redundant and confusing for users.
It was decided to remove the requirement for a Roster when using `Patient/$everything`
- Remove Roster check from the `PatientResource`
- Update tests for this change
- The `PatientResourceTest` is relying heavily on existing test data and the tests are dependent on one another. As part of this PR, I refactored some of this in order to aid in readability and adjust for the change to the `PatientResource`
- Since there was no longer a Roster, `LookBackServiceImpl. getPractitionerNPIFromRoster` was failing to return a Practitioner NPI. To fix this, I added a …
=> DPC-916 fix: Remove requirement for Patient to be in a group for Patient/$everything

.snyk
We would like to avoid pushing out software with a vulnerable dependency.  Our Snyk integration with Jenkins allows this, and a [separate ticket in the ops repo](https://github.com/CMSgov/dpc-ops/pull/279) will check the correct box (literally, _un_check the box by default, actually).  
However, we currently have a few known vulnerabilities in software that we only use in test environments, and for which we don't have a good upgrade path (we've [already upgraded to the latest available library](https://github.com/CMSgov/dpc-app/pull/1115)).  This PR gives us 30 days of silence from Snyk on those particular issues, so that we can proceed to reduce the changes of publishing new, _unknown_ issues.
- Add a .snyk file 
The file was produced with the `snyk wizard` CLI tool
By itself, this PR …
=> DPC-780 Have major Snyk finding fail builds

dpc-api/src/main/java/gov/cms/dpc/api/auth/macaroonauth/MacaroonsAuthenticator.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/EndpointResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/jdbi/EndpointDAO.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/AbstractEndpointResource.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/EndpointResource.java, dpc-testing/src/main/java/gov/cms/dpc/testing/factories/FHIRPatientBuilder.java, dpc-testing/src/main/java/gov/cms/dpc/testing/factories/OrganizationFactory.java
During the audit/risk assessment of DPC API it was discovered that path authorization for the /Endpoint resource was not functioning correctly.
A fully authenticated client could have access to another organization's Endpoint resource and its operations (get,update,delete).
Affected endpoints:
GET /Endpoint 
PUT /Endpoint 
Delete /Endpoint
MacaroonsAuthenticator was attempting to authorize requests to Endpoint resource by using DPC-attribution's Endpoint search API. The MacaroonsAuthenticator attempted to search for an EndpointResource filtering by "_id" (id of the resource specified in the path by the client) and "organization" (Extracted from authenticated principal/token).
If the search returned a result it meant there was a resource with that specified id and belonging to the …
=> Added suport for id filter in Endpoint resource search

Makefile
The `cryptography` library was [updated](https://cryptography.io/en/latest/changelog.html) on 2/7/2021 and it introduced a dependency on `Rust`.  This dependency requirement causes our usage of the library to fail.  
To aid users in building the library without `Rust`, the `cryptography` build process now outputs:
```
=============================DEBUG ASSISTANCE=============================
If you are seeing a compilation error please try the following steps to
successfully install cryptography:
1) Upgrade to the latest pip and try again. This will fix errors for most
users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2) Read https://cryptography.io/en/latest/installation.html for specific
instructions for your platform.
3) Check our frequently asked questions for more …
```
=> Ensure smoke test dependencies exclude Rust

.github/workflows/ci-workflow.yml
Snyk was added to Github Actions for `dpc-app` in this PR: https://github.com/CMSgov/dpc-app/pull/1150
However, it has caused PRs to be blocked because we currently do not have a stable baseline of findings.
Until the findings can be addressed and remediated, we can rely solely on the periodic scan that happens outside of CI and can be viewed in the Snyk dashboard.
- Updated the Github Actions pipeline so that the Snyk scan is removed.
CI pipeline is passing in Github Actions.
Please review.
=> Remove Snyk from Github Actions

.github/workflows/ci-workflow.yml
Ubuntu 20 does not currently include Ansible, which is required to set up our test environments.  For the moment, we will be pinning GitHub Actions to use Ubuntu 18.
- Use Ubuntu 18.04 for both GHA tests
This is not a _change_ so much as a temporary reversion.  We expect the Ubuntu maintainers to include Ansible in a future update to version 20, and have a [ticket](https://jira.cms.gov/browse/DPC-1173) to remind us to review and revert this PR.
- Do we need to pin both tests, since the web app is unaffected?
=> DPC-1170: Pin GHA to ubuntu-18.04

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/ResourceFetcher.java
Reverts CMSgov/dpc-app#1251
Because [BFD fixed the underlying issue](https://github.com/CMSgov/beneficiary-fhir-data/pull/516) that caused our outage, we would like to return to our position of strict enforcement of `_since` timing.
=> Revert "DPC-1225 remove unchecked exception for bfd time regression"

docker-compose.portals.yml
This branch fixes the broken docker image build job on jenkins: https://management.dpc.cms.gov/job/DPC%20-%20Docker%20Build/
* changing admin app image from `dpc-admin` to `dpc-web-admin`
The jenkins job was failing because the docker-compose specified the wrong image for the `dpc-admin` service. That meant that rubocop was being ran on an older image that had been cached on jenkins.
All feedback welcome.
=> DPC-1073: Fixing docker build job

docker-compose.portals.yml, docker-compose.yml, dpc-go/dpc-attribution/docker-compose.yml
The current deployed major version of Postgres in AWS for DPC is Postgres 11.  However, in the docker-compose stacks for dpc-app, we are pulling from postgres:latest (see here for example).
We need to ensure all references to pulling Postgres images from Dockerhub in dpc-app align with the version of Postgres that we are using in AWS.  This should be `postgres:11` image in Dockerhub.
- Pin Postgres version to 11
=> DPC 1329 Fix: Pin Postgres image version to 11

dpc-impl/Gemfile, dpc-impl/Gemfile.lock, dpc-impl/config/newrelic.yml
This branch adds the new relic gem to dpc-impl for reporting.
* Updating `Gemfile` with dependency
* Updating `Gemfile.lock`
* Adding config file
To get the updates to `Gemfile.lock`, I built the impl image with `make impl` and then ran `make start-portals`. Once it was running, I copied the file out of the running container.
All feedback is welcome.
=> DPC-1335: Adding New Relic integration

Makefile, dpc-go/dpc-attribution/docker-compose.yml
Following changes made in [this PR](https://github.com/CMSgov/dpc-app/pull/1310), `make start-v2` was no longer exposing the port for the postgres container. According to the logs, the `dpc-go/dpc-attribution/docker-compose.yml` command was recreating the db since the migrator depended on it. This caused an error when trying to connect to the db via Postico or by using the `make seed-db` command:
```
could not connect to server: Connection refused
Is the server running on host "localhost" (::1) and accepting
TCP/IP connections on port 5432?
could not connect to server: Connection refused
Is the server running on host "localhost" (127.0.0.1) and accepting
TCP/IP connections on port 5432?
```
```
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the …
```
=> Fix dpc-go/dpc-attribution/docker-compose.yml

Makefile, dpc-go/dpc-api/docker-compose.yml, dpc-go/dpc-attribution/docker-compose.yml, dpc-go/dpc-attribution/migrator/README.md, dpc-go/dpc-attribution/src/repository/implementer_repository_test.go
Now that we have changed the context for the dpc-go docker-compose files, we need an easy way to rebuild all of the v2 components in order to use updated code. This includes migrator, attribution2, and api (v2).
- add `make build-v2` target
- change context for dpc-api/docker-compose.yml build cmd
- add build cmd for migrator
- update migrator README
- `make build-v2` successfully rebuilds migrator, attribution2, and api (v2)
Any
=> FEAT: Add `make build-v2` command

dpc-go/dpc-api/docker/Dockerfiles/Dockerfile.api, dpc-go/dpc-attribution/docker/Dockerfiles/Dockerfile.attribution
The V2 API and V2 Attribution Docker images currently contain all of the source code.  We should ensure that the images are lean.
- Use multistage builds so that the final image that is used in production is lean and secure.
- Updated V2 API `Dockerfile` to leverage multistage builds, with a lean final image.
- Updated V2 Attribution `Dockerfile` to leverage multistage builds, with a lean final image.
The images build successfully.  Manual inspection of the running containers was performed, and ensured that the source code has been removed.
The scope of this modification is limited to introducing multistage builds.  However, there are a few outstanding questions which might warrant additional tickets?
(1) Is port 8080 the correct port to be exposed?  
(2) Is the CI in Github Actions …
=> DPC-1573: Use multistage builds for V2 API and V2 Attribution

Makefile
Issues in our `Makefile` were identified:
- `start-v2` uses images in the `dpc-v2` project, and does not build new images when executed (potentially resulting in new containers containing stale code)
- `build-v2` builds new images in the default project instead of the `dpc-v2` project
- Updated the `build-v2` target to ensure the images are built in the `dpc-v2` project (via `-p`).  This is necessary since all the images that are run as part of `start-v2`, are specified to run in `dpc-v2` project.
- Updated the `start-v2` target to ensure stale images are rebuilt.  This is necessary in situations when `build-v2` is not used, allowing users to run containers with latest/greatest code that is built into newly built images when this target is run.
Tested locally with successful results. …
=> Update Makefile to Ensure V2 Images are Built Appropriately

dpc-go/dpc-api/docker-compose.yml, dpc-go/dpc-attribution/docker-compose.yml
To ensure consistency between V1 image naming and V2 image naming, we should ensure the V2 `docker-compose` files, which are used to build the images, appropriately identify an image name for each V2 image.
- Added the name of the image to the V2 API and V2 Attribution `docker-compose` files.
Local testing succeeded.
Please review.
=> DPC-1574: Add image name to V2 API and V2 Attribution

tools.go
This change stems from https://github.com/CMSgov/bcda-app/pull/731
DPC is not using `delve` in the DPC-specific SSAS image; it should be removed.
- Removed the `delve` dependency from the DPC-specific SSAS image.
NOTE: This is simply a workaround to get the team moving after incompatible delve changes were [released today](https://github.com/go-delve/delve/pull/2606).  In the future, the SSAS image should either be taken directly from ECR or pulled directly from `bcda-ssas-app` (in order to eliminate cross-project dependencies)
Docker Build passing.
Please review.
=> Remove delve dependency from SSAS image

dpc-go/dpc-api/src/client/ssas_client.go, dpc-go/dpc-api/src/service/admin/router.go, dpc-go/dpc-api/src/service/admin/router_test.go, dpc-go/dpc-api/src/service/public/router.go, dpc-go/dpc-api/src/service/public/router_test.go, dpc-go/dpc-attribution/src/repository/organization_repository_test.go, dpc-go/postman/developer-edition/DPC V2 - Developer's Edition.postman_collection.json, dpc-go/postman/functional-tests/DPC_V2_Functional_Tests.postman_collection.json
The SRE team has requested that all public and admin api routes be based off of `/api/v2` instead of `/v2`
- update public and admin routes to be based off of `/api/v2`
- update unit tests
- update postman tests
- Unit tests for API all pass
- Postman requests do not return 404s when using `/api/v2`
Any
=> DPC-1662: Change V2 API Routes to `/api/v2`

Makefile, dpc-go/dpc-attribution/docker-compose.yml, dpc-go/dpc-attribution/docker/Dockerfiles/Dockerfile.attribution, dpc-go/dpc-attribution/docker/Dockerfiles/entrypoint.sh, dpc-go/dpc-attribution/migrator/README.md
This PR is part of the work needed to complete DPC-1575.
SRE team requires the migrator to be run as part of running attribution v2
- include the migrator image in the attribution v2 Dockerfile
- add entrypoint script to run the migrations
- update docker-compose for attribution and Makefile make build-v2 target to drop separate migrator build
- fix typo in migrator README
- Running `make start-v2` successfully starts up attribution v2 (and other services) normally and also automatically migrates attribution v2
Does the migrator README need to be changed more or dropped entirely? I think the manual instructions could still be helpful when not using docker, but am open to other thoughts.
=> DPC-1575: Move attribution v2 migrator to Dockerfile

dpc-smoketest/pom.xml
Snyk has indicated that there may be vulnerabilities from `com.thoughtworks.xstream` and `org.apache.pdfbox`. Upon further inspection, these are both dependencies of org.apache.jmeter, which we only use for our smoke tests. Jmeter is using older versions of these two libraries, but their newer versions have been updated to deal with the vulnerabilities indicated by Snyk.
override the versions of xstream and pdfbox to their newest stable versions instead of those used by jmeter
since we are not using these libraries directly, but instead they are used by our dependency (jmeter), we need add both of them to the pom before jmeter so that jmeter will use these versions instead of installing its own, outdated dependencies.
While not completely new (these were already in use by jmeter), added …
=> DPC-1667: Upgrade dependencies in response to Snyk alerts

dpc-adminv2/config/environments/production.rb, dpc-impl/config/environments/production.rb
In the implementer portal the `production` configuration did not read the email server configuration from the environment. This PR reads these values, including email server URL, port, etc.
- Read email server configuration values from environment variables (implementer portal)
- Copy the same configuration code to the v2 admin portal 
This is a bug fix for work in previous sprints with SIA and security checklists
Any changes needed?
=> DPC-1875: Implementer portal email server configuration

.snyk
Snyk is reporting that we need to upgrade to the latest version of `nokogiri`. We did 😄 .
- Ignore this alert
This PR does not have any change to application behavior or installed software versions.
I have validated that we're running the version of `nokogiri` that addresses the vulnerability, and that after this change a local snyk test no longer reports it.
Any issues?
=> DPC-1946: Ignore nokogiri false positive

pom.xml
PR #1531 causes the local build to fail. The maven dependency tree does not add a `log4j` reference when it is reverted; it is an unnecessary step in `log4shell` remediation.
=> Revert #1531

dpc-aggregation/pom.xml, dpc-api/pom.xml, dpc-common/pom.xml, dpc-smoketest/pom.xml
Update gson Maven dependency 2.8.9 -> 2.9.0 to keep dependencies up to date
=> [DPC-2297] Update gson Maven dependency to 2.9.0

dpc-common/pom.xml, pom.xml
* Update hibernate-core 5.5.7 -> 5.6.5
=> [DPC-2297] Upgrade hibernate-core to lastest version

dpc-web/config/routes.rb
* The documents link has moved to /docsV1, and this change will re-route all traffic within the web applications to /docsV1.
=> Change route to redirect to docsV2

dpc-admin/app/models/organization.rb
This query includes un-registered orgs as well as disabled in the api orgs into the same query for the "not enabled in API" org filter. This fixes the original bug DPC-2351
* Changed the query using a join between organizations and registered_organizations when trying to use the filter for "not enabled in API" organizations from the Web Admin Organization view. This will not include those registered orgs that have been disabled, and orgs that have not yet been registered. Previously, unregistered orgs were not showing.
=> DPC-2579: Adjust filter query for un-registered orgs

docker-compose.portals.yml, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java, dpc-api/src/main/resources/application.conf, dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java
*  Increase the timeout threshold for completing requests from 30 to 60
* In the case of the /Patient/$everything endpoint, this timeout is too short and results in >90% of requests to the endpoint timing out and returning 500s from the API
* Add some clarifying comments
=> Increase JobTimeout Threshold

dpc-admin/Gemfile.lock, dpc-adminv2/Gemfile.lock
* Conservatively bundle update the omniauth gem in dpc-admin and dpc-adminv2 based on guidance from: CVE-2020-36599
=> Omniauth Gem Update

dpc-api/src/main/java/gov/cms/dpc/api/auth/DPCAuthFilter.java, dpc-common/src/main/java/gov/cms/dpc/common/logging/filters/GenerateRequestIdFilter.java, dpc-common/src/main/java/gov/cms/dpc/common/logging/filters/LogResponseFilter.java, dpc-common/src/main/java/gov/cms/dpc/common/utils/XSSSanitizerUtil.java, dpc-common/src/test/java/gov/cms/dpc/common/logging/filters/GenerateRequestIdFilterUnitTest.java, dpc-common/src/test/java/gov/cms/dpc/common/logging/filters/LogResponseFilterTest.java
Also updated XSSSanitizer from using a deprecated properties
* Added properties to logging we didn't have before
* Added try/catch around MDC.clear() as we think there could be an error in that function we're not capturing causing MDC to persist from one call to the next across organizations.
=> DPC-2868 Increase logging for more clarity and visibility 

Makefile, dpcv1-portals-test.sh
* Add a command for bringing down the resources that are created when we use make `ci-portals-v1`
=> Add a make down command for start-v2-portals

dpc-common/src/main/java/gov/cms/dpc/common/logging/filters/GenerateRequestIdFilter.java, dpc-common/src/main/java/gov/cms/dpc/common/logging/filters/LogResponseFilter.java, dpc-common/src/test/java/gov/cms/dpc/common/logging/filters/GenerateRequestIdFilterUnitTest.java, dpc-common/src/test/java/gov/cms/dpc/common/logging/filters/LogResponseFilterTest.java
* Get full media type as string for logs, and fix associated tests.
=> DPC-2945 Get full media type as string

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/DataResource.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/DataResourceTest.java, src/test/EndToEndRequestTest.postman_collection.json
Making the `/Data` endpoint `@Produce` application/ndjson instead of producing an aplication/fhir+json
Needed to update the tests as well to contain the `Accepts application/ndjson` header
*
=> DPC-565 Data Headers

dpc-go/dpc-api/src/auth/ssas.go
Ignoring this line as research has indicated this is not a problem, connections are recommended to be closed, and this code is not used or maintained at this time as well. V2 was never supported or worked on by the Fearless team. Moving V1 to a production ready state was priority per CMS.
Needed to add an ignore line to get through build. Research on the previous error did not indicate a significant problem. Additionally, the v2 golang based code is not currently in use, is not publicly available, and is not supported by the current contract team.
=> Gosec error fix

dpc-admin/config/initializers/sidekiq.rb, dpc-adminv2/config/initializers/sidekiq.rb, dpc-impl/config/initializers/sidekiq.rb
This updates the Sidekiq configurations in dpc-admin, dpc-adminv2, and dpc-impl, to match the change made [here](https://github.com/CMSgov/dpc-app/pull/1860/files#diff-3928310c948a0787c751598050c359efc90035cbe50db5a960f8695c089e2ad6) in dpc-web.
Though these three passed our GitHub Actions, it's possible that this is what's causing our ECS container checks to fail during the dev deployment (error messages in our AWS logs seem to hint that this is the case). If that's true, then this PR should fix our dev deployments.
=> DPC-3312 - Fix sidekiq config code to match updated version

.github/workflows/ci-workflow.yml
This PR clears out our GitHub Actions workflows, so that we stop building the V2 API and related frontends. Pull Requests will now only trigger CI for the v1 API, dpc-web, and dpc-admin.
=> [DPC-2868] remove GitHub CI Workflows related to v2

dpc-api/pom.xml, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/BaseResourceUnitTest.java, pom.xml
https://jira.cms.gov/browse/DPC-3474
Updated Jacoco settings to get it to generate a coverage report when unit tests are run locally.
Added unit tests for BaseResource.
This was done as part of [DPC-3381](https://jira.cms.gov/browse/DPC-3381), which is an attempt to increase coverage in the Resources folder.
Also, I temporarily updated to the newest version of Mockito, which let me push code coverage to 100%.  Unfortunately, even though everything ran fine locally tests started failing when they were run on the DPC CI Workflow (See [example](https://github.com/CMSgov/dpc-app/actions/runs/5326360468/jobs/9648950731)), so I reverted it back.  We should probably look into upgrading at some point in the future, or just refactoring our code to be more easily testable.
New code coverage report …
=> Me dpc 3437 baseresource code coverage update

dpc-api/pom.xml, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/BaseResourceUnitTest.java, dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/features/FHIRRequestFeatureTest.java, pom.xml
https://jira.cms.gov/browse/DPC-3494
Updated Mockito from 3.4.6 to 5.4.0.
Removed mocking of Method class from FHIRRequestFeatureTest.
Updated BaseResourceUnitTest to use new MockedStatic and MockedConstruction.
We were running an old version of Mockito that didn't support mocking static or final methods, or constructors, and this was preventing us from pushing code coverage as far as we otherwise could.  The new version of Mockito was also causing unit tests to fail randomly and erratically.  
The new version was causing tests to fail because an old test in `FHIRRequestFeatureTest` was mocking the `Method` class from `java.lang.reflect`.  Mockito depends on this class, along with a few others from that package, and mocking them is essentially rewriting Mockito's plumbing while it's …
=> Me dpc 3494 part 2 upgrade mockito

.github/dependabot.yml
https://jira.cms.gov/browse/PLT-143
Add Dependabot config
We decided to converge on Dependabot for our dependency management solution. We'll only be alerting on critical security updates.
=>  PLT-143: Enable and configure dependabot for security updates across all repos

README.md, dpc-smoketest/pom.xml, dpc-testing/pom.xml
https://jira.cms.gov/browse/DPC-3519
Removed dpc-testing and dpc-smoketest from SonarQube.
Update readme.md to show how to run SonarQube locally.
dpc-smoketest and dpc-testing are modules that exist solely to test the other subprojects and don't need to be tested on their own.  They were still included in our SonarQube coverage numbers, though, and dragging them down since they're at 0%.
dpc-smoketest and dpc-testing are no longer included in SonarQube coverage reports.
=> Me 3519 remove tests from sonarqube

dpc-common/src/main/java/gov/cms/dpc/common/consent/entities/ConsentEntity.java, dpc-common/src/main/java/gov/cms/dpc/common/consent/entities/OptOutFileEntity.java, dpc-consent/src/main/resources/consent.migrations.xml
https://jira.cms.gov/browse/DPC-3599
This PR does the following:
1. A database migration for `dpc_consent` db. It creates a table called `opt_out_file`, consisting of metadata for each opt out file we import, as well as a foreign key `opt_out_file_id` on the `consent` table. For every beneficiary who chooses to opt out, we'll be storing a record in the `consent` table. The Many-to-One relationship here allows us to tie each record to an opt out file and timestamp, for visibility/transparency.
2. Creates an `OptOutFileEntity` for the ORM, so that our Java code can interact with it.
3. Updates the `ConsentEntity` to reflect the Many-to-One relationship.
- Successfully ran the migration on my local environment without any issues.
- Successfully compiled `dpc-common` and `dpc-consent`.
If any …
=> [DPC-3599] Opt-out Import Database Migrations

README.md
none
Update README.md to explain how to run against BFD sandbox.
Question came up in a meeting wondering if we could run against the BFD sandbox, this update adds instructions on how to do it.
I followed the instructions and was able to pull down test resources from BFD.
=> Update README.md to include how to run against BFD sandbox

dpc-web/Gemfile, dpc-web/Gemfile.lock
https://jira.cms.gov/browse/DPC-3643
Version of listener gem in Gemfile updated to conflicting gem.
Gemfile.lock updated for new version of listener gem
Conflict kept rails server from starting
Rails server now starts without error messages
None
=> DPC-3643 update listen gem to avoid conflict

Makefile, docker-compose.portals.yml, dpc-portal/config/initializers/health_check.rb, dpc-portal/config/initializers/sidekiq_alive.rb, dpc-portal/config/puma.rb, dpc-portal/config/routes.rb, dpc-portal/docker/entrypoint.sh, dpcv1-portals-test.sh
https://jira.cms.gov/browse/DPC-3665
- Update port from 3000 to 3100 to avoid conflict with admin portal in deployed environments
- Move all routes to be scoped under `/portal` to match routing in deployed environments
- Update sidekiq port to avoid conflict with admin sidekiq port
- Add health check endpoint to support load balancer checks
We identified a couple of adjustments to the Rails application in the deployment ticket to support infra deployments.
Rebuilt the portal application and spun it up locally:
```
make portal
make down-portals
make start-portals
```
Was able to verify all endpoints are available:
---
---
Also deployed this to dev and confirmed accessibility.
=> DPC-3665: Update Rails portal configuration to match infrastructure setup

dpc-common/src/test/java/gov/cms/dpc/common/entities/AddressEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/AttributionRelationshipTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/ContactEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/ContactPointEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/EndpointEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/NameEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/OrganizationEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/PatientEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/PersonEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/ProviderEntityTest.java, dpc-common/src/test/java/gov/cms/dpc/common/entities/RosterEntityTest.java
N/A
- Update usage of org.junit to org.junit.jupiter.api
- Update `PersonEntityTest` to create a new entity for each test
- Auto-formatting updates from the IDE (sorry 😅)
Followup to #1971. @alex-dzeda noticed that the coverage didn't increase in Sonarqube after merging the PR; I tested locally with `make unit-tests` and observed that the new tests were not run as part of the test suite locally or included in local code coverage metrics.
After comparison with other, existing tests, I determined that the issue was using `org.junit.Test` and `org.junit.Asserts` instead of the jupiter equivalents.
I also needed to update `PersonEntityTest` to create a new entity for each test, since it was running into NullPointerException issues with the existing approach.
Verified the local code coverage …
=> Ensure dpc-common entity tests are run as part of test suite

docker-compose.portals.yml, dpc-admin/app/jobs/application_job.rb, dpc-admin/config/application.rb, dpc-admin/docker/entrypoint.sh, dpc-portal/app/jobs/application_job.rb, dpc-portal/config/application.rb, dpc-portal/docker/entrypoint.sh, dpc-web/app/jobs/application_job.rb, dpc-web/config/application.rb, dpc-web/docker/entrypoint.sh
https://jira.cms.gov/browse/DPC-3735
- Update actionmailer configuration to add jobs in specific queues (this setting is used by Devise)
- Update base ApplicationJob to add jobs in specific queues
- Update sidekiq commands in entrypoints to process specific queues
We are currently experiencing inconsistent issues with emails being sent out from the sandbox portal.
Emails are queued as sidekiq jobs within Redis and then processed by sidekiq workers. However, the dpc-web, dpc-admin, and dpc-portal sidekiq applications are all configured to enqueue and process jobs from the same Redis instance and the same default queue, which means that a job meant for the dpc-web application may be processed by the -admin or -portal worker. This ends in failure.
This PR configures sidekiq and actionmailer …
=> DPC-3735: Enqueue admin and portal jobs in unique sidekiq queues

dpc-portal/Gemfile
https://jira.cms.gov/browse/DPC-3740
- Move lookbook dependency from :development group to :production group in Gemfile
In #1979 we installed lookbook and configured it to deploy in the dev environment. However, the lookbook dependency is only installed in the :development RAILS_ENV group. It needs to be installed in the :production group, which is the RAILS_ENV used in all deployed environments.
In the future we should make sure this dependency is not installed in sandbox/prod, but until we get to production launch readiness we can keep this in the production group.
cc. @StewGoin
=> DPC-3740: Install lookbook in deployed environments

dpc-portal/lib/tasks/dpc.rake, dpc-portal/spec/spec_helper.rb
Added rake task to create an org in DPC for use by the portal
Makes testing portal UI easier
1. Start the dpc `make start-dpc`
2. Run the task `docker exec dpc-app-dpc_portal-1 bundle exec rails dpc:make_org`
3. Verify the printed url shows an org in the browser
=> Add task to create local org

dpc-api/pom.xml, dpc-api/src/main/java/gov/cms/dpc/api/DPCAPIModule.java, dpc-api/src/main/java/gov/cms/dpc/api/auth/DPCAuthFilter.java, dpc-api/src/main/java/gov/cms/dpc/api/converters/InetDeserializer.java, dpc-api/src/main/java/gov/cms/dpc/api/entities/IpAddressEntity.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractBaseResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractIpAddressResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/BaseResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/IpAddressResource.java, dpc-api/src/test/java/gov/cms/dpc/api/converters/InetDeserializerUnitTest.java, dpc-api/src/test/java/gov/cms/dpc/api/jdbi/IpAddressDAOTest.java, dpc-api/src/test/java/gov/cms/dpc/api/jdbi/IpAddressDAOUnitTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/BaseResourceUnitTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/IpAddressResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/IpAddressResourceUnitTest.java, dpc-testing/README.md, pom.xml
https://jira.cms.gov/browse/DPC-3762
Adds an IpAddress endpoint to dpc-api.  
Sets DPCAuthFilter to always return a 403 when the new endpoint is called.
Updated dpc-testing/README.md to explain how to write unit tests for DAOs.
Updated IpAddressEntity so its methods are fluent.
Adds a new IpAddress endpoint that supports reading, submitting and deleting an organization's IP addresses.  For the time being, the end point is disabled and returns a 403 when any operations are called on it.
If you remove the auth filter the integration tests demonstrate GET, POST and DELETE operations on the end point.
=> [DPC-3762] Me/dpc 3762 add api endpoints for ip address

dpc-api/src/main/java/gov/cms/dpc/api/models/CreateIpAddressRequest.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/AbstractIpAddressResource.java, dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/IpAddressResource.java, dpc-api/src/test/java/gov/cms/dpc/api/models/CreateIpAddressRequestUnitTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/IpAddressResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/IpAddressResourceUnitTest.java, pom.xml
https://jira.cms.gov/browse/DPC-3762
Updates POST request to create an IpAddress so that it no longer takes an IpAddressEntity and requires an org_id.
For context, see this PR comment https://github.com/CMSgov/dpc-app/pull/2006#discussion_r1446793809
Tested locally.
=> [DPC-3762] No longer takes IpAddressEntity in POST request

Makefile, dpc-portal/Gemfile, dpc-portal/Gemfile.lock
- Removed listener and web-console gems from development stanza of Gemfile
- Updated makefile to stop the supporting services of ci-portal, etc, which dpc-down wasn't doing for me
Should not have effect on production services
Nothing should change in terms of how things work
=> Remove web-console from dpc-portal

dpc-admin/Gemfile, dpc-portal/Gemfile, dpc-web/Gemfile
https://jira.cms.gov/browse/DPC-3861
Updates nokogiri to >= 1.16.2 in dpc-admin, dpc-web and dpc-portal to address [this](https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-xc9x-jj77-9p9j) vulnerability.
Vulnerability checks were failing when we attempted to merge code to doc-app.
All tests are passing.
=> Update nokogiri gem

dpc-web/app/views/devise/password_expired/show.html.erb, dpc-web/app/views/portal/show.html.erb, dpc-web/spec/features/authentication/user_sign_in_spec.rb, dpc-web/spec/features/confirmation/user_confirmation_email_spec.rb
https://jira.cms.gov/browse/DPC-3882
- Removes the username of a logged in user from the logged-in home title
- Adds a title for the password expired page
All other page-level view components in dpc-web have been confirmed to a) have a title, and b) expose no PII in the title.
=> [DPC-3882] Remove PII from dpc-web portal page title

dpc-portal/app/components/core/form/masked_input_component.html.erb, dpc-portal/app/components/core/form/masked_input_component.rb, dpc-portal/app/components/core/form/masked_input_component_preview.rb, dpc-portal/app/components/core/form/text_input_component.html.erb, dpc-portal/app/components/core/form/text_input_component.rb, dpc-portal/app/components/core/form/text_input_component_preview.rb, dpc-portal/app/components/core/modal/modal_component.html.erb, dpc-portal/app/components/core/modal/modal_component.rb, dpc-portal/app/components/core/modal/modal_component_preview.rb, dpc-portal/app/components/core/table/row_component.html.erb, dpc-portal/app/components/page/credential_delegate/invitation_success_component.html.erb, dpc-portal/app/components/page/credential_delegate/invitation_success_component.rb, dpc-portal/app/components/page/credential_delegate/invitation_success_component_preview.rb, dpc-portal/app/components/page/credential_delegate/new_invitation_component.html.erb, dpc-portal/app/components/page/credential_delegate/new_invitation_component.rb, dpc-portal/app/components/page/credential_delegate/new_invitation_component_preview.rb, dpc-portal/app/controllers/credential_delegate_invitations_controller.rb, dpc-portal/app/models/cd_invitation.rb, dpc-portal/config/routes.rb, dpc-portal/spec/components/core/form/masked_input_component_spec.rb, dpc-portal/spec/components/core/form/text_input_component_spec.rb, dpc-portal/spec/components/core/modal/modal_component_spec.rb, dpc-portal/spec/components/page/credential_delegate/invitation_success_component_spec.rb, dpc-portal/spec/components/page/credential_delegate/new_invitation_component_spec.rb, dpc-portal/spec/factories/users.rb, dpc-portal/spec/models/cd_invitation_spec.rb, dpc-portal/spec/rails_helper.rb, dpc-portal/spec/requests/credential_delegate_invitations_spec.rb
https://jira.cms.gov/browse/DPC-3872
- Updated TextInputComponent to show errors
- Added MaskedInputComponent to support Phone Mask (must be child of form tag)
- Added a ModalComponent for use by NewInvitationComponent and RowComponent
- Added components for credential delegate invitation page and success page
- Added mock CD Invitation until we have a db schema to handle validations
- Added CredentialDelegateInvitation controller (with authentication required)
Just getting the views working. No actual logic beyond validations.
Screenshots
=> DPC-3872: AO invites CD

dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/AdminResource.java, dpc-api/src/test/java/gov/cms/dpc/api/AbstractSecureApplicationTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/AdminResourceTest.java
https://jira.cms.gov/browse/DPC-3905
Renamed the current `/Admin/Organization` end point to indicate that it's searching by NPI and not id.
Despite the fact that it said it was searching by id, the admin end point we already have is actually searching by NPI.  The initial tests we had never caught it because they were only checking for a 200, not verifying the results.  I added a new integration test to AdminResourceTest that performs the search by NPI and ensures that a valid org is returned.
Passes new integration tests.
=> [DPC-3905] Add admin endpoint for fetching an organization by NPI

lambda/opt-out-import/main.go, lambda/opt-out-import/main_test.go, lambda/opt-out-import/parsers.go, lambda/opt-out-import/parsers_test.go
[DPC-3888](https://jira.cms.gov/browse/DPC-3888)
- Unwrap S3 events from SNS events from SQS events
The pipeline from S3 --> Lambda includes hops from S3 --> SNS --> SQS --> Lambda, and each of those steps end up wrapping the previous message in another event wrapper.
This updates our parsing code to unwrap the S3 event from those other wrappers.
I have manually verified in AWS that the uploaded integration test file is parsed correctly.
=> DPC-3888: Handle SQS/SNS-wrapped event notifications for Opt Out Import

lambda/opt-out-import/db.go, lambda/opt-out-import/main.go
https://jira.cms.gov/browse/DPC-3888
- Ensure the effective date in confirmation file is set
Noticed the effective date is always 01-01-01. We should be using the `createdRecords` array which has the effective date set on each record 👍 
Verified the generated confirmation file in S3 after integration test.
=> DPC-3888: Fix effective dates in confirmation file

dpc-aggregation/src/main/resources/application.yml, dpc-api/src/main/resources/application.yml, dpc-attribution/src/main/resources/application.yml, dpc-consent/src/main/resources/application.yml
- Add access-json request log appender
Re-add the access-json request log appender.
Verified in Splunk logs after deploying to dev.
=> Fix JSON format for access logs

lambda/opt-out-export/db.go, lambda/opt-out-export/main.go
https://jira.cms.gov/browse/DPC-3952
- Add periodic logs while scanning patients table
- Add request_filename and request_filesize
Adding some logs to:
- Show that the lambda is doing work while scanning the patients table
- Show request file information in the dashboard
Verified in the updated dashboard and in logs as part of integration test.
Matches the generated filesize in S3:
=> DPC-3952: Add additional logs to export lambda

QuickStart.md, README.md, docker-compose.portals.yml, dpc-admin/docker/entrypoint.sh, dpc-portal/bin/dev, dpc-web/docker/entrypoint.sh
N/A
- Update docker entrypoint scripts to generate golden macaroon on startup
This removes a manual step required to call the API and generate golden macaroons. If the API is running when a frontend application starts, we will automatically generate a new macaroon If the API is not running, we will continue as normal and log a message noting that there is no macaroon.
Ran `make portal && make start-portal` with and without a golden macaroon set in the docker-compose file and observed both behaviors.
=> Automatically generate golden macaroon on local dev startup

dpc-web/app/controllers/client_tokens_controller.rb, dpc-web/app/controllers/organizations_controller.rb, dpc-web/app/controllers/public_keys_controller.rb, dpc-web/app/views/client_tokens/show.html.erb, dpc-web/config/routes.rb, dpc-web/spec/controllers/client_tokens_controller_spec.rb, dpc-web/spec/controllers/public_keys_controller_spec.rb, dpc-web/spec/features/portal/managing_api_credentials_spec.rb, dpc-web/spec/features/portal/updating_organization_spec.rb
N/A
@jdettmannnava surfaced that the `/portal` path is used in the sandbox to route back to the homepage. However, this conflicts with the routing set up for dpc-portal.
This removes the /portal routing (which is just a duplicate of the root / homepage). Instead, we should explicitly route people to the root path.
Unit tests, which have tests for redirection already.
=> Remove sandbox /portal path

dpc-portal/Gemfile, dpc-portal/app/controllers/login_dot_gov_controller.rb, dpc-portal/app/controllers/main_controller.rb, dpc-portal/app/views/devise/sessions/new.html.erb, dpc-portal/app/views/layouts/application.html.erb, dpc-portal/app/views/main/welcome.html.erb, dpc-portal/spec/requests/login_dot_gov_spec.rb, dpc-portal/spec/requests/main_spec.rb
No ticket
- Log Out button at top of page if user logged in
- Log in page has only login.gov button
- User redirects appropriately after login
Interim solution until design and/or other requirements.
Manual testing
=> Manage user session better

dpc-portal/Gemfile, dpc-portal/Gemfile.lock
https://jira.cms.gov/browse/DPC-3971
Reverted simplecov gem to 0.17
Sonarqube stopped processing portal code coverage on Mar 5; the day the rails upgrade was merged into master. As part of the upgrade simplecov was not pinned to 0.17. Simplecov 0.18+ breaking ci is a [known issue](https://github.com/codeclimate/test-reporter/issues/413).
There was comment (present in the other gemfiles) warning not to upgrade, but it was removed because for some reason, when I run `bundle install` after sshing into the docker container, it will fail if there are too many bytes in the Gemfile. I removed "extraneous" comments, which meant I missed this.
[Ran the build](https://management.dpc.cms.gov/job/DPC%20-%20Docker%20Build/3666/) and [checked the …
=> Fix sonarqube not scanning dpc-portal

dpc-web/config/environments/development.rb, dpc-web/config/initializers/session_store.rb
https://jira.cms.gov/browse/DPC-3965
Conditional logic added so only store session in redis if not local
Session was being stored in redis, but development cache is by default in memory. It seemed better to keep the default cache functionality for development than use redis.
Logged in locally
=> DPC-3965 Allow local login to DPC-Web

lambda/opt-out-import/Makefile, lambda/opt-out-import/db.go, lambda/opt-out-import/db_test.go, lambda/opt-out-import/main.go, lambda/opt-out-import/main_test.go
https://jira.cms.gov/browse/DPC-3956
- Distinguish between opt ins and opt outs
- Include response and confirmation filenames, if applicable, as part of final log messages
- Fix Printf statement which was causing logs to be picked up as warning in the dashboard
- Fix DB_HOST for running integration tests locally
Updating logs to improve the information we have in the dashboard.
Updated Opt Out dashboard and confirmed graphs have data with the latest information from the integration test run.
=> DPC-3956: Update logging metrics for import job

dpc-portal/app/components/page/client_token/new_token_component.html.erb, dpc-portal/app/components/page/client_token/show_token_component.html.erb, dpc-portal/app/components/page/credential_delegate/invitation_success_component.html.erb, dpc-portal/app/components/page/organization/new_organization_component.html.erb
No ticket
Replaced tabs with spaces in components.
Tabs don't play well with all editors.
grepped and didn't find any more tabs
=> Replace tabs with spaces

dpc-admin/Gemfile, dpc-admin/Gemfile.lock, dpc-admin/config/environments/test.rb, dpc-portal/Gemfile, dpc-portal/Gemfile.lock, dpc-web/Gemfile, dpc-web/Gemfile.lock, dpc-web/config/environments/test.rb
no ticket
[Spring](https://github.com/rails/spring) (a gem for speeding up tests) and spring-watcher-listen updated
Old version of spring was blocking `rails console` from running.
Update just in "development" stanza, so should not impact production
Tests pass, can run rails console
=> Upgrade spring gem

docker-compose.portals.yml, dpc-portal/README.md, dpc-portal/app/jobs/sync_organization_job.rb, dpc-portal/app/models/provider_organization.rb, dpc-portal/spec/jobs/sync_organization_job_spec.rb, dpc-portal/spec/models/provider_organization_spec.rb, engines/api_client/app/services/dpc_client.rb, engines/api_client/spec/services/dpc_client_spec.rb
https://jira.cms.gov/browse/DPC-3903
This creates a background job that runs after a ProviderOrganization is created. It uses the ApiClient to query dpc-api, and checks if there's an organization in dpc_attribution with our new ProviderOrganization's NPI. If it does exist in attribution, the job then updates the ProviderOrganzation to link with the UUID of the corresponding dpc_attribution organization. If it does not exist in attribution,  the job sends a request to create a new organization in attribution with the correct data. 
Currently, we're using largely mock data to create the organization in dpc_attribution. From our new ProviderOrganization, we're only sending the name and NPI.
Unit tests, and ran all of the use cases on my machine.
If any security implications apply, add Jason …
=> [DPC-3903] Create and Link DPC API organization after provider_organization record is created

dpc-portal/.rubocop.yml, dpc-portal/app/controllers/authorized_official_invitations_controller.rb, dpc-portal/app/mailers/invitation_mailer.rb, dpc-portal/app/models/invitation.rb, dpc-portal/app/services/ao_invitation_service.rb, dpc-portal/app/services/cpi_api_gateway_client.rb, dpc-portal/app/views/invitation_mailer/invite_ao.html.erb, dpc-portal/config/routes.rb, dpc-portal/lib/tasks/dpc.rake, dpc-portal/spec/components/page/credential_delegate/new_invitation_component_spec.rb, dpc-portal/spec/factories/ao_org_links.rb, dpc-portal/spec/factories/cd_org_links.rb, dpc-portal/spec/factories/invitations.rb, dpc-portal/spec/mailers/invitation_spec.rb, dpc-portal/spec/models/invitation_spec.rb, dpc-portal/spec/requests/authorized_official_invitations_spec.rb, dpc-portal/spec/requests/credential_delegate_invitations_spec.rb, dpc-portal/spec/requests/organizations_spec.rb, dpc-portal/spec/services/ao_invitation_service_spec.rb, dpc-portal/spec/services/client_token_manager_spec.rb, dpc-portal/spec/spec_helper.rb
https://jira.cms.gov/browse/DPC-4015
- Invitation extended to allow authorized_official type
- Mailer for AO Invitation
- Minimal controller for handling AO invitation acceptance
- Service for generating an AO invitation and mailing invite
- Rake task for generating AO invitation
We are adding the use of "invitations" to the AO-accept-org flow.
- Automated Testing
- Manual run of rake task
=> DPC-4015 AO Invitations

Makefile
https://jira.cms.gov/browse/DPC-4038
Forces build and installation of dpc-common before attempting to copy dpc-smoketest's dependencies to JMeter.
Forcing the install of dpc-common makes sure that the dpc-common.jar and dpc-testing.jar are available when Maven attempts to build and run the smoke tests on Jenkins.  
This isn't necessary every time smoke tests need to run, only when we change dpc-common or dpc-testing or purge the Maven cache, but this was the easiest way to make sure that they're always available.
Ran against dev and made sure smoke tests passed.
=> [DPC-4038] Me/dpc 4038 fix smoke tests

dpc-portal/app/assets/stylesheets/login.scss
https://jira.cms.gov/browse/DPC-4034
login.css renamed login.scss;  background image found via asset_path function
Using *.css just puts the hard-coded values into the application.css file. The *.scss ending allows some processing, which includes using the asset_path function to derive the [fingerprinted value](https://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark) of the asset, which is what is moved to the public folder.
Used developer tools to investigate the styling of the login button, noted that the background image appeared and was fingerprinted.
=> DPC-4034 Use fingerprinted asset in css

dpc-admin/Gemfile, dpc-admin/Gemfile.lock, dpc-portal/Gemfile, dpc-portal/Gemfile.lock, dpc-web/Gemfile, dpc-web/Gemfile.lock
no-ticket
Sidekiq updated to 7.2.4 in dpc-admin, dpc-portal, and dpc-web
Docker build breaking over https://github.com/sidekiq/sidekiq/security/advisories/GHSA-q655-3pj8-9fxq
=> Update sidekiq for security

docker-compose.portals.yml, dpc-portal/app/controllers/invitations_controller.rb, dpc-portal/app/controllers/login_dot_gov_controller.rb, dpc-portal/app/services/user_info_service.rb, dpc-portal/config/initializers/devise.rb, dpc-portal/spec/requests/login_dot_gov_spec.rb, dpc-portal/spec/services/user_info_service_spec.rb
https://jira.cms.gov/browse/DPC-4025
- UserInfo service added to call login.gov user-info endpoint
- LoginDotGov controller stores token in session if IAL/2
- Move Login.gov url to env variable
Will be used in invitations controller
Put service in invitations controller, where it logged information (changes not committed)
=> DPC_4025 User Info Service

dpc-portal/Gemfile.lock, dpc-portal/spec/services/auto_session_logout_service_spec.rb
=> Add spec to cover sessions controller

engines/api_client/.rubocop.yml, engines/api_client/README.md, engines/api_client/spec/rails_helper.rb, engines/api_client/spec/services/dpc_client_spec.rb
No ticket
- dpc_client_spec updated to reflect actual calls
- config.fixture_path commented out because not using fixtures and was causing a deprecation warning
- README updated to include how to test
When [updating the docker file](https://jira.cms.gov/browse/DPC-4046), I noticed the tests weren't passing, and I had to learn again how to run the tests.
=> Make api_client specs and rubocop pass

dpc-aggregation/src/main/resources/application.yml, dpc-api/src/main/resources/application.yml
https://jira.cms.gov/browse/DPC-4039
Explicitly sets the logging level of certain namespaces to INFO, so that broken dashboards work.
A blanket INFO level for all unspecified namespaces potentially could have resulted in a flood of logs from all over our codebase, and a higher AWS bill. This approach ensures we're only turning on logs that we want to pick up on the dashboards.
Deployed this branch to `dev` and ran a number of API calls, ensuring that logs were captured as expected, and that they render successfully from the dashboards in question (pointed to dev).
=> [DPC-4039] set logger to info in relevant namespaces

docker-compose.portals.yml, dpc-portal/bin/sidekiq-dev, dpc-portal/config/environments/test.rb, dpc-portal/docker/entrypoint.sh, dpc-portal/spec/jobs/sync_organization_job_spec.rb
No ticket
- Local portal-sidekiq loads GOLDEN_MACAROON if not present
- ActiveJob queue adapter set to :test in test environment
- I noticed that ProviderOrganizations were not being created in the API on create when developing locally. The sidekiq logs showed it did not have permission to create the organization in the API. We already optionally set the GOLDEN_MACAROON on boot for the rails apps, so I ported the code to run before starting local portal sidekiq as well.
- I also noticed that some tests were calling redis when a provider organization was created. Setting the queue adapter to :test fixed the issue.
- Tests that made calls to sidekiq no longer do
- Making a provider organization locally creates the organization in the API
If any security implications apply, add Jason …
=> Make local dev sidekiq more robust

docker-compose.portals.yml, dpc-admin/Gemfile, dpc-admin/Gemfile.lock, dpc-portal/Gemfile, dpc-portal/Gemfile.lock, dpc-web/Gemfile, dpc-web/Gemfile.lock
No ticket
The nokogiri gem was updated to 1.16.5 in dpc-admin, dpc-portal, and dpc-web
- A security vulnerability was fixed in 1.16.5, and as we were using an earlier version, our checks would not pass CI.
- Gemfile.lock was added to volumes to make sure the changes rippled
Passed CI
=> Upgrade nookogiri

dpc-web/app/assets/javascripts/components/analytics_events.js, dpc-web/app/controllers/users/sessions_controller.rb, dpc-web/app/views/devise/sessions/new.html.erb, dpc-web/app/views/portal/show.html.erb, dpc-web/spec/features/authentication/user_sign_in_spec.rb
https://jira.cms.gov/browse/DPC-4041
- Fires off a `header_click` event whenever the CMS logo is clicked. 
- Fires off a `login` event after successful login.
- 
- `header_click` only triggers on CMS logo because, [per spec](https://confluence.cms.gov/display/BLSTANALYT/AA+header_click), this event should not fire when a navigation link is clicked -- and all the other items in the header qualify as navigation links.
=> [DPC-4041] Analytics -- header_click and login

engines/api_client/app/services/dpc_client.rb, engines/api_client/spec/services/dpc_client_spec.rb
https://jira.cms.gov/browse/DPC-4114
DpcClient returns FHIR:Bundle from get_organization_by_npi
get_organization_by_npi was trying to unmarshall the wrong object
- Updated tests
- Ran SyncOrganizationJob in dpc-portal rails console, and it interacted with the backend appropritately
=> DPC-4114: Fix Sync Organization

dpc-api/pom.xml, dpc-bluebutton/pom.xml
https://jira.cms.gov/browse/DPC-4124
The [previous PR failed](https://github.com/CMSgov/dpc-app/actions/runs/9602217342/job/26482573585?pr=2199) due to an inability to resolve `io/netty/handler/codec/http2/Http2Connection` during `dpc-api` unit test execution. It turns out, `io.netty` dependencies of `mockserver` were excluded only for `dpc-api`. Removing that exclusion resolves that dependency issue.
=> [DPC-4124] update mockserver version to 5.15.0

docker-compose.portals.yml, dpc-portal/app/controllers/application_controller.rb, dpc-portal/app/controllers/organizations_controller.rb, dpc-portal/app/lib/dpc_json_logger.rb, dpc-portal/app/models/current_attributes.rb, dpc-portal/bin/nonprod, dpc-portal/bin/sidekiq-nonprod, dpc-portal/config/environments/production.rb, dpc-portal/config/initializers/logging.rb, dpc-portal/config/initializers/lograge.rb, dpc-portal/spec/factories/users.rb, dpc-portal/spec/lib/dpc_json_logger_spec.rb, dpc-portal/spec/models/current_attributes_spec.rb
https://jira.cms.gov/browse/DPC-4126
- Hide Foreman service log prefixes in nonprod (deployed environments)
- Add request-global log attributes for current_user info, organization info, and any raised exceptions
- Fix request_id attribute
Noticed a few issues while auditing the logs produced by the portal in splunk:
- Since we are using foreman to run the fake CPI API GW in nonprod, it is prefixing the service name. This breaks the JSON formatting of each log line, which breaks splunk parsing. Added sed commands to fix this.
- The request_id is not logged because it uses the Rails default `log_tags` functionality. Since we use lograge for request logs, this is not picked up in the logs.
- The normal logs using `Rails.logger` are not printed via JSON.
I also added some helpful information …
=> DPC-4126: Fix JSON logging and add standardized fields

docker-compose.yml, dpc-portal/app/components/core/table/row_component.rb, dpc-portal/app/controllers/application_controller.rb, dpc-portal/app/controllers/client_tokens_controller.rb, dpc-portal/app/controllers/ip_addresses_controller.rb, dpc-portal/app/controllers/public_keys_controller.rb, dpc-portal/app/models/credential_audit_log.rb, dpc-portal/app/models/provider_organization.rb, dpc-portal/config/initializers/lograge.rb, dpc-portal/db/migrate/20240620201824_create_credential_audit_logs.rb, dpc-portal/db/schema.rb, dpc-portal/spec/components/core/table/row_component_spec.rb, dpc-portal/spec/factories/credential_audit_logs.rb, dpc-portal/spec/models/credential_audit_log_spec.rb, dpc-portal/spec/models/provider_organization_spec.rb, dpc-portal/spec/requests/client_tokens_spec.rb, dpc-portal/spec/requests/ip_addresses_spec.rb, dpc-portal/spec/requests/public_keys_spec.rb, dpc-portal/spec/support/component_support.rb, dpc-portal/spec/support/credential_resource_shared_examples.rb, dpc-portal/spec/support/dpc_client_support.rb
https://jira.cms.gov/browse/DPC-3823
- Added CredentialAuditLog model with table
- Added method to application_controller for logging changes to credentials
- Call above method in each credential controller
- Log when client tokens removed from provider organization
We want to have a log of all credentials managed via the portal for auditing, debugging, and supporting future enhancements.
Automated and manual testing.
=> DPC-3823 Credential Audit Log

dpc-portal/app/components/core/navigation/step_indicator_component.html.erb, dpc-portal/app/components/core/navigation/step_indicator_component.rb, dpc-portal/app/components/core/navigation/step_indicator_component_preview.rb, dpc-portal/app/components/page/invitations/accept_invitation_component.html.erb, dpc-portal/app/components/page/invitations/register_component.html.erb, dpc-portal/app/components/page/invitations/register_component.rb, dpc-portal/app/components/page/invitations/register_component_preview.rb, dpc-portal/app/components/page/invitations/start_component.html.erb, dpc-portal/app/components/page/invitations/start_component.rb, dpc-portal/app/components/page/invitations/start_component_preview.rb, dpc-portal/app/components/page/invitations/success_component.html.erb, dpc-portal/app/components/page/invitations/success_component.rb, dpc-portal/app/components/page/invitations/success_component_preview.rb, dpc-portal/app/components/page/session/invitation_login_component.html.erb, dpc-portal/app/components/page/session/invitation_login_component_preview.rb, dpc-portal/app/controllers/invitations_controller.rb, dpc-portal/app/models/invitation.rb, dpc-portal/app/views/invitation_mailer/invite_ao.html.erb, dpc-portal/config/routes.rb, dpc-portal/spec/components/core/navigation/step_indicator_component_spec.rb, dpc-portal/spec/components/page/invitations/accept_invitation_component_spec.rb, dpc-portal/spec/components/page/invitations/register_component_spec.rb, dpc-portal/spec/components/page/invitations/start_component_spec.rb, dpc-portal/spec/components/page/invitations/success_component_spec.rb, dpc-portal/spec/components/page/session/invitation_login_component_spec.rb, dpc-portal/spec/mailers/invitation_spec.rb, dpc-portal/spec/models/invitation_spec.rb, dpc-portal/spec/requests/invitations_spec.rb
https://jira.cms.gov/browse/DPC-4129
- Added components to support flow: Step, Start, Register Success
- Registration checks split between identity and other validation
- Invitations spec uses shared examples for endpoints, same behavior for cd and ao invitations
We are expanding the registration process.
Automated and manual testing of both authorized official and credential delegate flows.
=> DPC-4129 5 step registration flow

dpc-portal/app/controllers/invitations_controller.rb, dpc-portal/app/controllers/login_dot_gov_controller.rb, dpc-portal/spec/requests/invitations_spec.rb, dpc-portal/spec/requests/login_dot_gov_spec.rb
https://jira.cms.gov/browse/DPC-4132
- login controller no longer creates user
- invitations controller requires login dot gov tokens instead of sign in
- invitations controller upserts user on confirm registration
We don't want the users table full of people unrelated to DPC, so we are only creating users after a successful invitation acceptance.
Automated and manual testing.
=> DPC-4132 Only create user on connecting to org

dpc-smoketest/pom.xml
https://jira.cms.gov/browse/DPC-4172
- tika-parsers upgraded to 2.9.2
- removed explicit upgrade of apache commons - compress to 1.26.1 because that is what 2.9.2 uses
Snyk was complaining about a vulnerability in a dependency of tika-parsers 1.28.5 (org.apache.cxf 3.5.3) and tika 2.9.2 uses org.apache.cxf 3.5.8, which does not have this vulnerability.
[Smoke test](https://management.dpc.cms.gov/job/DPC%20-%20Smoke%20Test/5491/) with this upgrade passes
=> DPC-4172: Upgrade tika-parsers

docker-compose.portals.yml, dpc-web/app/jobs/grant_access_job.rb, dpc-web/app/models/user.rb, dpc-web/spec/features/authentication/user_resets_password_spec.rb, dpc-web/spec/features/authentication/user_sign_in_spec.rb, dpc-web/spec/features/confirmation/user_confirmation_email_spec.rb, dpc-web/spec/features/registration/new_user_signs_up_for_account_spec.rb, dpc-web/spec/jobs/grant_access_job_spec.rb, dpc-web/spec/models/user_spec.rb
https://jira.cms.gov/browse/DPC-4078
- GrantAccessJob added
- User performs GrantAccessJob when confirmed_at set to non-nil
- Other specs changed to use ActiveJob::TestHelper because queue polluted by GrantAccessJob
We are not really vetting access to the sandbox, so this job will grant access automatically. We will need to set a Splunk alert on log failure so we can manually add in case of failure.
=> DPC-4078 automate sandbox approval

dpc-portal/app/models/invitation.rb, dpc-portal/spec/models/invitation_spec.rb
No ticket
Remove dashes from SSN from IdP before hashing
Our IdP started sending the ssn with dashes, which messes up our comparison logic
=> Pass AO check of login.gov sends ssn with dashes

dpc-api/pom.xml, dpc-api/src/test/java/gov/cms/dpc/api/validations/ProfileTests.java, dpc-common/pom.xml, dpc-common/src/main/resources/validations/DPCAttestation.json, dpc-common/src/main/resources/validations/DPCPatient.json, dpc-common/src/test/java/gov/cms/dpc/fhir/validations/AttestationValidationTest.java, dpc-common/src/test/java/gov/cms/dpc/fhir/validations/PatientValidationTest.java, dpc-testing/pom.xml, pom.xml
https://jira.cms.gov/browse/DPC-4171
The upgrade to 6.x only required an update to one test, so this PR covers two major version upgrades.
=> [DPC-4171] Upgrade HAPI FHIR

README.md
When attempting to run `ExpirationJobTest` from IntelliJ, using the instructions in the README section `Debugging Integration Tests`, I was getting a port collision error. This is because this particular test is unique in that it runs in DropWizard as the `attribution` service. The other integration tests run as the `dpc-api` service, and the instructions were written with those in mind. I've added the case of `ExpirationJobTest` to the README instructions for future use.
=> Add instructions for fixing ExpirationJobTest run in IntelliJ debugger

dpc-admin/app/views/shared/_head.html.erb
No ticket
Removed reference to 16x16 favicon from dpc-admin shared header, as this asset does not (and never had) existed.
When doing the POC for portals smoke tests, the test to admin failed when it attempted its default behavior to download page assets, as this asset is not available.
[POC smoke tests](https://github.com/CMSgov/dpc-app/pull/2232) passed with page asset verification on dpc-admin.
=> No Ticket: remove reference to never-existing favicon

dpc-portal/app/views/invitation_mailer/invite_ao.html.erb, dpc-portal/app/views/invitation_mailer/invite_cd.html.erb, dpc-portal/spec/mailers/invitation_spec.rb
https://jira.cms.gov/browse/DPC-4204
- Templates for cd and ao invites explicitly use https if Rails.env.production? == true
- Link to invitation in production should be https protocol
- Rails.env just means not running in development or test mode. It should be 'production' for dev and test (and eventually prod) servers
Automated testing
=> DPC-4204: use https for link to invitation

dpc-portal/app/models/invitation.rb, dpc-portal/app/services/ao_verification_service.rb, dpc-portal/db/schema.rb, dpc-portal/spec/services/ao_verification_service_spec.rb
https://jira.cms.gov/browse/DPC-4221
Hashing of ssn for comparison with ssn in information from CPI API Gateway removed. Now doing straight string matching.
Original implementation assumed we would be storing the ssn in the session, so we set it up to compare hashes. We are not storing it in the session (we either retrieve it from our IdP for the check, or we use a stored foreign key), so the hashing no longer serves any useful purpose.
Manual and Automated testing
=> DPC-4221: Remove unnecessary hashing

dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/GroupResource.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/GroupResourceTest.java
[DPC-4196](https://jira.cms.gov/browse/DPC-4196)
- fixes replaceRoster() response to include the data for the newly updated roster (e.g. the members that are `PUT` in there)
- integration test covers this scenario
- uses same refresh method from DAO class in previous PR (linked below)
This is a follow-up to #2241 
Before:
After:
See also `dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/GroupResourceTest.java`
=> [DPC-4196] - Episode II - fix replaceRoster() response

dpc-portal/Gemfile.lock
No ticket
Fugit in Gemfile.lock updated
Build failing on GHSA-2m96-52r3-2f3g
Need to upgrade to 1.11.1
We don't request fugit directly, but via sidekiq-cron. Updated by disabling check, then running `bundle update fugit` in the docker container.
Builds and passes tests
=> upgrade fugit

dpc-portal/app/components/page/credential_delegate/list_component.html.erb, dpc-portal/app/controllers/invitations_controller.rb, dpc-portal/spec/components/page/credential_delegate/list_component_spec.rb, dpc-portal/spec/requests/invitations_spec.rb
https://jira.cms.gov/browse/DPC-4252
- User names added/updated when registering
- Column removed from "Active Credential Delegates" table
Testing revealed we were not showing the Credential Delegate's name in the "Active Credential Delegates" table. It turns out that we had stopped persisting the name on create.
As long as we were in there, we removed a column for deleting a Credential Delegate's access to an organization, as we don't have the functionality and will not be implementing it for MVP.
Manual and Automated testing.
=> DPC-4252 Credential Delegate name missing

dpc-portal/app/components/page/invitations/bad_invitation_component.html.erb, dpc-portal/app/controllers/application_controller.rb, dpc-portal/app/controllers/login_dot_gov_controller.rb, dpc-portal/app/controllers/users/sessions_controller.rb, dpc-portal/config/locales/en.yml, dpc-portal/config/routes.rb, dpc-portal/spec/components/page/invitations/bad_invitation_component_spec.rb, dpc-portal/spec/requests/invitations_spec.rb, dpc-portal/spec/requests/login_dot_gov_spec.rb
https://jira.cms.gov/browse/DPC_4204
- Logout button added to BadInvitationComponent
- IDP environment variables moved to ApplicationController as used in multiple controllers
- logout and logged_out routes added to LoginDotGovController to handle logout and return from IdP
- Failed PII match text updated
Matches designs
=> DPC-4204 AO fails email check

README.md, docs/api/logging.md, docs/api/service-initialization.md
N/A
- Moved `dpc-queue` to the shared modules section, since it's not an API/service.
- Added some docs about logging and API service initialization
Adding some docs to make onboarding a little easier and help with understanding the Dropwizard services.
N/A
=> docs: Add some API architecture docs and fix dpc-queue label

dpc-portal/app/controllers/invitations_controller.rb, dpc-portal/spec/requests/invitations_spec.rb
No ticket
- user info passed to create user in invitations controller
- user info method in invitations spec renamed because bled into controller
Bug in invitations controller was masked by a method in the spec
Automated and manual testing
=> Fix create bug in portal

README.md
[[DPC-4273] ](https://jira.cms.gov/browse/DPC-4273)
- Updated README.md to include alternative steps for building the api if a build failure is encountered when following the existing procedure.
- Following README.md steps on a new laptop as part of corporate/project onboarding, a build failure was encountered running `mvn clean install`.
- [M. Esposito](https://github.com/MEspositoE14s) suggested alternative steps to resolve build failure.
- Steps were verified and build was successful.
- Revising README.md as basic intro/test of dev methodology and tools, as well as to include useful tip in README.md
- Re-tested alternative steps and verified build is successful.
=> [DPC-4273] Added tip with alternative steps to resolve build failures in manual dpc-app build steps.

.github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/DPC-4258
ci-workflow updated to find tests added to project
- Paths in .resultset.json edited to point to absolute paths in docker container that runs sonarqube
- Unit tests run for api
- Jacoco results from build-api used for api verification
The original implementation only involved making sure the workflow failed if code was outed without tests. This update makes sure the workflow passes if new code is tested.
Changes tested in https://github.com/CMSgov/dpc-app/pull/2276, which has the same workflow file. It also has new code and tests in dpc-api, dpc-portal, dpc-web, and dpc-admin.
=> DPC-4258 pass if add tests

dpc-portal/app/jobs/verify_ao_job.rb, dpc-portal/spec/jobs/verify_ao_job_spec.rb
[DPC-4299](https://jira.cms.gov/browse/DPC-4299)
- remove code that updates ProviderOrganization verification status in [verify_ao_job.rb](https://github.com/CMSgov/dpc-app/blob/acb5c1a19f3274afbdd8aad2ce3cff4be93d0c08/dpc-portal/app/jobs/verify_ao_job.rb#L7)
- an AO failing med sanction check would cause an entire organization to also be rejected. [disable_rejected()](https://github.com/CMSgov/dpc-app/blob/ca55c2499cdc2503929c10f00245ea65e76adb1d/dpc-portal/app/models/provider_organization.rb#L64) would delete the api tokens for the organization
- We no longer want this behavior, so now only the AO user is rejected
- existing test cases already cover this sidekiq job in [verify_ao_job_spec.rb](erify_ao_job_spec.rb)
- failing test cases updated to reflect changes
=> [DPC-4299] - Update AO job so sanctions don't affect org API access

src/main/resources/prod_patient_bundle-dpr.json, src/main/resources/prod_provider_bundle.json
https://jira.cms.gov/browse/DPC-4302
Removed `id` elements from prod smoke test resource files.
When the smoke tests run they load the resources from these files, and then remove them when they're finished.  If the first smoke test takes a long time, then the second will sometimes start before the first is finished and try to insert the same resources.  This leads to a primary key collision and the tests fail.  Removing the ids allows the system to generate random ones on insert so the tests can run in parallel without problems.
Note: This was already done on the test files used in the other environments.
Smoke tests ran successfully in prod [here](https://management.dpc.cms.gov/job/DPC%20-%20Smoke%20Test/5774/).
=> Remove id elements from prod smoketest test data

dpc-portal/app/assets/stylesheets/login.scss, dpc-portal/app/components/page/session/login_component.html.erb, dpc-portal/spec/components/page/session/login_component_spec.rb
[DPC-4278](https://jira.cms.gov/browse/DPC-4278)
- remove lorem ipsum placeholder text for `/portal/users/sign_in` and use latest content provided by design
- Source of truth for content under "Page for returning users to sign in" on Confluence doc [HERE](https://confluence.cms.gov/display/DAPC/DPC+Portal+MVP+Copy#:~:text=Page%20for%20returning%20users%20to%20sign%20in).
- link to sandbox on the right side of the page
- Lorem ipsum placeholder text was used beforehand.
- manually verified the content updates by running 
- `make portal && make start-portal` then navigating to `http://localhost:3100/portal/users/sign_in`
- see also updates to `dpc-portal/spec/components/page/session/login_component_spec.rb`
=> [DPC-4278] Content updates for default welcome page

dpc-portal/app/models/invitation.rb, dpc-portal/spec/models/invitation_spec.rb, dpc-portal/spec/requests/invitations_spec.rb
https://jira.cms.gov/browse/DPC-4229
In the CD invitation flow we no longer match on given name and phone number.  
These changes were made in an attempt to streamline the CD invitation process.
Tests updated to verify that first name and phone number are no longer required to match.  
**Note**: We still require that the invitation has a given name and phone number, we just don't match on them.
=> [DPC-4229] Removed given name and phone matching on cd invite

dpc-portal/app/components/page/credential_delegate/new_invitation_component.html.erb, dpc-portal/spec/components/page/credential_delegate/new_invitation_component_spec.rb
https://jira.cms.gov/browse/DPC-4329
Adds real content for the new invitation confirmation modal
We need to display a message explaining the ramifications of inviting a new credential delegate.
=> [DPC-4329] Update content for new invitation confirmation modal

docker-compose.override.yml, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceTest.java, dpc-api/src/test/java/gov/cms/dpc/api/resources/v1/GroupResourceUnitTest.java, dpc-attribution/src/main/java/gov/cms/dpc/attribution/resources/v1/GroupResource.java, dpc-attribution/src/test/java/gov/cms/dpc/attribution/resources/GroupResourceTest.java
https://github.com/CMSgov/dpc-app/compare/me/dpc-4213-create-duplicate-rosters?expand=1
Attempting to create a roster that already exists for a provider in an org will return an error.  Previously, the request would be ignored, and the already existing roster would be returned with a 200.
After much [discussion](https://cmsgov.slack.com/archives/CJL0FRN2E/p1722519081409839), I went with the majority and made the error a 403.  If we change our minds before this is merged it's only a two line change.
Ran locally and verified.
=> [DPC-4213] Add error on create existing group

dpc-portal/app/jobs/verify_resource_health_job.rb, dpc-portal/spec/jobs/verify_resource_health_job_spec.rb
No ticket
- VerifyResourceHealthJob use Rails.logger instead of logger
- Stub IDP_HOST in spec
Sidekiq:Job has its own logger that pushes to STDOUT, so it logs to console when running tests. And setting the constant manually was writing warnings to the console.
All tests pass without writing anything to the console
=> Remove console logging when running rspec

dpc-portal/Dockerfile
No ticket
Ignoring CVE-2024-2151 added to bundle audit in dpc-portal Dockerfile
[CVE-2024-2151](https://nvd.nist.gov/vuln/detail/CVE-2024-21510) is a security error in Sinatra that does not have a fix. As we use Sinatra internally for testing and as a mock CPI API Gateway (whose port is not exposed to the public internet), ignoring the warning for now seems permissible.
[DPC-4359](https://jira.cms.gov/browse/DPC-4359) removes the ignore flag when a fix becomes available.
Portal builds and passes CI.
=> Ignore sinatra vulnerability

.github/workflows/ci-workflow.yml, dpc-portal/app/controllers/invitations_controller.rb, dpc-portal/config/initializers/logging.rb, dpc-portal/spec/requests/invitations_spec.rb
https://jira.cms.gov/browse/DPC-4389
- FailAo/CdPiiCheck added to logging constants
- log when AO or CD fails PII check
We need these events logged for our Registration Failure Dashboard ([DPC-4371](https://jira.cms.gov/browse/DPC-4371))
Automated testing with log/test.log verification
=> Add PII Fail logging

dpc-portal/app/components/page/organization/new_organization_component.html.erb, dpc-portal/app/components/page/organization/tos_form_component.html.erb, dpc-portal/spec/components/page/organization/tos_form_component_spec.rb
https://jira.cms.gov/browse/DPC-4373
Removes stray path link.
=> [DPC-4373] Remove unneeded path link

lambda/opt-out-export/db.go, lambda/opt-out-import/db.go
https://jira.cms.gov/browse/DPC-4415
Conditionally force sslmode depending on environment
In our upgrade to postgres 16, we have to use ssl. We had ssl turned off for our lambdas so they could run against our local database (for testing), which are not set up for ssl. New code runs in sslmode except when 'testing' (which includes running locally)
Tested both locally (test and run-local)
Uploaded export to test and it worked.
Uploaded import to test but unsure how to test?
=> Use ssl to connect to databases in lambdas

dpc-portal/app/components/page/credential_delegate/list_component.html.erb, dpc-portal/app/components/page/credential_delegate/list_component.rb, dpc-portal/app/components/page/credential_delegate/list_component_preview.rb, dpc-portal/app/components/page/organization/compound_show_component.html.erb, dpc-portal/app/components/page/organization/compound_show_component.rb, dpc-portal/app/components/page/organization/compound_show_component_preview.rb, dpc-portal/app/controllers/organizations_controller.rb, dpc-portal/app/models/invitation.rb, dpc-portal/spec/components/page/credential_delegate/list_component_spec.rb, dpc-portal/spec/components/page/organization/compound_show_component_spec.rb, dpc-portal/spec/requests/organizations_spec.rb
https://jira.cms.gov/browse/DPC-4402
- Added a table to the list view component for expired invitations
- Query for expired invitations during OrganizationsController#show action
- Filter out expired invitations from the pending invitations query in OrganizationsController#show action
We want to render a list of expired invitations, so that the AO can keep track and initiate a new invitation if need be.
=> [DPC-4402] Add Expired Invitations list to Organization view for AO

dpc-portal/app/jobs/log_organizations_api_credential_status_job.rb, dpc-portal/spec/jobs/log_organizations_api_credential_status_spec.rb
This is a follow-up to https://github.com/CMSgov/dpc-app/pull/2327 for [DPC-4390](https://jira.cms.gov/browse/DPC-4390).
- wrap DpcApiClient calls so if an exception is raised, the sidekiq job can continue to run for organizations with successful API calls (see context below)
- following the automatic deployment to the dev environment, I observed that the sidekiq job was not emitting the expected message in the logs.
- it appears that one of the organizations on the dev environment has an invalid UUID, causing get_client_tokens() to fail
=> Add exception handling to LogOrganizationsApiCredentialStatusJob

dpc-portal/app/models/invitation.rb, dpc-portal/spec/models/invitation_spec.rb
No ticket
Filter was added to Invitation#expired?
Accepted CD invitations were showing up in the expired invitations block. They shouldn't.
=> Expired should not include accepted, cancelled, or renewed invitations

.github/workflows/opt-out-export-dev-deploy.yml, .github/workflows/opt-out-import-dev-deploy.yml
No ticket
Build in github actions changed to disable using CGO
CGO is disabled in the builds for other environments and they work. It was not enabled in dev builds, and they had 'GLIBC not found' errors when run.
Pushed to dev with branch github actions and export worked.
=> Disable cgo in opt out lambdas because does not work

dpc-admin/config/initializers/health_check.rb
No ticket
Removed 'migrations' from admin healthcheck
Admin does not manage its own database, and for some reason decided to be miffed about this.
Health check passes.
=> remove migrations from check (it does not have a database)

dpc-portal/app/components/page/organization/compound_show_component.html.erb, dpc-portal/app/components/page/organization/compound_show_component_preview.rb, dpc-portal/spec/components/page/organization/compound_show_component_spec.rb
https://jira.cms.gov/browse/DPC-4432
Adds org id to details page.
As any portal user
I want to see org ID below the org name/NPI on the org details page 
so that I can use it as a reference for API setup
Spec updated.
=> [DPC-4432] Add org ID to details page

.github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/DPC-4448
actions/(upload|download)-artifact updated to v4 in ci-workflow.yml
We are closing down access to v3 on January 30, 2025. See https://jira.cms.gov/browse/PLT-832
grepped workflows directory and found usage only in ci-workflow.yml
Upgraded to v4 and still ran successfully
=> Upgrade to Artifacts Actions to v4

.github/workflows/tag-for-release.yml, .github/workflows/tag_release.yml
https://jira.cms.gov/browse/DPC-4453
Go back to fetching everything as separate step.
Previous fix tried to optimize fetching tags. Turns out, it doesn't work.
Runners try to do the least work possible, so it was saving previously-fetched tags. Running a different workflow forced a complete clean of the directory, so the next time this workflow was run, it didn't have any tags.
Successful run: https://github.com/CMSgov/dpc-app/actions/runs/12601770911/job/35123530838
=> DPC-4453  - revert fetch optimization

.github/workflows/ci-workflow.yml, dpc-portal/Dockerfile
https://jira.cms.gov/browse/DPC-4359
Removed ignore flag in dpc-portal/Dockerfile
CVE-2024-21510 is a vulnerability in Sinatra that was fixed in 4.1.0, which we had already upgraded to.
Removed ignore flag and everything still worked
=> Remove check for CVE-2024-21510

.github/workflows/dpc-load-test.yml
None
This changes the name of the NEW_RELIC_API_KEY secret to LOAD_TEST_NEW_RELIC_API_KEY.
The original name was too generic. For the Load Test use case, we specifically need an INGEST key, and as such, it is likely not useful for other use cases. By specifying the use case, others can create and add keys of their own for their own use cases.
=> [NO TICKET] Update new relic api key secret name

docker-compose.portals.yml, docker-compose.yml, dpc-bluebutton/src/main/java/gov/cms/dpc/bluebutton/client/MockBlueButtonClient.java, dpc-bluebutton/src/test/java/gov/cms/dpc/bluebutton/client/MockBlueButtonClientUnitTest.java, dpc-test.sh, src/main/resources/bb-test-data/patient/-19990000000001.json, src/test/resources/bb-test-data/empty.json, src/test/resources/bb-test-data/patient/-19990000000001.json
https://jira.cms.gov/browse/DPC-4456
- Update ci tests to use the mockBfdClient for dpc-api.
- Update mockBfdClient to support the synthetic patient we search for in prod BFD to load transaction time.
Our integration tests run as part of `make ci-app` relied on dpc-api being connected to the real production BFD system, and dpc-aggregation using our mockBfdClient.  This PR makes the whole test suite use the mockBfdClient and makes things generally more reliable.
This fixes the Jenkins build problems due to dpc-api failing its health check because it couldn't connect to BFD.
Example [here](https://management.dpc.cms.gov/job/DPC%20-%20Docker%20Build/4382/)
Passing run [here](https://management.dpc.cms.gov/job/DPC%20-%20Full%20Deploy%20and%20Release/2829/)
Ran locally and in Jenkins.
=> [DPC-4456] Update ci to use mock bfd client for all tests

dpc-admin/Dockerfile, dpc-portal/Dockerfile, dpc-web/Dockerfile, engines/api_client/Dockerfile
No ticket
yaml-dev and libffi-dev added to docker image for webapps
psych and ffi gems stopped building, and these libraries allow them to build
Builds
=> Fix gem build issues

dpc-api/src/test/java/gov/cms/dpc/api/auth/PublicKeyHandlerTest.java, dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/filters/FHIRAsyncRequestFilterTest.java, dpc-common/src/test/java/gov/cms/dpc/fhir/dropwizard/filters/FHIRRequestFilterTest.java
https://jira.cms.gov/browse/DPC-4457
assertDoesNotThrow added to tests without assertions:
- FHIRRequestFilterTest: testSuccess, testNestedAcceptsHeader, testNullContentHeader, testTestedContentHeader
- FHIRAsyncRequestFilterTest: testCorrectAcceptsHeader, testMultipleAcceptsHeader, testCorrectPreferHeader
- PublicKeyHandlerTest: testValidKey
Although any exception will cause a test to fail, Sonarqube complains about [tests without assertions](https://sonarqube.cloud.cms.gov/project/issues?resolved=false&scopes=TEST&severities=BLOCKER&id=bcda-dpc-api): Add at least one assertion to this test case.
Ran ci-workflow against this branch; [sonarqube no longer complains about this issue](https://sonarqube.cloud.cms.gov/project/issues?resolved=false&severities=BLOCKER&branch=jd%2Fdpc-4457-test-as …
=> DPC-4457 Add assertDoesNotThrow to tests without assertions

Makefile, dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/ClientUtils.java
https://jira.cms.gov/browse/DPC-4461
Ensures that when running local smoke tests dpc-api is up and connected to the real BFD.
Local smoke tests were sometimes failing because we recently defaulted to using our mockBfdClient when running for most processes, and the smoke tests need a connection to the real BFD. If you had previously ran dpc with `USE_BFD_MOCK` set to true and then ran the smoke tests they would fail.
Run `make smoke/local` and everything should pass.
=> [dpc-4461] Make sure local smoke tests are initialized correctly

.github/workflows/api-waf-sync-deploy.yml, .github/workflows/api-waf-sync-test-integration.yml, .github/workflows/check_healthy.yml, .github/workflows/deploy_go_lambda.yml, .github/workflows/dpc-portal-accessibility-test.yml, .github/workflows/opt-out-export-deploy.yml, .github/workflows/opt-out-export-test-integration.yml, .github/workflows/opt-out-import-deploy.yml, .github/workflows/opt-out-import-test-integration.yml, .github/workflows/opt-out-import-unit.yml, .github/workflows/tag_release.yml
https://jira.cms.gov/browse/DPC-4472
Top-level names changed for multiple workflows.
I had left 'dev' in some workflow names, and thought standardizing naming would be useful.
After merge, will verify names in Actions look better.
=> DPC-4472 fix workflow names

package-lock.json, package.json
No ticket
newman pinned to 6.1.3 in package.json
newman runs our postman tests in ci. Current version of newman does not work with node > 22.2.0, which ends life 4/2026. Old version works with new node.
Ran newman locally against node 23 and it worked.
=> Downgrade newman

.github/workflows/ci-workflow.yml, dpc-test.sh, engines/api_client/Dockerfile, scripts/cleanup-docker.sh
https://jira.cms.gov/browse/DPC-4478
- ci-workflow.yml updated to use self hosted runners
- cleanup-docker.sh added to avoid duplication
- dcp-test.sh no longer removes database volume between tests
- api_client dockerfile removed unnecessary packages
For security reasons, we should be using self-hosted runners instead of github runners. Moving to self-hosted runners required us to manually install python, maven, docker compose, and npm.
We also kept running out of disk space, so cleaning up docker (via the new cleanup-docker.sh) and removing unnecessary packages from the api_client were necessary.
We had to leave the database volume between tests because of some race condition making dpc-consent not start up.
There is also a drive-by fix to sonarqube, which stopped finding tests for the …
=> DPC-4478 self hosted ci workflow

.github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/DPC-4478
ci-workflow.yml reverted to running on github runners
Although the self-hosted runners work in principle, the infrastructure does not support it, and its failures are blocking PRs.
CI runs successfully
=> revert to github runner workflow

.github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/DPC-4502
Process for importing test results into sonarqube changed for Rails apps.
The old system of updating the test results for sonarqube was failing, resulting in 0 lines covered.
Coverage for lines Rails apps in sonarqube greater than 0.
=> DPC-4502 Fix sonarqube test coverage in Rails apps

.github/workflows/docker_build.yml
[DPC-4496](https://jira.cms.gov/browse/DPC-4496)
- Remove obsolete commented out code
- remove job for building just web-portal
- 2 new jobs
- ea rails app will be built and then uploaded as an artifact
- the second job will pull down that artifact and push to AWS ECR
- currently experiencing issues w/ self-hosted GHA runners running out of disk space, so these jobs were separated out as opposed to a single `make ci-portals-v1` command 
- in practice, the java apps still take a majority of the time, but this gives feedback to the developer sooner if one of the rails apps fails to build
- Example CI job [here](https://github.com/CMSgov/dpc-app/actions/runs/13185239034)
=> [DPC-4496] use upload/download artifacts for rails docker builds

.github/workflows/docker-build.yml
No ticket
docker-build.yml generate_docker_tag stanza echoes docker tag in same step it generates.
Echoing in other step did not always work.
Ran [workflow](https://github.com/CMSgov/dpc-app/actions/runs/13289770580/job/37107324124) and tag in output.
=> Show Docker Image Tag on generation

.github/workflows/ecs-deploy.yml, .github/workflows/promote-build.yml, dpc-admin/Gemfile.lock, dpc-portal/Dockerfile, dpc-portal/Gemfile.lock, dpc-web/Gemfile.lock
https://jira.cms.gov/browse/DPC-4525
- promote-build.yml added
- ecs-deploy.yml fix
We are migrating from Jenkins to Github Actions. This workflow replaces '[DPC - Promote Build](https://github.com/CMSgov/dpc-ops/blob/main/jenkins_files/Jenkinsfile.promote_build)'.
Note: Jenkins has a feature in which you can look up the parameters of other jobs. This feature is not available in Github Actions. Therefore, this promotion always uses the main branch of dpc-ops. We _could_ add this as a parameter, but I think the cleaner interface is better.
[Ran](https://github.com/CMSgov/dpc-app/actions/runs/13317487378/job/37194959257) and verified correct image and app_version deployed.
=> DPC-4525 Github Actions Promote Build

.github/workflows/tag-for-release.yml, .github/workflows/tag_release.yml
https://jira.cms.gov/browse/DPC-4533
tag_release utility changed to add all changes since last release to release documentation.
There were two issues. First, the fetch-depth needed to be set to zero in checking out the code. Second setting the output variable required special multi-line handling.
Also a minor update to the trigger allows for testing by using the current branch.
Tagging ran successfully (and was then deleted).
=> DPC-4533 Add all changes to release documentation

.github/workflows/promote-build.yml
No ticket
"inputs" added to workflow dispatch, default 'to' changed to 'test'
Workflow_dispatch was missing "inputs" key; defaulted to promoting to same as from
Inputs currently available for promote from this branch
=> Add params to promote

dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionFHIRTest.java
https://jira.cms.gov/browse/DPC-4476
Removes erroneous creation of roster in tests.
AttributionFHIRTest was disabled because of a failure in the SUBMIT tests. This PR removes the additional call to `create`.
Tests updated.
=> [DPC-4476] Enable AttributionFHIRTest.java

dpc-attribution/src/main/resources/migrations.xml, dpc-common/src/main/java/gov/cms/dpc/common/entities/ContactPointEntity.java
No ticket.
Updates column name.
Before upgrading to Java 17, we need to update this column name, as "value" is a protected term.
Tests passing, including smoke.
=> Update contact_telecoms column name

dpc-portal/app/components/page/invitations/accept_invitation_component.html.erb, dpc-portal/app/components/page/invitations/invitation_login_component.html.erb, dpc-portal/app/components/page/invitations/register_component.html.erb, dpc-portal/app/components/page/invitations/start_component.html.erb, dpc-portal/app/components/page/invitations/success_component.html.erb, dpc-portal/app/models/invitation.rb, dpc-portal/spec/components/page/invitations/accept_invitation_component_spec.rb, dpc-portal/spec/components/page/invitations/ao_flow_fail_component_spec.rb, dpc-portal/spec/components/page/invitations/invitation_login_component_spec.rb, dpc-portal/spec/components/page/invitations/register_component_spec.rb, dpc-portal/spec/components/page/invitations/start_component_spec.rb, dpc-portal/spec/components/page/invitations/success_component_spec.rb
https://jira.cms.gov/browse/DPC-4541
Adds portal welcome page to step tracker as first step.
UX research suggested that users would prefer to see the step tracker as soon as possible, to better ascertain how long the process would take.
AO welcome page
CD welcome page
=> Add welcome page to step tracker

.github/workflows/load-test-unit-tests.yml, dpc-load-testing/README.md, dpc-load-testing/__tests__/mbi-generator.test.js, dpc-load-testing/__tests__/npi-generator.test.js, dpc-load-testing/package.json, dpc-load-testing/script.js, dpc-load-testing/utils/mbi-generator.js, dpc-load-testing/utils/npi-generator.js, dpc-load-testing/utils/test-utils.js, dpc-load-testing/yarn.lock
https://jira.cms.gov/browse/DPC-4551
- New code generates valid NPIs and MBIs, for use in load testing. 
- Runs unit tests for these utilities in GH Actions
Info on NPI validation: https://www.eclaims.com/articles/how-to-calculate-the-npi-check-digit/
Info on MBI format: https://www.cms.gov/medicare/new-medicare-card/understanding-the-mbi-with-format.pdf
When we're running load tests, we'll need to generate an arbitrary number of valid identifiers when we create Providers and Patients.
=> [DPC-4551] Generate fake NPIs and MBIs

dpc-portal/app/components/page/invitations/invitation_login_component.html.erb
https://jira.cms.gov/browse/DPC-4593
- Update "Login.gov FAQ" link to "Login.gov help" on sign in or create page.
- Updated link to open in new tab.
Changes asked for by design/content after UAT.
Ran locally.
=> [dpc-4593] Update login.gov link

dpc-portal/config/locales/en.yml
https://jira.cms.gov/browse/DPC-4597
Messages for expired CD invitation updated
Original message included invite code, which is no longer a thing.
Matches requested message
=> DPC-4597 Update Expired CD Invitation Screen

dpc-portal/app/components/page/invitations/bad_invitation_component.html.erb, dpc-portal/spec/components/page/invitations/bad_invitation_component_spec.rb
https://jira.cms.gov/browse/DPC-4592
- Removed "Go to DPC home" button from invalid invitation page.
- Updated "Go to DPC home" button on CD already accepted page to point to sign in page.
Changes requested from content/design.
Ran locally and all tests pass.
Invalid Invitation:
CD Already Accepted:
=> Update home buttons

Makefile
https://jira.cms.gov/browse/DPC-4583
Makefile targets `start-app-debug` and `start-it-debug` updated so they start the system with the debugger and db ports open.
In testing, it was noticed that `start-dpc-debug` and `start-app-debug` weren't opening the DB port for easier debugging.
Ran locally and verified that the DB and debugger ports are open.
=> Update it-debug make targets

dpc-portal/app/components/page/organization/compound_show_component_preview.rb
None
Updated Page -> Organization -> Compound Show -> Authorized Official and Credential Delegate to no longer error out.
Noticed while using Lookbook that these were failing.
Run Lookbook and see that the previews work again.
=> [Bugfix] Lookbook preview fix for compound_show_component

.github/workflows/ecs-deploy.yml
https://jira.cms.gov/browse/DPC-4605
Terraform installed in ecs-deploy.yml increased to 1.10.5
In order to set up our terraform state backends properly, we need to upgrade to 1.10.5. Also upgraded dependencies to ensure compatibility.
Deployed to dev using Github actions:
-    Without changes: https://github.com/CMSgov/dpc-app/actions/runs/14523894541
-   With new images: https://github.com/CMSgov/dpc-app/actions/runs/14524016825
=> DPC-4605 Upgrade terraform in deploy action

dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java, dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/ResourceWriter.java, dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/engine/JobBatchProcessorUnitTest.java, dpc-queue/src/main/java/gov/cms/dpc/queue/models/JobQueueBatchFile.java
https://jira.cms.gov/browse/DPC-4660
Updated DPC Metric logs to capture patientid, processing time  and file size for each resource 
These changes are made to log on splunk to understand hwo long it takes to process a single patient and the size of files it generates 
this is a simple log change and we are logging PatientId not patietnMBI and doesnt impact 
- Adds a new software dependency or dependencies. NO 
- Modifies or invalidates one or more of our security controls. NO 
- Stores or transmits data that was not stored or transmitted before. NO 
- Requires additional review of security implications for other reasons. NO 
Changes will be validated by running our tests and inspecting logs
=> DPC-4660 Patient Aggregation Logs

Makefile, dpc-load-testing/constants.js, dpc-load-testing/stress-test.js
https://jira.cms.gov/browse/DPC-4633
- Adds a configuration object for stress tests
- Sets a maxVUs number for stress tests
- Creates a new Makefile command to run stress tests locally
This allows us to run stress tests as part of our load testing suite. Stress tests are designed to ramp up the load to test the limits of an API -- in our case, we'll ramp up from 1x of the average load, to 2x, 3x, and finally 5x, in half hour increments.
=> [DPC-4633] Configure Stress Test

dpc-portal/spec/system/accessibility_spec.rb
https://jira.cms.gov/browse/DPC-4679
Increases Axe accessibility standard to WCAG 2.1AA.
We want our portal to be accessible to a higher standard than default.
[Accessibility tests](https://github.com/CMSgov/dpc-app/actions/runs/14624557229) running as expected.
=> Update WCAG level

dpc-load-testing/__tests__/npi-generator.test.js, dpc-load-testing/eslint.config.js, dpc-load-testing/lib/luhn.js, dpc-load-testing/utils/npi-generator.js
https://jira.cms.gov/browse/DPC-4673
Fixes the NPI Generator by pulling in the [luhn-js](https://www.npmjs.com/package/luhn-js) library, replacing my hand-made implementation of the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm).
During some testing, we found that POST v1/Practitioner was returning 400 errors after around 6 iterations. As it turns out, this was due to some errors in our NPI Generator. Pulling in the luhn-js third party library to replace the faulty logic resolves this problem. 
Because K6 does not run a Node.js runtime, we're unable to pull in NPM modules the usual way. I opted to get around this by pulling the library's main file into the `lib` directory, and import from there.
You can test this by updating `single-iteration.js` to run more than 6 total …
=> [DPC-4673] Fix NPI Generator

dpc-attribution/src/test/java/gov/cms/dpc/attribution/AttributionFHIRTest.java
N/A
- disables AttributionFHIRTest
There was an attempt to resolve this ticket with https://github.com/CMSgov/dpc-app/pull/2577. This appears to have not been the solution, and now we're seeing an increased failure rate. This is blocking PRs and builds on main, which is killing our velocity at a time when we have the looming Greenfield cutover. Let's disable this for now and revisit once the pressure's off.
=> [NO TICKET] disable AttributionFHIRTest

.github/workflows/docker-build.yml, .github/workflows/ecs-release.yml
(no ticket) This is a follow-up to https://github.com/CMSgov/dpc-app/pull/2625
Slack discussion [HERE](https://cmsgov.slack.com/archives/C04UG13JF9B/p1746640468842269)
- fix formatting for the way the consent image is cached for runners to push consent image to ECR
=> fix gzip consent command not saving image properly

dpc-portal/lib/dpc_portal_utils.rb, dpc-portal/spec/lib/dpc_portal_utils_spec.rb
https://jira.cms.gov/browse/DPC-4700
- Use HOST_NAME from environment variables to set login.gov callback url
We need to be able to get the correct URL when running in Greenfield. 
This depends on changes submitted in https://github.com/CMSgov/dpc-ops/pull/808/
=> [DPC-4700] use HOST_NAME for login.gov callback url

engines/api_client/app/services/dpc_client.rb, engines/api_client/spec/services/dpc_client_spec.rb
https://jira.cms.gov/browse/DPC-4701
https://jira.cms.gov/browse/DPC-4704
Adds a flag to `DpcClient` that allows it to ignore whether the endpoint it's connecting to has a valid certificate.
In GF, we're connecting our Rails apps to dpc-api through the internal load balancer over https, and it doesn't have a certificate.  Without this flag, our apps refuse to connect.  
This requires https://github.com/CMSgov/dpc-ops/pull/811
Deployed to Greenfield non-prod and was able to create an account in dpc-web, then create a token and a private key.
=> [DPC-4704, DPC-4701] Add allow_invalid_cert flag to DpcEngine

.github/workflows/opt-out-export-deploy-gf.yml
No ticket
duplicate permission stanza removed from opt-out-export-deploy-gf.yml
Invalid yaml
No longer flagged as invalid
=> remove duplicated permission

maven-config.sh
None, quick fix.
Fixes `maven-config.sh` not handling blank lines in our decrypted `local.env` file.
Somewhere along the way we added a blank line at the end of `ops/config/decrypted/local.env`.  `maven-config.sh` reads this and adds an empty parameter to `./mvn/maven.config` that breaks our build commands.  This PR makes sure we ignore empty lines and generate a valid `maven.config`.
Run `make maven-config`, then open the `maven.config` file and make sure there's not a line with just `-D` and no parameter.
=> [None] Fix maven-config.sh

.github/workflows/check_healthy_gf.yml, .github/workflows/ecs-deploy-gf.yml
https://jira.cms.gov/browse/DPC-4764
ecs-deploy-gf workflow updated to point to non-prefixed dpc-ops directory for deployment.
Run check_healthy on codebuild.
We are removing explicit references to greenfield in our operations processes as part of post-migration cleanup
Successfully ran deploy workflow using [dpc-ops branch](https://github.com/CMSgov/dpc-ops/pull/842) with gf- prefixes removed: https://github.com/CMSgov/dpc-app/actions/runs/15909902931
=> DPC-4764 remove 'gf-' prefix from directories in dpc-ops

dpc-bluebutton/pom.xml, dpc-queue/pom.xml
No ticket.
Upgrades netty-handler-proxy and awssdk.cloudwatch
Our version of cloudwatch was introducing a transitive vulnerability that needed to be excluded for the netty-handler-proxy upgrade to be clean on Snyk. The [automated PR](https://github.com/CMSgov/dpc-app/pull/2697) did not include this exclusion.
Passes Snyk security test.
=> Upgrade netty-handler-proxy

.github/workflows/dpc-web-accessibility-test.yml, Makefile, dpc-web-accessibility-test.sh, dpc-web/Gemfile, dpc-web/Gemfile.lock, dpc-web/config/environments/test.rb, dpc-web/docker/accessibility-test.sh, dpc-web/spec/spec_helper.rb, dpc-web/spec/system/accessibility_spec.rb
https://jira.cms.gov/browse/DPC-4782
- Makefile added ci-web-accessibility
- .github/workflows/dpc-web-accessibility-test.yml to run via github actions
- dpc-web-accessibility-test.sh to run the accessibility tests from the command line
- dpc-web/Gemfile: added axe gems
- dpc-web/config/environments/test.rb: use file system for assets
- dpc-web/docker/accessibility-test.sh: created to add firefox to container and run accessibility tests
- dpc-web/spec/spec_helper.rb: require axe, enable localhost web connect
- dpc-web/spec/system/accessibility_spec.rb: one accessibility test to show system working
We need to add automated accessibility tests to dpc-web. This PR is based on the setup of dpc-portal, which already has accessibility tests. See https://github.com/CMSgov/dpc-app/pull/2315/files …
=> DPC-4782: Infrastructure for dpc-web accessibility tests

dpc-aggregation/src/test/java/gov/cms/dpc/aggregation/AggregationServiceTest.java
Bugfix
In `AggregationServiceTest`, added a longer delay when waiting for the service to shut down.
This test was failing intermittently when run on Github, but not locally.  This _should_ fix it.  If the issue crops up again I'd consider bumping it up to 30 seconds, or just removing the test altogether.
Ran 10 times in a row over 2 days on Github with no failures:
1.  https://github.com/CMSgov/dpc-app/actions/runs/16323252682/job/46106473335?pr=2726
2.  https://github.com/CMSgov/dpc-app/actions/runs/16324109865/job/46109505579?pr=2726
3.  https://github.com/CMSgov/dpc-app/actions/runs/16324109865/job/46115670719?pr=2726
4.  https://github.com/CMSgov/dpc-app/actions/runs/16326415641/job/46117599239?pr=2726
5.  https://github.com/CMSgov/dpc-app/actions/runs/16327730602/job/46122132683?pr=27 …
=> [Bugfix] Add Longer Wait for Aggregation Shut Down Test

dpc-smoketest/src/main/java/gov/cms/dpc/testing/smoketests/SmokeTest.java
https://jira.cms.gov/browse/DPC-2802
Due to https://github.com/CMSgov/dpc-app/pull/2739, the default HAPI client no longer sends a `Prefer` header.  The smoke tests were depending on it, though, so this adds it back in.
As part of the previous PR, we removed the default `Prefer` header from our HAPI client because it shouldn't be sent on every request.  The smoke tests relied on it being there, though, instead of only adding it when necessary.  This gets them working again.
Smoke tests pass: https://github.com/CMSgov/dpc-app/actions/runs/16477267873
=> [DPC-2802] Bugfix Smoketests

engines/api_client/Makefile, engines/api_client/README.md, engines/api_client/app/services/dpc_client.rb, engines/api_client/spec/services/dpc_client_spec.rb
No ticket
Updated fetch of ALLOW_INVALID_SSL_CERT to be false unless set
Running local was failing because ALLOW_INVALID_SSL_CERT was not set. We could always force it to be set, or assume false if it wasn't set. The latter made more sense to me.
Ran dpc-portal locally with the new client and successfully added a public key.
=> Portal works even if ALLOW_INVALID_SSL_CERT not set

dpc-portal/Dockerfile, dpc-portal/bin/dev, dpc-portal/bin/nonprod, dpc-portal/bin/sidekiq-dev, dpc-portal/bin/sidekiq-nonprod
https://jira.cms.gov/browse/DPC-4812
Moved Foreman gem into the portal Docker image.
We had been installing Foreman on a per environment basis when the portal starts up, but as part of https://github.com/CMSgov/dpc-ops/pull/853 we won't be able to write to our containers anymore.  That means we can no longer install anything, so we're adding Foreman to the Docker image ahead of time instead.  The trade off is it'll get installed regardless of whether we actually intend to use it, but I don't think that's a big deal.
Full build and deploy with passing smoke tests [https://github.com/CMSgov/dpc-app/actions/runs/16526473477](https://github.com/CMSgov/dpc-app/compare/main...me/here).
=> [DPC-4812] Moved foreman to Docker image

dpc-portal/spec/spec_helper.rb, dpc-web/spec/spec_helper.rb
No ticket.
spec_helper for dcp-web and dpc-portal allow calls to release-assets.githubusercontent.com instead of objects.githubusercontent.com
Something changed, so the call for the gecko driver for accessibility tests used a different host, so webmock complained of real calls.
Accessibility tests only fail on the fact that the sites fail axe standards instead of webmock exceptions:
dpc-web: https://github.com/CMSgov/dpc-app/actions/runs/16993607204
dpc-portal: https://github.com/CMSgov/dpc-app/actions/runs/16993614683
=> Update webmock allows for accessiblity tests

.github/workflows/docker-build.yml, .github/workflows/ecs-release.yml
No Ticket
- docker build GHA takes optional 'block_release_tag'
- ecs release GHA uses block_release_tag to only create release on explicit workflow dispatch
- Moved all version tag creation to docker build GHA to DRY up code
Previous logic allowed multiple release builds made by our daily dev check. This created builds that pushed the images in use out due to our ECR lifecycle. 
Successful build and deploy: https://github.com/CMSgov/dpc-app/actions/runs/17680391735
Tested logic alone before applying to flow:
Use "tagged result" on workflow dispatch: https://github.com/CMSgov/dpc-app/actions/runs/17677484300
Reverse logic (block tagged result on workflow dispatch): https://github.com/CMSgov/dpc-app/actions/runs/17677373329
Block tagged result on "fail" in retrieving tagged result: …
=> Block release tag from scheduled builds

dpc-web/config/environments/test.rb
No ticket
Eager load app in test environment
dpc-web tests are intermittently failing since the upgrade to Rails 8. It looks related to [this issue](https://github.com/heartcombo/devise/pull/5695). Although eager loading is probably not the best solution, it should do until devise fixes it.
Before fix, tests failed with the following seeds: 28654 and 24842. They pass with the fix.
In the dpc web container:
`bundle exec rspec --seed 39498`
=> Fix web test flakiness

dpc-api/src/test/java/gov/cms/dpc/api/tasks/GenerateClientTokenTests.java, pom.xml
No ticket
- pitest upgraded
- unnecessary import removed
Snyk found a vulnerability in our (very old) version fixed by upgrade.
Fix showed an odd import that was unnecessary and thus removed.
This change only affects tests.
Tests pass.
=> Upgrade pitest
